/* 
 * File: TeAP_e_HMIPopUp.h 
 *   
 * Code generated for Simulink model ''. 
 *  
 * Model version                  :  
 * Simulink Coder version         :  
 * C/C++ source code generated on : Wed Nov 12 18:10:04 2025 
 * Embedded hardware selection: 
 */

#ifndef RTW_HEADER_TeAP_e_HMIPopUp_h_
#define RTW_HEADER_TeAP_e_HMIPopUp_h_
#include "rtwtypes.h"


typedef enum
{
    TeAP_e_HMIPopUp_IDLE = 0, /* Default value */ 
    TeAP_e_HMIPopUp_SHIFT_TO_DRIVE = 1,
    TeAP_e_HMIPopUp_SEARCHING_MOVE_FORWARD = 2,
    TeAP_e_HMIPopUp_SEARCHING_MOVE_FORWARD_SPEED_TOO_HIGH = 3,
    TeAP_e_HMIPopUp_SPACE_FOUND_STOP = 4,
    TeAP_e_HMIPopUp_SPACE_FOUND_STOP_STANDSTILL = 5,
    TeAP_e_HMIPopUp_SPACE_FOUND_SPEED_TOO_HIGH = 6,
    TeAP_e_HMIPopUp_SPACE_FOUND_SELECT_SPACE = 7,
    TeAP_e_HMIPopUp_PERP_SELECT_LEFT = 8,
    TeAP_e_HMIPopUp_PERP_SELECT_LEFT_FORWARD_AVAIL = 9,
    TeAP_e_HMIPopUp_PERP_SELECT_LEFT_REVERSE_AVAIL = 10,
    TeAP_e_HMIPopUp_PERP_SELECT_LEFT_FORWARD = 11,
    TeAP_e_HMIPopUp_PERP_SELECT_LEFT_REVERSE = 12,
    TeAP_e_HMIPopUp_PERP_SELECT_RIGHT = 13,
    TeAP_e_HMIPopUp_PERP_SELECT_RIGHT_FORWARD_AVAIL = 14,
    TeAP_e_HMIPopUp_PERP_SELECT_RIGHT_REVERSE_AVAIL = 15,
    TeAP_e_HMIPopUp_PERP_SELECT_RIGHT_FORWARD = 16,
    TeAP_e_HMIPopUp_PERP_SELECT_RIGHT_REVERSE = 17,
    TeAP_e_HMIPopUp_DISCLAIMER = 18,
    TeAP_e_HMIPopUp_PARALLEL_EXIT_SELECT = 19,
    TeAP_e_HMIPopUp_PARALLEL_EXIT_STOP = 20,
    TeAP_e_HMIPopUp_REMOVE_HANDS_FEET = 21,
    TeAP_e_HMIPopUp_FULL_AUTO_ACTIVE_FRONT = 22,
    TeAP_e_HMIPopUp_FULL_AUTO_ACTIVE_REAR = 23,
    TeAP_e_HMIPopUp_PAUSED_PRESS_BUTTON = 24,
    TeAP_e_HMIPopUp_PAUSED_OBJECT_IN_PATH = 25,
    TeAP_e_HMIPopUp_COMPLETE_PROCEED = 26,
    TeAP_e_HMIPopUp_COMPLETE_RELEASE = 27,
    TeAP_e_HMIPopUp_SPACE_FOUND_REMOVE_HANDS_LEFT = 28,
    TeAP_e_HMIPopUp_SPACE_FOUND_REMOVE_HANDS_RIGHT = 29,
    TeAP_e_HMIPopUp_PARALLEL_EXIT_REMOVE_HANDS_LEFT = 30,
    TeAP_e_HMIPopUp_PARALLEL_EXIT_REMOVE_HANDS_RIGHT = 31,
    TeAP_e_HMIPopUp_WAIT_FOR_STEER_FRONT = 32,
    TeAP_e_HMIPopUp_WAIT_FOR_STEER_REAR = 33,
    TeAP_e_HMIPopUp_MOVE_BACKWARD = 34,
    TeAP_e_HMIPopUp_STOP_FRONT = 35,
    TeAP_e_HMIPopUp_STOP_REAR = 36,
    TeAP_e_HMIPopUp_SHIFT_TO_DRIVE_GUIDANCE = 37,
    TeAP_e_HMIPopUp_MOVE_FORWARD = 38,
    TeAP_e_HMIPopUp_SHIFT_TO_REVERSE = 39,
    TeAP_e_HMIPopUp_COMPLETE_HMI_FRONT = 40,
    TeAP_e_HMIPopUp_COMPLETE_HMI_REAR = 41,
    TeAP_e_HMIPopUp_DOOR_OPEN_FULLSCREEN = 42,
    TeAP_e_HMIPopUp_LIFEGATE_OPEN_FULLSCREEN = 43,
    TeAP_e_HMIPopUp_ESC_ACTIVE_FULLSCREEN = 44,
    TeAP_e_HMIPopUp_SPEED_TOO_HIGH_FULLSCREEN = 45,
    TeAP_e_HMIPopUp_LO4_ACTIVE_FULLSCREEN = 46,
    TeAP_e_HMIPopUp_TRAILER_CONNECTED_FULLSCREEN = 47,
    TeAP_e_HMIPopUp_SERVICE_REQUIRED_FULLSCREEN = 48,
    TeAP_e_HMIPopUp_FRONT_WIPE_FULLSCREEN = 49,
    TeAP_e_HMIPopUp_REAR_WIPE_FULLSCREEN = 50,
    TeAP_e_HMIPopUp_TEMP_NA_FULLSCREEN = 51,
    TeAP_e_HMIPopUp_CRUISE_CONTROL_ENGAGED_FULLSCREEN = 52,
    TeAP_e_HMIPopUp_BUTTON_PRESS_FULLSCREEN = 53,
    TeAP_e_HMIPopUp_DOOR_OPEN_OVERLAY = 54,
    TeAP_e_HMIPopUp_LIFTGATE_OPEN_OVERLAY = 55,
    TeAP_e_HMIPopUp_ESC_ACTIVE_OVERLAY = 56,
    TeAP_e_HMIPopUp_BUTTON_PRESS_TAKECONTROL = 57,
    TeAP_e_HMIPopUp_LO4_ACTIVE_OVERLAY = 58,
    TeAP_e_HMIPopUp_TRAILER_CONNECTED_OVERLAY = 59,
    TeAP_e_HMIPopUp_SERVICE_REQUIRED_OVERLAY = 60,
    TeAP_e_HMIPopUp_FRONT_WIPE_OVERLAY = 61,
    TeAP_e_HMIPopUp_REAR_WIPE_OVERLAY = 62,
    TeAP_e_HMIPopUp_TEMP_NA_OVERLAY = 63,
    TeAP_e_HMIPopUp_SPEED_TOO_HIGH_REAR = 64,
    TeAP_e_HMIPopUp_SPEED_TOO_HIGH_FRONT = 65,
    TeAP_e_HMIPopUp_UNAVAIL_SPEED_TOO_HIGH_OVERLAY = 66,
    TeAP_e_HMIPopUp_CRUISE_CONTROL_ENGAGED_TAKECONTROL = 67,
    TeAP_e_HMIPopUp_DOOR_OPEN_TAKECONTROL = 68,
    TeAP_e_HMIPopUp_LIFTGATE_OPEN_TAKECONTROL = 69,
    TeAP_e_HMIPopUp_ESC_ACTIVE_TAKECONTROL = 70,
    TeAP_e_HMIPopUp_SPEED_TOO_HIGH_TAKECONTROL = 71,
    TeAP_e_HMIPopUp_LO4_ACTIVE_TAKECONTROL = 72,
    TeAP_e_HMIPopUp_TRAILER_CONNECTED_TAKECONTROL = 73,
    TeAP_e_HMIPopUp_SERVICE_REQUIRED_TAKECONTROL = 74,
    TeAP_e_HMIPopUp_FRONT_WIPE_TAKECONTROL = 75,
    TeAP_e_HMIPopUp_REAR_WIPE_TAKECONTROL = 76,
    TeAP_e_HMIPopUp_TEMP_NA_TAKECONTROL = 77,
    TeAP_e_HMIPopUp_WHEEL_TOUCHED_TAKECONTROL = 78,
    TeAP_e_HMIPopUp_DRIVER_OVERRIDE_TAKECONTROL = 79,
    TeAP_e_HMIPopUp_MANUAL_PARK_TAKECONTROL = 80,
    TeAP_e_HMIPopUp_SEMI_PARALLEL_REMOVE_HANDS_LEFT = 81,
    TeAP_e_HMIPopUp_SEMI_PARALLEL_REMOVE_HANDS_RIGHT = 82,
    TeAP_e_HMIPopUp_MAX = MAX_int32_T
} TeAP_e_HMIPopUp;


#endif                     /* RTW_HEADER_TeAP_e_HMIPopUp_h_ */
/* 
 * File trailer for generated code. 
 *  
 * [EOF] 
 */

