/*
 * $QNXLicenseC:
 * Copyright 2019, QNX Software Systems. All Rights Reserved.
 *
 * You must obtain a written license from and pay applicable
 * license fees to QNX Software Systems before you may reproduce,
 * modify or distribute this software, or any work that includes
 * all or part of this software. Free development licenses are
 * available for evaluation and non-commercial purposes. For more
 * information visit http://licensing.qnx.com or email
 * licensing@qnx.com.
 *
 * This file may contain contributions from others. Please review
 * this entire file for other proprietary rights or license notices,
 * as well as the QNX Development Suite License Guide at
 * http://licensing.qnx.com/license-guide/ for other information.
 * $
 */

/**
 * @file serdes_api.h
 *
 * @brief The definitions and functions to use the camera serializer/
 *        deserializer (serdes) library.
 *
 * @details The APIs defined in this file describe the interface for the
 *          serdes library.  This library is used by the Sensor service to
 *          support cameras that are access through a deserializer/serializer
 *          pair.  Different serdes libraries are created to implement the
 *          necessary driver to support different models of deserializers and
 *          serializers.  Each library must implement an instance of the
 *          @c camera_serdes_t structure that is dynamically loaded by the
 *          Sensor service to make use of the serdes driver.
 */

#ifndef __SERDES_API_H__
#define __SERDES_API_H__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>

/**
 * @brief A value representing a handle used to identify an open instance of
 *        a serdes context.
 */
typedef int32_t serdes_handle_t;

/**
 * @brief Format of the data received from the camera through the serializer.
 */
typedef enum {
    SERDES_FORMAT_RGB888 = 0,
    SERDES_FORMAT_RGB565,
    SERDES_FORMAT_RGB666,
    SERDES_FORMAT_YUV422_8BIT,
    SERDES_FORMAT_YUV422_10BIT,
    SERDES_FORMAT_YUV422_12BIT,
    SERDES_FORMAT_RAW8,
    SERDES_FORMAT_RAW16,
    SERDES_FORMAT_RAW10,
    SERDES_FORMAT_RAW20,
    SERDES_FORMAT_RAW11,
    SERDES_FORMAT_RAW12,
    SERDES_FORMAT_RAW14,
    SERDES_FORMAT_24BIT,
    SERDES_FORMAT_8BIT
} serdes_format_t;

/**
 * @brief Type of frame synchronization to perform on the deserializer.
 *
 * @details A serdes library can extend the definitions below by providing
 *          extra enum entries that can be ORed with the definitions above.
 *          This permits a serdes to specify different variants of internal
 *          and external frame synchronization.
 */
typedef enum {
    /**
     * No frame synchronization.
     */
    SERDES_FSYNC_NONE = 0,
    /**
     * A frame synchronization method that is internal to the deserializer;
     * this is usually a method generated by the deserializer.
     */
    SERDES_FSYNC_INTERNAL = 1,
    /**
     * A frame synchronization method that is external to the deserializer;
     * typically this is a specific external pin.
     */
    SERDES_FSYNC_EXTERNAL = 2,
} serdes_fsync_t;

/**
 * @brief The CSI2 virtual channel to use for deserializer output.
 */
typedef enum {
    /**
     * A CSI2 virtual channel of 1.
     */
    SERDES_VIRTUAL_CHANNEL_1 = 0,
    /**
     * A CSI2 virtual channel of 2.
     */
    SERDES_VIRTUAL_CHANNEL_2,
    /**
     * A CSI2 virtual channel of 3.
     */
    SERDES_VIRTUAL_CHANNEL_3,
    /**
     * A CSI2 virtual channel of 4.
     */
    SERDES_VIRTUAL_CHANNEL_4,
    /**
     * A seperate virtual channel is used for each serializer link; i.e.
     * serializer link 1 uses VC of 1, serializer link 2 uses VC of 2...
     */
    SERDES_VIRTUAL_CHANNEL_PER_LINK,
    /**
     * Keep the CSI2 virtual channel that are generated by the serializer
     * intact.
     */
    SERDES_VIRTUAL_CHANNEL_UNCHANGED
} serdes_virtual_channel_t;

/**
 * @brief The different serializer links connected to the deserializer.
 */
typedef enum {
    /**
     * No specific serializer link selected.
     */
    SERDES_LINK_NONE = 0,
    /**
     * The first serializer link.
     */
    SERDES_LINK_1,
    /**
     * The second serializer link.
     */
    SERDES_LINK_2,
    /**
     * The third serializer link.
     */
    SERDES_LINK_3,
    /**
     * The fourth serializer link.
     */
    SERDES_LINK_4
} serdes_link_t;

/**
 * @brief The different configurable mode of a GPIO pin.
 */
typedef enum {
    /**
     * The GPIO pin is disabled.
     */
    SERDES_GPIO_DISABLED = 0,
    /**
     * The GPIO pin is configured as an output pin.
     */
    SERDES_GPIO_OUTPUT,
    /**
     * The GPIO pin is configured as an input pin.
     */
    SERDES_GPIO_INPUT
} serdes_gpio_mode_t;

/**
 * @brief The unit being addressed for an enable/disable operation.
 */
typedef enum {
    /**
     * No unit - operation will do nothing.
     */
    SERDES_UNIT_NONE = 0,
    /**
     * Enable/disable all serializers.
     */
    SERDES_UNIT_SERIALIZERS = 1,
    /**
     * Enable/disable the deserializer.
     */
    SERDES_UNIT_DESERIALIZER = 2,
    /**
     * Enable/disable all serializers and the deserializer.
     */
    SERDES_UNIT_SERDES = 3
} serdes_unit_t;

/**
 * @brief This enumerated type specifies the deserializer properties list.
 *
 * @details These properties are used as keys for the following function:
 *          - @c serdes_set_deser_property()
 *          - @c serdes_get_deser_property()
 *
 *          Each key is associated with a value of the indicated type.
 */
typedef enum {
    /**
     * End-of-list identifier.
     */
    DESER_PROP_END = -1,
    /**
     * The serializer format as a @c ::serdes_format_t value.
     */
    DESER_PROP_FORMAT,
    /**
     * The path to the I2c driver to be used to access the deserializer as a
     * @c char* value.
     */
    DESER_PROP_I2C_PATH,
    /**
     * The I2C address of the deserializer as a @c uint8_t value.
     */
    DESER_PROP_I2C_ADDR,
    /**
     * The desired speed of the I2C bus in Hz as a @c uint32_t value.
     */
    DESER_PROP_I2C_SPEED,
    /**
     * The desired number of CSI2 lanes for the CSI2 output as a @c uint8_t
     * value.
     */
    DESER_PROP_CSI2_NUM_LANES,
    /**
     * The desired CSI2 Virtual Channel (VC) for the CSI2 output as a
     * @c serdes_virtual_channel_t value.
     */
    DESER_PROP_CSI2_VIRTUAL_CHANNEL,
    /**
     * The desired frame synchronization as a @c uint32_t value where this is
     * made of flags from @c serdes_fsync_t and serdes library specific
     * extensions.
     */
    DESER_PROP_FSYNC,
    /**
     * For manual frame synchronization, this sets the frame synchronization
     * periods in clock cycles as a @c uint32_t value.
     */
    DESER_PROP_FSYNC_MANUAL_PERIOD,
    /**
     * Set of deserializer specific flags as a @c uint32_t value.  The meaning
     * of each bits of these flags are defined in the specific serdes library.
     */
    DESER_PROP_FLAGS,
    /**
     * Vendor specific properties supported by a specific serdes library start
     * from here.
     */
    DESER_PROP_VENDOR_SPECIFIC = 0x1000
} serdes_deserializer_property_t;

/**
 * @brief This enumerated type specifies the serializer properties list.
 *
 * @details These properties are used as keys for the following function:
 *          - @c serdes_set_ser_property()
 *          - @c serdes_get_set_property()
 *
 *          Each key is associated with a value of the indicated type.
 */
typedef enum {
    /**
     * End-of-list identifier.
     */
    SER_PROP_END = -1,
    /**
     * Indicate if this serializer is used in this configuration as a
     * @c bool value.
     */
    SER_PROP_ACTIVE,
    /**
     * The native I2C address of the serializer as a @c uint8_t value.
     */
    SER_PROP_I2C_ADDR,
    /**
     * The alias I2C address to use for the serializer as a @c uint8_t value.
     */
    SER_PROP_I2C_ALIAS,
    /**
     * The native I2C address of the sensor as a @c uint8_t value.
     */
    SER_PROP_SENSOR_I2C_ADDR,
    /**
     * The alias I2C address to use for the sensor as a @c uint8_t value.
     */
    SER_PROP_SENSOR_I2C_ALIAS,
    /**
     * The desired speed of the remote I2C bus in Hz as a @c uint32_t value.
     */
    SER_PROP_I2C_SPEED,
    /**
     * Set of serializer specific flags as a @c uint32_t value.  The meaning
     * of each bits of these flags are defined in the specific serdes library.
     */
    SER_PROP_FLAGS,
    /**
     * Vendor specific properties supported by a specific serdes library start
     * from here.
     */
    SER_PROP_VENDOR_SPECIFIC = 0x1000
} serdes_serializer_property_t;

/**
 * @brief Request a handle to access an instance of serdes
 * @details If the specified deserializer, serializer and number of links are
 *          supported by the library, an handle is returned that is needed to
 *          make use of other functions in this library.
 *
 * @param deserializer_id The identifier for the deserializer model as defined
 *                        in a library-specific enum.
 * @param serializer_id The identifier for the serializer model as defined in
 *                      a library-specific enum.
 * @param num_links The number of serializer links to enable.
 * @param handle (output) On success, set to the handle; NULL on failure.
 *
 * @return @c #CAMERA_EOK when the function successfully completes, otherwise
 *         another @c ::camera_error_t value that provides the reason that the
 *         call failed.
 */
typedef int (*serdes_open_func_t)(uint32_t deserializer_id,
                                  uint32_t serializer_id,
                                  uint32_t num_links,
                                  serdes_handle_t* handle);

/**
 * @brief Stop using the serdes handle
 *
 * @details Any internal resources associated with a previously
 *          opened serdes are freed.
 *
 * @param handle The handle that's returned from calling the
 *               function @c serdes_open_func_t.
 */
typedef int (*serdes_close_func_t)(serdes_handle_t handle);

/**
 * @brief Configure one or more settings of the deserializer before
 *        initialization.
 *
 * @details For the @c args argument, you can provide one or more
 *          property-value pairs using @c ::serdes_deserializer_property_t
 *          values as the name of the property and the correct type for the
 *          value such as an @c int or @c double value.
 *
 *           @note There is no type-checking performed by the compiler,
 *                 therefore, you must ensure that the value you provide
 *                 for each property-value pair matches the expected data
 *                 type. Data type mismatches can result in undefined
 *                 behavior and may cause your application to crash.
 *
 *           After calling @c serdes_open(), serdes properties are set to
 *           default values by the library.  You can use this function to
 *           modify these properties before @c serdes_init() is called.  After
 *           having called @c serdes_init(), all properties have been applied
 *           to the serdes and it is not possible to change these properties
 *           anymore by calling this function unless otherwise specified.  You
 *           should make use of the @c serdes_set_deser_property() macro below
 *           that automatically inserts @c DESER_PROP_END to the end of your
 *           property-value pairs.  It takes as first parameter a
 *           @c camera_serdes_t*.
 *           You can specify multiple property-value pairs by delimiting them
 *           with a comma as follows:
 * @code
 * serdes_set_deser_property(serdes, handle,
 *                           DESER_PROP_FORMAT, SERDES_FORMAT_YUV422_8BIT,
 *                           DESER_PROP_I2C_PATH, "/dev/i2c0",
 *                           DESER_PROP_I2C_ADDR, 0x20);
 * @endcode
 *
 * @param handle The handle returned by a call to the @c serdes_open() function.
 * @param args... A series of comma-delimited property-value pairs.
 * @return @c #CAMERA_EOK when the function successfully completes, otherwise
 *         another @c ::camera_error_t value that provides the reason that the
 *         call failed.
 */
typedef int (*serdes_set_deser_property_func_t)(serdes_handle_t handle,
                                                ...);
#define serdes_set_deser_property(serdes, handle, args...) \
    serdes->set_deser_property(handle, args, DESER_PROP_END)

/**
 * @brief Retrieve one or more properties of the deserializer.
 *
 * @details For the @c args argument, you can provide one or more
 *          property-value pairs using @c ::serdes_deserializer_property_t
 *          values as the name of the property and the correct type for the
 *          value such as an @c int* or @c double* value.
 *
 *           @note There is no type-checking performed by the compiler,
 *                 therefore, you must ensure that the value you provide
 *                 for each property-value pair matches the expected data
 *                 type. Data type mismatches can result in undefined
 *                 behavior and may cause your application to crash.
 *
 *           You should make use of the @c serdes_get_deser_property() macro
 *           below that automatically inserts @c DESER_PROP_END to the end of
 *           your property-value pairs.  It takes as first parameter a
 *           @c camera_serdes_t*.
 *           You can specify multiple property-value pairs by delimiting them
 *           with a comma as follows:
 * @code
 * serdes_get_deser_property(serdes, handle,
 *                           DESER_PROP_FORMAT, &format,
 *                           DESER_PROP_I2C_ADDR, &i2c_addr);
 * @endcode
 *
 * @param handle The handle returned by a call to the @c serdes_open() function.
 * @param args... A series of comma-delimited property-value pairs.
 * @return @c #CAMERA_EOK when the function successfully completes, otherwise
 *         another @c ::camera_error_t value that provides the reason that the
 *         call failed.
 */
typedef int (*serdes_get_deser_property_func_t)(serdes_handle_t handle,
                                                ...);
#define serdes_get_deser_property(serdes, handle, args...) \
    serdes->get_deser_property(handle, args, DESER_PROP_END)

/**
 * @brief Configure one or more settings of the serializer before
 *        initialization.
 *
 * @details For the @c args argument, you can provide one or more
 *          property-value pairs using @c ::serdes_serializer_property_t values
 *          as the name of the property and the correct type for the value such
 *          as an @c int or @c double value.
 *
 *           @note There is no type-checking performed by the compiler,
 *                 therefore, you must ensure that the value you provide
 *                 for each property-value pair matches the expected data
 *                 type. Data type mismatches can result in undefined
 *                 behavior and may cause your application to crash.
 *
 *           After calling @c serdes_open(), serdes properties are set to
 *           default values by the library.  You can use this function to
 *           modify these properties before @c serdes_init() is called.  After
 *           having called @c serdes_init(), all properties have been applied
 *           to the serdes and it is not possible to change these properties
 *           anymore by calling this function.
 *
 *           You should make use of the @c serdes_set_ser_property() macro
 *           below that automatically inserts @c SER_PROP_END to the end of
 *           your property-value pairs.  It takes as first parameter a
 *           @c camera_serdes_t*.  You can specify multiple property-value
 *           pairs by delimiting them with a comma as follows:
 * @code
 * serdes_set_ser_property(serdes, handle, SERDES_LINK_1,
 *                         SER_PROP_ACTIVE, true,
 *                         SER_PROP_I2C_ADDR, 0x30,
 *                         SER_PROP_I2C_ALIAS, 0x31);
 * @endcode
 *
 * @param handle The handle returned by a call to the @c serdes_open() function.
 * @param link To which link of the deserializer is this serializer connected.
 * @param args... A series of comma-delimited property-value pairs.
 * @return @c #CAMERA_EOK when the function successfully completes, otherwise
 *         another @c ::camera_error_t value that provides the reason that the
 *         call failed.
 */
typedef int (*serdes_set_ser_property_funct_t)(serdes_handle_t handle,
                                               serdes_link_t link,
                                               ...);
#define serdes_set_ser_property(serdes, handle, link, args...) \
    serdes->set_ser_property(handle, link, args, SER_PROP_END)

/**
 * @brief Retrieve one or more properties of the serializer.
 *
 * @details For the @c args argument, you can provide one or more
 *          property-value pairs using @c ::serdes_serializer_property_t
 *          values as the name of the property and the correct type for the
 *          value such as an @c int* or @c double* value.
 *
 *           @note There is no type-checking performed by the compiler,
 *                 therefore, you must ensure that the value you provide
 *                 for each property-value pair matches the expected data
 *                 type. Data type mismatches can result in undefined
 *                 behavior and may cause your application to crash.
 *
 *           You should make use of the @c serdes_set_ser_property() macro
 *           below that automatically inserts @c SER_PROP_END to the end of
 *           your property-value pairs.  It takes as first parameter a
 *           @c camera_serdes_t*.  You can specify multiple property-value
 *           pairs by delimiting them with a comma as follows:
 * @code
 * serdes_get_ser_property(serdes, handle, SERDES_LINK_1,
 *                         SER_PROP_I2C_ADDR, &i2c_addr,
 *                         SER_PROP_I2C_ALIAS, &i2c_alias);
 * @endcode
 *
 * @param handle The handle returned by a call to the @c serdes_open() function.
 * @param args... A series of comma-delimited property-value pairs.
 * @return @c #CAMERA_EOK when the function successfully completes, otherwise
 *         another @c ::camera_error_t value that provides the reason that the
 *         call failed.
 */
typedef int (*serdes_get_ser_property_func_t)(serdes_handle_t handle,
                                              serdes_link_t link,
                                              ...);
#define serdes_get_ser_property(serdes, handle, link, args...) \
    serdes->get_ser_property(handle, link, args, SER_PROP_END)

/**
 * @brief Initialize the deserializer and serializers
 * @details Perform all initialization of the deserializer and serializers
 *          to prepare them to receive data from the camera.
 *
 * @param handle The handle that's returned from calling the function
 *               @c serdes_open_func_t.
 * @return @c #CAMERA_EOK when the function successfully completes, otherwise
 *         another @c ::camera_error_t value that provides the reason that the
 *         call failed.
 */
typedef int (*serdes_init_func_t)(serdes_handle_t handle);

/**
 * @brief Enable streaming from the deserializer and/or serializers.
 * @details After initialization is completed using @c serdes_init_func_t, you
 *          need to call this function to enable transmission of data from
 *          serializers and deserializer.
 *
 * @param handle The handle that's returned from calling the function
 *               @c serdes_open_func_t.
 * @param unit What unit to enable.
 * @return @c #CAMERA_EOK when the function successfully completes, otherwise
 *         another @c ::camera_error_t value that provides the reason that the
 *         call failed.
 */
typedef int (*serdes_enable_func_t)(serdes_handle_t handle, serdes_unit_t unit);

/**
 * @brief Disable streaming from the deserializer and/or serializers
 * @details After CSI2 data streaming is enabled using @c serdes_enable_func_t,
 *          call this function to disable this streaming when it is no longer
 *          required.
 *
 * @param handle The handle that's returned from calling the function
 *               @c serdes_open_func_t.
 * @param unit What unit to disable.
 * @return @c #CAMERA_EOK when the function successfully completes, otherwise
 *         another @c ::camera_error_t value that provides the reason that the
 *         call failed.
 */
typedef int (*serdes_disable_func_t)(serdes_handle_t handle, serdes_unit_t unit);

/**
 * @brief Configure the desired GPIO mode for a given GPIO pin
 * @details Some GPIO pins have configurable mode of operations and must be
 *          programmed to the appropriate mode before use.
 *
 * @param handle The handle that's returned from calling the function
 *               @c serdes_open_func_t.
 * @param link Configure GPIO for which link; use @c SERDES_LINK_NONE for
 *             configuring a GPIO pin on the deserializer.
 * @param pin What GPIO pin to program; supported values here depend on the
 *            specific serdes library being used.
 * @param mode The desired mode of operation for the pin.
 * @return @c #CAMERA_EOK when the function successfully completes, otherwise
 *         another @c ::camera_error_t value that provides the reason that the
 *         call failed.
 */
typedef int (*serdes_configure_gpio_func_t)(serdes_handle_t handle,
                                            serdes_link_t link,
                                            uint8_t pin,
                                            serdes_gpio_mode_t mode);

/**
 * @brief Set what value to output on a given GPIO output pin
 * @details The GPIO output can be either set as a global value sent by the
 *          deserializer to all links or as a specific value given for a
 *          particular serializer link.
 *
 * @param handle The handle that's returned from calling the function
 *               @c serdes_open_func_t.
 * @param link Set GPIO output for which link; use @c SERDES_LINK_NONE for
 *             setting a value on the deserializer that applies to all links.
 * @param pin What GPIO pin to program; supported values here depend on the
 *            specific serdes library being used.
 * @param value What value to output on the GPIO; supported values are defined
 *              in the specific serdes library.
 * @return @c #CAMERA_EOK when the function successfully completes, otherwise
 *         another @c ::camera_error_t value that provides the reason that the
 *         call failed.
 */
typedef int (*serdes_set_gpio_func_t)(serdes_handle_t handle,
                                      serdes_link_t link,
                                      uint8_t pin,
                                      uint8_t value);

/**
 * @brief Parses a name/value pair from the config file
 * @details This function is called for each attribute associated
 *          with the deserializer or one of the serializers in the
 *          configuration file.
 *
 * @param handle The handle that's returned from calling the function
 *               @c serdes_open_func_t.
 * @param link Config attributed for which link; use @c SERDES_LINK_NONE for
 *             setting a value on the deserializer that applies to all links.
 * @param name  The name of the attribute.
 * @param value The value of the attribute.
 * @return @c #CAMERA_EOK when the function successfully completes, otherwise
 *         another @c ::camera_error_t value that provides the reason that the
 *         call failed.
 */
typedef int (*serdes_parse_config_func_t)(serdes_handle_t handle,
                                          serdes_link_t link,
                                          char* name,
                                          char* value);

/**
 * @brief Functions that must be implemented by a serdes library
 * @details The serdes library must define an instance of this structure named
 *          @c serdes_defs that the Sensor service will use to interface with
 *          the serdes driver.
*/
typedef struct {
    /**
     * A function pointer. For more information, see @c serdes_open_func_t().
     */
    serdes_open_func_t                          open;
    /**
     * A function pointer. For more information, see @c serdes_close_func_t().
     */
    serdes_close_func_t                         close;
    /**
     * A function pointer. For more information, see
     * @c serdes_set_deser_property_func_t().
     */
    serdes_set_deser_property_func_t            set_deser_property;
    /**
     * A function pointer. For more information, see
     * @c serdes_get_deser_property_func_t().
     */
    serdes_get_deser_property_func_t            get_deser_property;
    /**
     * A function pointer. For more information, see
     * @c serdes_set_deser_property_func_t().
     */
    serdes_set_ser_property_funct_t             set_ser_property;
    /**
     * A function pointer. For more information, see
     * @c serdes_get_deser_property_func_t().
     */
    serdes_get_ser_property_func_t              get_ser_property;
    /**
     * A function pointer. For more information, see @c serdes_init_func_t().
     */
    serdes_init_func_t                          init;
    /**
     * A function pointer. For more information, see @c serdes_enable_func_t().
     */
    serdes_enable_func_t                        enable;
    /**
     * A function pointer. For more information, see
     * @c serdes_disable_func_t().
     */
    serdes_disable_func_t                       disable;
    /**
     * A function pointer. For more information, see
     * @c serdes_configure_gpio_func_t().
     */
    serdes_configure_gpio_func_t                configure_gpio;
    /**
     * A function pointer. For more information, see
     * @c serdes_set_gpio_func_t().
     */
    serdes_set_gpio_func_t                      set_gpio;
    /**
     * A function pointer. For more information, see
     * @c serdes_parse_config_func_t().
     */
    serdes_parse_config_func_t                  parse_config;
} camera_serdes_t;

#ifdef __cplusplus
}
#endif
#endif   /* __SERDES_API_H__ */

#if defined(__QNXNTO__) && defined(__USESRCVERSION)
#include <sys/srcversion.h>
__SRCVERSION("$URL$ $Rev$")
#endif
