

#if !defined(__HMI_DRV_PAR_H__)
#define __HMI_DRV_PAR_H__


/* -----------------------------------------------------------------------------
    &&&~ Signal value names
 ----------------------------------------------------------------------------- */

#define kVIN_MSG_SNA                         3
#define kVIN_MSG_VIN_HI                      2
#define kVIN_MSG_VIN_MID                     1
#define kVIN_MSG_VIN_LO                      0


#define kVC_VehCfg7_Stat_SNA                 3
#define kVC_VehCfg7_Stat_REQUEST_DATA        2
#define kVC_VehCfg7_Stat_PROGAMMED           1
#define kVC_VehCfg7_Stat_NA                  0
#define kVC_Trans_Equipped_Automatic         0
#define kVC_Trans_Equipped_Manual            1


#define kVC_VehCfg5_Stat_SNA                 3
#define kVC_VehCfg5_Stat_REQUEST_DATA        2
#define kVC_VehCfg5_Stat_PROGAMMED           1
#define kVC_VehCfg5_Stat_NA                  0


#define kVC_VehCfg3_Stat_SNA                 3
#define kVC_VehCfg3_Stat_REQUEST_DATA        2
#define kVC_VehCfg3_Stat_PROGAMMED           1
#define kVC_VehCfg3_Stat_NA                  0
#define kVC_TcaseTyp_NOT_PRSNT               0
#define kVC_TcaseTyp_TCASE_143_144           1
#define kVC_TcaseTyp_BW4445_46_48_WS         2
#define kVC_TcaseTyp_Tcase_253_1522          3
#define kVC_TcaseTyp_Tcase_BW4444            4
#define kVC_TcaseTyp_Tcase_BW4446            5
#define kVC_TcaseTyp_Tcase_MPT3025C          6
#define kVC_TcaseTyp_Tcase_241_MPT1222C      7
#define kVC_TcaseTyp_BW4447_WOS              8
#define kVC_TcaseTyp_Tcase_243               9
#define kVC_TcaseTyp_BW4447_49_WS            10
#define kVC_TcaseTyp_Tcase_273               11
#define kVC_TcaseTyp_Tcase_MAS_ATC           12
#define kVC_TcaseTyp_Tcase_BW4440            13
#define kVC_TcaseTyp_Tcase_156               14
#define kVC_TcaseTyp_Tcase_256_3022          15
#define kVC_ChassisType_SNA                  127


#define kVC_VehCfg2_Stat_SNA                 3
#define kVC_VehCfg2_Stat_REQUEST_DATA        2
#define kVC_VehCfg2_Stat_PROGAMMED           1
#define kVC_VehCfg2_Stat_NA                  0
#define kVC_SpecialPKG_IC_NONE               0
#define kVC_SpecialPKG_IC_PKG_70JP           1
#define kVC_SpecialPKG_IC_PKG_300S           2
#define kVC_SpecialPKG_IC_PKG_BEATS          3
#define kVC_SpecialPKG_IC_PKG_SUPERBEE       4
#define kVC_SpecialPKG_IC_MOPAR              5
#define kVC_SpecialPKG_IC_Hellcat            6
#define kVC_SpecialPKG_IC_Shaker             7
#define kVC_SpecialPKG_IC_Scat               8
#define kVC_SpecialPKG_IC_ADR                9
#define kVC_SpecialPKG_IC_Scat_Drag          10
#define kVC_SpecialPKG_IC_High_Output        11
#define kVC_SpecialPKG_IC_Hellcat_HO         12
#define kVC_SpecialPKG_IC_LARAMIE            16
#define kVC_SpecialPKG_IC_BIGHORN            17
#define kVC_SpecialPKG_IC_LONGHORN           18
#define kVC_SpecialPKG_IC_LONESTAR           19
#define kVC_SpecialPKG_IC_LIMITED            20
#define kVC_SpecialPKG_IC_MOSSY_OAK          21
#define kVC_SpecialPKG_IC_ORT                22
#define kVC_SpecialPKG_IC_POWERWAGON         23
#define kVC_SpecialPKG_IC_HD_DX              24
#define kVC_SpecialPKG_IC_SPORT              25
#define kVC_SpecialPKG_IC_PWGN_Laramie       26
#define kVC_SpecialPKG_IC_RAM_1500           27
#define kVC_SpecialPKG_IC_PWGN_GOODYEAR      28
#define kVC_SpecialPKG_IC_LONGHORN_BLACK     29
#define kVC_SpecialPKG_IC_LONGHORN_BROWN     30
#define kVC_SpecialPKG_IC_RAM_2500           31
#define kVC_SpecialPKG_IC_RAM_3500           32
#define kVC_SpecialPKG_IC_RAM_4500           33
#define kVC_SpecialPKG_IC_RAM_5500           34
#define kVC_SpecialPKG_IC_RAM_TRX21          35
#define kVC_SpecialPKG_IC_VOYAGER            36
#define kVC_SpecialPKG_IC_PACIFICA           37
#define kVC_SpecialPKG_IC_GRAND_CARAVAN      38
#define kVC_SpecialPKG_IC__50th_Anniversary  39
#define kVC_SpecialPKG_IC__80th_Anniversary  40
#define kVC_SpecialPKG_IC_J9_Splash_Screen   41
#define kVC_SpecialPKG_IC_WRANGLER_SPORT     100
#define kVC_SpecialPKG_IC_WRANGLER_SAHARA    101
#define kVC_SpecialPKG_IC_WRANGLER_RUBICON   102
#define kVC_SpecialPKG_IC_JEEP_SPORT         103
#define kVC_SpecialPKG_IC_JEEP_SPORT_X       104
#define kVC_SpecialPKG_IC_JEEP_RUBICON       105
#define kVC_SpecialPKG_IC_JEEP_PRO_FIGHTER   106
#define kVC_SpecialPKG_IC__10th_Anniversary  107
#define kVC_SpecialPKG_IC_Limited_10th_Anniversary 108
#define kVC_SpecialPKG_IC_TRAILHAWK_SUPERCHARGED 150
#define kVC_SpecialPKG_IC_DODGE_100          246
#define kVC_SpecialPKG_IC_VARVATOS           247
#define kVC_SpecialPKG_IC_SNA                255


#define kVC_VehCfg1_Stat_SNA                 3
#define kVC_VehCfg1_Stat_REQUEST_DATA        2
#define kVC_VehCfg1_Stat_PROGAMMED           1
#define kVC_VehCfg1_Stat_NA                  0
#define kVC_MODEL_YEAR_SNA                   63
#define kVC_VEH_LINE_VEH_NONE                0
#define kVC_VEH_LINE_VEH_WK                  1
#define kVC_VEH_LINE_VEH_LX                  2
#define kVC_VEH_LINE_VEH_JC                  22
#define kVC_VEH_LINE_VEH_DS                  29
#define kVC_VEH_LINE_VEH_D2                  31
#define kVC_VEH_LINE_VEH_DD                  32
#define kVC_VEH_LINE_VEH_DP                  33
#define kVC_VEH_LINE_VEH_DJ                  34
#define kVC_VEH_LINE_VEH_WD                  35
#define kVC_VEH_LINE_VEH_DX                  39
#define kVC_VEH_LINE_VEH_LD                  41
#define kVC_VEH_LINE_VEH_M156                42
#define kVC_VEH_LINE_VEH_ZD                  43
#define kVC_VEH_LINE_VEH_LA                  44
#define kVC_VEH_LINE_VEH_RU                  45
#define kVC_VEH_LINE_VEH_M161                46
#define kVC_VEH_LINE_VEH_WS                  47
#define kVC_VEH_LINE_VEH_DF                  48
#define kVC_VEH_LINE_VEH_JL                  49
#define kVC_VEH_LINE_VEH_M157                50
#define kVC_VEH_LINE_VEH_RA                  51
#define kVC_VEH_LINE_VEH_WL                  52
#define kVC_VEH_LINE_VEH_DT                  53
#define kVC_VEH_LINE_VEH_DU                  54
#define kVC_VEH_LINE_VEH_JT                  55
#define kVC_VEH_LINE_VEH_RU_PACIFICA         56
#define kVC_VEH_LINE_VEH_PF                  80
#define kVC_VEH_LINE_VEH_KL                  81
#define kVC_VEH_LINE_VEH_UF                  82
#define kVC_VEH_LINE_VEH_UT                  83
#define kVC_VEH_LINE_VEH_M145                84
#define kVC_VEH_LINE_VEH_M145BD              85
#define kVC_VEH_LINE_VEH_K8                  86
#define kVC_VEH_LINE_VEH_FF                  87
#define kVC_VEH_LINE_FF_Abarth               88
#define kVC_VEH_LINE_VEH_M182                108
#define kVC_VEH_LINE_VEH_598                 199
#define kVC_VEH_LINE_VEH_M1                  200
#define kVC_VEH_LINE_VEH_M6                  201
#define kVC_VEH_LINE_VEH_M4                  202
#define kVC_VEH_LINE_VEH_M7                  203
#define kVC_VEH_LINE_VEH_MP                  204
#define kVC_VEH_LINE_VEH_MV                  205
#define kVC_VEH_LINE_SNA                     255
#define kVC_COUNTRY_COUNTRY_SNA              31
#define kVC_COUNTRY_ECE                      21
#define kVC_COUNTRY_S_KOR                    20
#define kVC_COUNTRY_EGYPT                    17
#define kVC_COUNTRY_CHINA                    16
#define kVC_COUNTRY_BRZ                      15
#define kVC_COUNTRY_MEX                      14
#define kVC_COUNTRY_VEN                      13
#define kVC_COUNTRY_GULF                     12
#define kVC_COUNTRY_IND                      11
#define kVC_COUNTRY_AUS                      10
#define kVC_COUNTRY_MLY                      9
#define kVC_COUNTRY_SWISS                    8
#define kVC_COUNTRY_GER                      7
#define kVC_COUNTRY_JPN                      6
#define kVC_COUNTRY_GB                       5
#define kVC_COUNTRY_CND                      4
#define kVC_COUNTRY_EU                       3
#define kVC_COUNTRY_USA                      2
#define kVC_COUNTRY_ROW                      0
#define kVC_LHD_RHD_SNA                      3
#define kVC_LHD_RHD_RHD                      2
#define kVC_LHD_RHD_LHD                      1
#define kVC_LHD_RHD_NA                       0
#define kVC_BODY_STYLE_BODY_SNA              15
#define kVC_BODY_STYLE_BODY_4DMP             8
#define kVC_BODY_STYLE_BODY_4DP              7
#define kVC_BODY_STYLE_BODY_2DP              6
#define kVC_BODY_STYLE_BODY_4DH              5
#define kVC_BODY_STYLE_BODY_WAGON            4
#define kVC_BODY_STYLE_BODY_CONV             3
#define kVC_BODY_STYLE_BODY_2DS              2
#define kVC_BODY_STYLE_BODY_4DS              1
#define kVC_BODY_STYLE_BODY_NONE             0
#define kVC_SpecialPKG_SNA                   255
#define kVC_SpecialPKG_NONE                  0


#define kDisplayView3_OFF                    0
#define kDisplayView3_VIEW_1                 1
#define kDisplayView3_VIEW_2                 2
#define kDisplayView3_VIEW_3                 3
#define kDisplayView3_VIEW_4                 4
#define kDisplayView3_VIEW_5                 5
#define kDisplayView3_VIEW_6                 6
#define kDisplayView3_VIEW_7                 7
#define kDisplayView3_VIEW_8                 8
#define kDisplayView3_VIEW_9                 9
#define kDisplayView3_VIEW_10                10
#define kDisplayView3_VIEW_11                11
#define kDisplayView3_VIEW_12                12
#define kDisplayView3_VIEW_13                13
#define kDisplayView3_VIEW_14                14
#define kDisplayView3_VIEW_15                15
#define kDisplayView3_VIEW_16                16
#define kDisplayView3_VIEW_17                17
#define kDisplayView3_VIEW_18                18
#define kDisplayView3_VIEW_19                19
#define kDisplayView3_VIEW_20                20
#define kDisplayView3_VIEW_21                21
#define kDisplayView3_VIEW_22                22
#define kDisplayView3_VIEW_23                23
#define kDisplayView3_VIEW_24                24
#define kDisplayView3_VIEW_25                25
#define kDisplayView3_VIEW_26                26
#define kDisplayView3_VIEW_27                27
#define kDisplayView3_VIEW_28                28
#define kDisplayView3_VIEW_29                29
#define kDisplayView3_VIEW_30                30
#define kDisplayView3_VIEW_31                31
#define kDisplayView3_VIEW_32                32
#define kDisplayView3_VIEW_33                33
#define kDisplayView3_VIEW_34                34
#define kDisplayView3_VIEW_35                35
#define kDisplayView3_VIEW_36                36
#define kDisplayView3_VIEW_37                37
#define kDisplayView3_VIEW_38                38
#define kDisplayView3_VIEW_39                39
#define kDisplayView3_VIEW_40                40
#define kDisplayView3_VIEW_41                41
#define kDisplayView3_VIEW_42                42
#define kDisplayView3_VIEW_43                43
#define kDisplayView3_VIEW_44                44
#define kDisplayView3_VIEW_45                45
#define kDisplayView3_VIEW_46                46
#define kDisplayView3_VIEW_47                47
#define kDisplayView3_VIEW_48                48
#define kDisplayView3_VIEW_49                49
#define kDisplayView3_VIEW_50                50
#define kDisplayView3_VIEW_51                51
#define kDisplayView3_VIEW_52                52
#define kDisplayView3_VIEW_53                53
#define kDisplayView3_VIEW_54                54
#define kDisplayView3_VIEW_55                55
#define kDisplayView3_VIEW_56                56
#define kDisplayView3_VIEW_57                57
#define kDisplayView3_VIEW_58                58
#define kDisplayView3_VIEW_59                59
#define kDisplayView3_VIEW_60                60
#define kDisplayView3_VIEW_61                61
#define kDisplayView3_VIEW_62                62
#define kDisplayView3_VIEW_63                63


#define kNET_CFG_STAT_PT_SNA                 3
#define kNET_CFG_STAT_PT_REQUEST_DATA        2
#define kNET_CFG_STAT_PT_PROGAMMED           1
#define kNET_CFG_STAT_PT_NA                  0


#define kNET_CFG_STAT_INT_SNA                3
#define kNET_CFG_STAT_INT_REQUEST_DATA       2
#define kNET_CFG_STAT_INT_PROGAMMED          1
#define kNET_CFG_STAT_INT_NA                 0


#define kPTS_AlrFL_SNA                       15
#define kPTS_AlrFL_ARC8                      8
#define kPTS_AlrFL_ARC7                      7
#define kPTS_AlrFL_ARC6                      6
#define kPTS_AlrFL_ARC5                      5
#define kPTS_AlrFL_ARC4                      4
#define kPTS_AlrFL_ARC3                      3
#define kPTS_AlrFL_ARC2                      2
#define kPTS_AlrFL_ARC1                      1
#define kPTS_AlrFL_PTS_ALR_NOD               0
#define kPTS_AlrFR_SNA                       15
#define kPTS_AlrFR_ARC8                      8
#define kPTS_AlrFR_ARC7                      7
#define kPTS_AlrFR_ARC6                      6
#define kPTS_AlrFR_ARC5                      5
#define kPTS_AlrFR_ARC4                      4
#define kPTS_AlrFR_ARC3                      3
#define kPTS_AlrFR_ARC2                      2
#define kPTS_AlrFR_ARC1                      1
#define kPTS_AlrFR_PTS_ALR_NOD               0
#define kPTS_AlrRL_SNA                       15
#define kPTS_AlrRL_ARC8                      8
#define kPTS_AlrRL_ARC7                      7
#define kPTS_AlrRL_ARC6                      6
#define kPTS_AlrRL_ARC5                      5
#define kPTS_AlrRL_ARC4                      4
#define kPTS_AlrRL_ARC3                      3
#define kPTS_AlrRL_ARC2                      2
#define kPTS_AlrRL_ARC1                      1
#define kPTS_AlrRL_PTS_ALR_NOD               0
#define kPTS_AlrRR_SNA                       15
#define kPTS_AlrRR_ARC8                      8
#define kPTS_AlrRR_ARC7                      7
#define kPTS_AlrRR_ARC6                      6
#define kPTS_AlrRR_ARC5                      5
#define kPTS_AlrRR_ARC4                      4
#define kPTS_AlrRR_ARC3                      3
#define kPTS_AlrRR_ARC2                      2
#define kPTS_AlrRR_ARC1                      1
#define kPTS_AlrRR_PTS_ALR_NOD               0
#define kPTS_AlrFC_PTS_ALR_NOD               0
#define kPTS_AlrFC_ARC1                      1
#define kPTS_AlrFC_ARC2                      2
#define kPTS_AlrFC_ARC3                      3
#define kPTS_AlrFC_ARC4                      4
#define kPTS_AlrFC_ARC5                      5
#define kPTS_AlrFC_ARC6                      6
#define kPTS_AlrFC_ARC7                      7
#define kPTS_AlrFC_ARC8                      8
#define kPTS_AlrFC_SNA                       15
#define kPTS_AlrRC_PTS_ALR_NOD               0
#define kPTS_AlrRC_ARC1                      1
#define kPTS_AlrRC_ARC2                      2
#define kPTS_AlrRC_ARC3                      3
#define kPTS_AlrRC_ARC4                      4
#define kPTS_AlrRC_ARC5                      5
#define kPTS_AlrRC_ARC6                      6
#define kPTS_AlrRC_ARC7                      7
#define kPTS_AlrRC_ARC8                      8
#define kPTS_AlrRC_SNA                       15


#define kODO_SNA                             16777215


#define kVEH_SPEED_SNA                       65535


#define kLRW_SNA                             16383
#define kLRWS_ST_ERR_INI                     3
#define kLRWS_ST_ERR                         2
#define kLRWS_ST_INI                         1
#define kLRWS_ST_OK                          0


#define kPRND_STAT_SNA                       15
#define kPRND_STAT_Sport                     9
#define kPRND_STAT_Minus                     8
#define kPRND_STAT_PLUS                      7
#define kPRND_STAT_AutoStick                 6
#define kPRND_STAT_NOT_R                     5
#define kPRND_STAT_LVR_D                     4
#define kPRND_STAT_LVR_N                     3
#define kPRND_STAT_LVR_R                     2
#define kPRND_STAT_LVR_P                     1
#define kPRND_STAT_LVR_NA                    0

#define kLANG_C_LANG_NO_CHG                  31
#define kLANG_C_POLISH                       17
#define kLANG_C_TURKISH                      16
#define kLANG_C_HINDI                        15
#define kLANG_C_MANDARIN_T                   14
#define kLANG_C_BRAZILIAN                    13
#define kLANG_C_ARABIC                       12
#define kLANG_C_KOREAN                       11
#define kLANG_C_RUSSIAN                      10
#define kLANG_C_MANDARIN_S                   9
#define kLANG_C_UK_ENGLISH                   8
#define kLANG_C_DUTCH                        7
#define kLANG_C_PORTUGESE                    6
#define kLANG_C_JAPANESE                     5
#define kLANG_C_SPANISH                      4
#define kLANG_C_ITALIAN                      3
#define kLANG_C_FRENCH                       2
#define kLANG_C_US_ENGLISH                   1
#define kLANG_C_GERMAN                       0


#define kASCM_Stat_NO_MESS                   0
#define kASCM_Stat_DUMP                      1
#define kASCM_Stat_PARK                      2
#define kASCM_Stat_AERO                      3
#define kASCM_Stat_NVL                       4
#define kASCM_Stat_OR1                       5
#define kASCM_Stat_ORL2                      6
#define kASCM_Stat_EEHNA                     7
#define kASCM_Stat_RAISE                     8
#define kASCM_Stat_LOWER                     9
#define kASCM_Stat_RL_INT                    10
#define kASCM_Stat_SRVS                      11
#define kASCM_Stat_AERO2                     12
#define kASCM_Stat_SNA                       15


#define kEC_ECUCfg5_Stat_SNA                 3
#define kEC_ECUCfg5_Stat_REQUEST_DATA        2
#define kEC_ECUCfg5_Stat_PROGAMMED           1
#define kEC_ECUCfg5_Stat_NA                  0


#define kCM_TCH_STAT_SNA                     7
#define kCM_TCH_STAT_TCH_CFG_MAX             6
#define kCM_TCH_STAT_TCH_CFG_OFFSET          5
#define kCM_TCH_STAT_TCH_CFG_RES             4
#define kCM_TCH_STAT_TCH_PS_CAN              2
#define kCM_TCH_STAT_TCH_PSD                 1
#define kCM_TCH_STAT_TCH_NOT_PSD             0


#define kCFG_FEATURE_CFG_NONE                0
#define kCFG_FEATURE_CFG_AUTO_LK             1
#define kCFG_FEATURE_CFG_AUTO_UNLK           2
#define kCFG_FEATURE_CFG_DLY_LK              3
#define kCFG_FEATURE_CFG_DRV_FST             4
#define kCFG_FEATURE_CFG_SOUND_LK            5
#define kCFG_FEATURE_CFG_HORN_DUR            6
#define kCFG_FEATURE_CFG_FLASH_LK            7
#define kCFG_FEATURE_CFG_DrAlrPrsnt          8
#define kCFG_FEATURE_CFG_PARK_ASSIST         9
#define kCFG_FEATURE_CFG_LANG                10
#define kCFG_FEATURE_CFG_US_METRIC           11
#define kCFG_FEATURE_CFG_SRV_INTV            12
#define kCFG_FEATURE_CFG_AUTO_WPR            13
#define kCFG_FEATURE_CFG_HL_DLY              14
#define kCFG_FEATURE_CFG_HL_WPR              15
#define kCFG_FEATURE_CFG_ACC_DLY             16
#define kCFG_FEATURE_CFG_REM_MEM             18
#define kCFG_FEATURE_CFG_EASY_EXIT           19
#define kCFG_FEATURE_CFG_LO_VEH              20
#define kCFG_FEATURE_CFG_TILT_IN_REV         21
#define kCFG_FEATURE_CFG_ILL_APRCH           22
#define kCFG_FEATURE_CFG_ILL_ENTRY           23
#define kCFG_FEATURE_CFG_GLBL_UP_WIN         24
#define kCFG_FEATURE_CFG_GLBL_DN_WIN         25
#define kCFG_FEATURE_CFG_DRL_ON              26
#define kCFG_FEATURE_CFG_AHB                 27
#define kCFG_FEATURE_REST_FACT_DEF           28
#define kCFG_FEATURE_CFG_CMP_CAL             29
#define kCFG_FEATURE_CFG_CMP_VAR             30
#define kCFG_FEATURE_CFG_VOICE_COMF          31
#define kCFG_FEATURE_CFG_NAV_TBYT            32
#define kCFG_FEATURE_CFG_HILL_ST             33
#define kCFG_FEATURE_CFG_AFS                 34
#define kCFG_FEATURE_CFG_BSD                 35
#define kCFG_FEATURE_CFG_PE                  36
#define kCFG_FEATURE_CFG_WAL                 37
#define kCFG_FEATURE_CFG_DSS                 38
#define kCFG_FEATURE_CFG_SOUND_RS            39
#define kCFG_FEATURE_CFG_DCS                 40
#define kCFG_FEATURE_CFG_AUTO_RELK           41
#define kCFG_FEATURE_CFG_CMS                 42
#define kCFG_FEATURE_CFG_FCW                 43
#define kCFG_FEATURE_CFG_PRE_SAFE            44
#define kCFG_FEATURE_CFG_BELT_SLAK           45
#define kCFG_FEATURE_CFG_FUEL_SAV            46
#define kCFG_FEATURE_CFG_FCW_SENS            47
#define kCFG_FEATURE_CFG_HDLP_DROP           48
#define kCFG_FEATURE_CFG_ECMM                49
#define kCFG_FEATURE_PASS_WIN_LKOUT          50
#define kCFG_FEATURE_AERO                    51
#define kCFG_FEATURE_JACK                    52
#define kCFG_FEATURE_CFG_TRLR                53
#define kCFG_FEATURE_CFG_ALIGNMENT           54
#define kCFG_FEATURE_CFG_ASCM_WMO            55
#define kCFG_FEATURE_CFG_LDW                 57
#define kCFG_FEATURE_OIL                     58
#define kCFG_FEATURE_CFG_NORMAL_DCS          59
#define kCFG_FEATURE_CFG_TRANSPORT           61
#define kCFG_FEATURE_CFG_PTO_MODE            62
#define kCFG_FEATURE_CFG_PTO_SINGLE_RPM      63
#define kCFG_FEATURE_CFG_PTO_RPM1            64
#define kCFG_FEATURE_CFG_PTO_RPM2            65
#define kCFG_FEATURE_CFG_PTO_RPM3            66
#define kCFG_FEATURE_CFG_PTO_Type            67
#define kCFG_FEATURE_CFG_PTO_Auto_Resume     68
#define kCFG_FEATURE_CFG_MAX_PTO_VEH_SPEED   69
#define kCFG_FEATURE_RVC_GRID                70
#define kCFG_FEATURE_DIMMER                  71
#define kCFG_FEATURE_RLE_LIGHT               72
#define kCFG_FEATURE_RLE_HORN                73
#define kCFG_FEATURE_CFG_TRLR_TYP            76
#define kCFG_FEATURE_CFG_TRLR_NAME           77
#define kCFG_FEATURE_CFG_PTS_FT              81
#define kCFG_FEATURE_CFG_PTS_RR              82
#define kCFG_FEATURE_CFG_PTS_FT_VOL          83
#define kCFG_FEATURE_CFG_PTS_RR_VOL          84
#define kCFG_FEATURE_CFG_PLG                 86
#define kCFG_FEATURE_CFG_AUX1                87
#define kCFG_FEATURE_CFG_AUX2                88
#define kCFG_FEATURE_CFG_AUX3                89
#define kCFG_FEATURE_CFG_AUX4                90
#define kCFG_FEATURE_CFG_AUX5                91
#define kCFG_FEATURE_CFG_LDWTRQ              93
#define kCFG_FEATURE_CFG_PTO_REM_Throttle    94
#define kCFG_FEATURE_CFG_UNIT_DEFAULT        95
#define kCFG_FEATURE_CFG_PressureUnit        96
#define kCFG_FEATURE_CFG_SpeedUnit           97
#define kCFG_FEATURE_CFG_DistanceUnit        98
#define kCFG_FEATURE_CFG_ConsumptionUnit     99
#define kCFG_FEATURE_CFG_CapacityUnit        100
#define kCFG_FEATURE_CFG_TemperatureUnit     101
#define kCFG_FEATURE_CFG_PowerUnit           102
#define kCFG_FEATURE_CFG_TorqueUnit          103
#define kCFG_FEATURE_CFG_EPS                 104
#define kCFG_FEATURE_CFG_CHMSL_LINES         105
#define kCFG_FEATURE_CFG_POLICE_PE           106
#define kCFG_FEATURE_EPB_AUTO_PRK            107
#define kCFG_FEATURE_EPB_SERVICE             108
#define kCFG_FEATURE_HOLD_N_GO               109
#define kCFG_FEATURE_PWR_FLD_MRR             110
#define kCFG_FEATURE_HANDS_FREE_LFT          111
#define kCFG_FEATURE_HANDS_FREE_SLDR         112
#define kCFG_FEATURE_SVC_GRIDLINES           113
#define kCFG_FEATURE_SVC_DELAY               114
#define kCFG_FEATURE_SLD_DR_ALRT             115
#define kCFG_FEATURE_TEEN_FCW_SENS           116
#define kCFG_FEATURE_TEEN_FCW_BRK            117
#define kCFG_FEATURE_TEEN_PRK_ASST           118
#define kCFG_FEATURE_TEEN_PRK_ASST_BRK       119
#define kCFG_FEATURE_TEEN_FT_PRK_VOL         120
#define kCFG_FEATURE_TEEN_RR_PRK_VOL         121
#define kCFG_FEATURE_TEEN_MAX_SPEED          122
#define kCFG_FEATURE_TEEN_FUEL_WRN           123
#define kCFG_FEATURE_TEEN_FUEL_POPUP         124
#define kCFG_FEATURE_TEEN_BLIND_SPOT         125
#define kCFG_FEATURE_TEEN_RAIN_WPR           126
#define kCFG_FEATURE_TEEN_AUTO_HB            127
#define kCFG_FEATURE_TEEN_LGHT_WPR           128
#define kCFG_FEATURE_TEEN_SLD_DR_ALRT        129
#define kCFG_FEATURE_TEEN_PLG_CHIME          130
#define kCFG_FEATURE_SLD_DR_CHM              131
#define kCFG_FEATURE_TEEN_SLD_DR_CHM         132
#define kCFG_FEATURE_CFG_ABSM                133
#define kCFG_FEATURE_CFG_PADDLE_SHIFT        134
#define kCFG_FEATURE_CFG_PRK_ASST_BRK        137
#define kCFG_FEATURE_CFG_LDW_ON              138
#define kCFG_FEATURE_CFG_PRK_ASST_TYPE       139
#define kCFG_FEATURE_CFG_DR_ALR              140
#define kCFG_FEATURE_CFG_RDY_DRV             141
#define kCFG_FEATURE_CFG_PANEL_INTS          142
#define kCFG_FEATURE_CFG_MOOD_LGT_INTS       143
#define kCFG_FEATURE_CFG_ML_HDLP_LVL         144
#define kCFG_FEATURE_CFG_BSM_TRLR            145
#define kCFG_FEATURE_CFG_AUTO_SS             146
#define kCFG_FEATURE_CFG_PCS                 147
#define kCFG_FEATURE_CFG_UNIT_SET            148
#define kCFG_FEATURE_CFG_DOORS_OFF_ACC_DLY   149
#define kCFG_FEATURE_CFG_MOTORIZED_SEATBELT  150
#define kCFG_FEATURE_CFG_MOTORIZED_SEATBELT_STRN 151
#define kCFG_FEATURE_CFG_TSI                 152
#define kCFG_FEATURE_CFG_LKA                 153
#define kCFG_FEATURE_CFG_LKA_SENS            154
#define kCFG_FEATURE_CFG_LKA_STRN            155
#define kCFG_FEATURE_CFG_ABSD                156
#define kCFG_FEATURE_CFG_ABSD_SENS           157
#define kCFG_FEATURE_CFG_ABSD_STRN           158
#define kCFG_FEATURE_CFG_TIRE_FILL_ALERT     162
#define kCFG_FEATURE_CFG_POWER_SIDE_STEP     163
#define kCFG_FEATURE_CFG_AUTO_STOP_START     164
#define kCFG_FEATURE_CFG_PEB                 165
#define kCFG_FEATURE_CFG_FFC_GRIDLINES       166
#define kCFG_FEATURE_CFG_RVC_CVPM_DGRID      167
#define kCFG_FEATURE_CFG_RVC_CVPM_SGRID      168
#define kCFG_FEATURE_CFG_SPEED_THRESHOLD_VALUE 169
#define kCFG_FEATURE_CFG_SPEED_THRESHOLD_CHECK_BOX 170
#define kCFG_FEATURE_CFG_EXTERNAL_LIGHT_SENSOR 171
#define kCFG_FEATURE_CFG_BUZZER_VOLUME_LEVEL 172
#define kCFG_FEATURE_CFG_TRUNK_UNLOCK_ENABLE 173
#define kCFG_FEATURE_CFG_BACKUP_ALARM        174
#define kCFG_FEATURE_CFG_RR_CARGO_GUIDE_LGT  175
#define kCFG_FEATURE_CFG_PTO_HI_IDLE         176
#define kCFG_FEATURE_CFG_PTO_HI_IDLE_RPM     177
#define kCFG_FEATURE_CFG_PTO_RMT_RPM_CTRL    178
#define kCFG_FEATURE_CFG_PTO_SS_GEAR_RATIO   179
#define kCFG_FEATURE_CFG_PTO_ACC_INT         180
#define kCFG_FEATURE_CFG_PTO_RAMP_RATE       181
#define kCFG_FEATURE_CFG_PTO_PB              182
#define kCFG_FEATURE_CFG_HWRSS               183
#define kCFG_FEATURE_CFG_SEIU_INPUT_WIRE     184
#define kCFG_FEATURE_CFG_SEIU_RPM            185
#define kCFG_FEATURE_CFG_BED_LOWER           186
#define kCFG_FEATURE_CFG_TSR_WARNING_MODE    187
#define kCFG_FEATURE_CFG_TSR_WARNING_MODE_OFFSET 188
#define kCFG_FEATURE_CFG_FT_PK_LOOSE_SHIP    189
#define kCFG_FEATURE_CFG_RR_PK_LOOSE_SHIP    190
#define kCFG_FEATURE_CFG_AUX6                191
#define kCFG_FEATURE_CFG_CHMSL_DYN_CNTR      192
#define kCFG_FEATURE_CFG_3RD_ROW_LOCK        193
#define kCFG_FEATURE_CFG_CHARGE_LOW_POPUP    194
#define kCFG_FEATURE_CFG_ESAVE               195
#define kCFG_FEATURE_CFG_ESAVE_BATT_LVL      196
#define kCFG_FEATURE_CFG_FOBIK_SAFE          197
#define kCFG_FEATURE_CFG_FOB_Left_Vehicle_Chime 198
#define kCFG_FEATURE_CFG_Theft_Alarm         199
#define kCFG_FEATURE_CFG_PANIC_ALARM         200
#define kCFG_FEATURE_CFG_SECURE_PARK_ACTIVATION 201
#define kCFG_FEATURE_CFG_SECURE_PARK_DEACTIVATION 202
#define kCFG_FEATURE_CFG_LIFTGATE_RELEASE_INSIDEBUTTON 203
#define kCFG_FEATURE_CFG_LIFTGATE_RELEASE_UNLOCKWITHDOORS 204
#define kCFG_FEATURE_CFG_VISM_KEEP_AWAKE     205
#define kCFG_FEATURE_FOA_Alert_Settings_FOAOnOff_Req 206
#define kCFG_FEATURE_FOA_Alert_Settings_PhoneAlertOnOff_Req 207
#define kCFG_STAT_RQ_CFG_SPEC                3
#define kCFG_STAT_RQ_CFG_ENBL                2
#define kCFG_STAT_RQ_CFG_DSBL                1
#define kCFG_STAT_RQ_CFG_DEF                 0


#define kCmdIgnStat_SNA                      7
#define kCmdIgnStat_IGN_START                5
#define kCmdIgnStat_IGN_RUN                  4
#define kCmdIgnStat_IGN_OFF_ACC              3
#define kCmdIgnStat_IGN_LK                   0


#define kBATT_VOLT_SNA                       255



#define kTGW_CAMERA_DISP_STAT_DISP_NON_CAMERA 0
#define kTGW_CAMERA_DISP_STAT_DISP_DIGITAL_RVC_CAMERA 1
#define kTGW_CAMERA_DISP_STAT_DISP_ANALOG_RVC_CAMERA 2
#define kTGW_CAMERA_DISP_STAT_DISP_ANALOG_CHMSL_CAMERA 3
#define kTGW_CAMERA_DISP_STAT_DISP_SURROUND_VIEW_CAMERA 4
#define kTGW_CAMERA_DISP_STAT_DISP_TRAILER_CAMERA 5
#define kTGW_CAMERA_DISP_STAT_DISP_WIRLESS_CAMERA 6
#define kTGW_CAMERA_DISP_STAT_DISP_SVS_MORECAMS_POPUP 7
#define kTGW_CAMERA_DISP_STAT_DISP_INTERIOR_CAMERA 8
#define kTGW_CAMERA_DISP_STAT_DISP_TRAILER_SURROUND_CAMERA 9
#define kTGW_CAMERA_DISP_STAT_Not_Used4      10
#define kTGW_CAMERA_DISP_STAT_Not_Used5      11
#define kTGW_CAMERA_DISP_STAT_Not_Used6      12
#define kTGW_CAMERA_DISP_STAT_Not_Used7      13
#define kTGW_CAMERA_DISP_STAT_Not_Used8      14
#define kTGW_CAMERA_DISP_STAT_SNA            15

#define kCameraDisplaySts2_OFF               0
#define kCameraDisplaySts2_VIEW_1            1
#define kCameraDisplaySts2_VIEW_2            2
#define kCameraDisplaySts2_VIEW_3            3
#define kCameraDisplaySts2_VIEW_4            4
#define kCameraDisplaySts2_VIEW_5            5
#define kCameraDisplaySts2_VIEW_6            6
#define kCameraDisplaySts2_VIEW_7            7
#define kCameraDisplaySts2_VIEW_8            8
#define kCameraDisplaySts2_VIEW_9            9
#define kCameraDisplaySts2_VIEW_10           10
#define kCameraDisplaySts2_VIEW_11           11
#define kCameraDisplaySts2_VIEW_12           12
#define kCameraDisplaySts2_VIEW_13           13
#define kCameraDisplaySts2_VIEW_14           14
#define kCameraDisplaySts2_VIEW_15           15
#define kCameraDisplaySts2_VIEW_16           16
#define kCameraDisplaySts2_VIEW_17           17
#define kCameraDisplaySts2_VIEW_18           18
#define kCameraDisplaySts2_VIEW_19           19
#define kCameraDisplaySts2_VIEW_20           20
#define kCameraDisplaySts2_VIEW_21           21
#define kCameraDisplaySts2_VIEW_22           22
#define kCameraDisplaySts2_VIEW_23           23
#define kCameraDisplaySts2_VIEW_24           24
#define kCameraDisplaySts2_VIEW_25           25
#define kCameraDisplaySts2_VIEW_26           26
#define kCameraDisplaySts2_VIEW_27           27
#define kCameraDisplaySts2_VIEW_28           28
#define kCameraDisplaySts2_VIEW_29           29
#define kCameraDisplaySts2_VIEW_30           30
#define kCameraDisplaySts2_VIEW_31           31
#define kCameraDisplaySts2_VIEW_32           32
#define kCameraDisplaySts2_VIEW_33           33
#define kCameraDisplaySts2_VIEW_34           34
#define kCameraDisplaySts2_VIEW_35           35
#define kCameraDisplaySts2_VIEW_36           36
#define kCameraDisplaySts2_VIEW_37           37
#define kCameraDisplaySts2_VIEW_38           38
#define kCameraDisplaySts2_VIEW_39           39
#define kCameraDisplaySts2_VIEW_40           40
#define kCameraDisplaySts2_VIEW_41           41
#define kCameraDisplaySts2_VIEW_42           42
#define kCameraDisplaySts2_VIEW_43           43
#define kCameraDisplaySts2_VIEW_44           44
#define kCameraDisplaySts2_VIEW_45           45
#define kCameraDisplaySts2_VIEW_46           46
#define kCameraDisplaySts2_VIEW_47           47
#define kCameraDisplaySts2_VIEW_48           48
#define kCameraDisplaySts2_VIEW_49           49
#define kCameraDisplaySts2_VIEW_50           50
#define kCameraDisplaySts2_VIEW_51           51
#define kCameraDisplaySts2_VIEW_52           52
#define kCameraDisplaySts2_VIEW_53           53
#define kCameraDisplaySts2_VIEW_54           54
#define kCameraDisplaySts2_VIEW_55           55
#define kCameraDisplaySts2_VIEW_56           56
#define kCameraDisplaySts2_VIEW_57           57
#define kCameraDisplaySts2_VIEW_58           58
#define kCameraDisplaySts2_VIEW_59           59
#define kCameraDisplaySts2_VIEW_60           60
#define kCameraDisplaySts2_VIEW_61           61
#define kCameraDisplaySts2_VIEW_62           62
#define kCameraDisplaySts2_VIEW_63           63


#define kVC_VehCfg8_Stat_NA                  0
#define kVC_VehCfg8_Stat_PROGAMMED           1
#define kVC_VehCfg8_Stat_REQUEST_DATA        2
#define kVC_VehCfg8_Stat_SNA                 3
#define kVC_Steering_Cfactor_TYPE_1          0
#define kVC_Steering_Cfactor_TYPE_2          1
#define kVC_Steering_Cfactor_TYPE_3          2
#define kVC_Steering_Cfactor_TYPE_4          3
#define kVC_WHL_BASE_LENGTH_Not_Used         0
#define kVC_WHL_BASE_LENGTH_Length_1         1
#define kVC_WHL_BASE_LENGTH_Length_2         2
#define kVC_WHL_BASE_LENGTH_Length_3         3
#define kVC_WHL_BASE_LENGTH_Length_4         4
#define kVC_WHL_BASE_LENGTH_Length_5         5
#define kVC_WHL_BASE_LENGTH_Length_6         6
#define kVC_WHL_BASE_LENGTH_Length_7         7
#define kVC_WHL_BASE_LENGTH_Length_8         8
#define kVC_WHL_BASE_LENGTH_Length_9         9
#define kVC_WHL_BASE_LENGTH_Length_10        10
#define kVC_WHL_BASE_LENGTH_Length_11        11
#define kVC_WHL_BASE_LENGTH_Length_12        12
#define kVC_WHL_BASE_LENGTH_Length_13        13
#define kVC_WHL_BASE_LENGTH_Length_14        14
#define kVC_WHL_BASE_LENGTH_Length_15        15


#define kTRSC_STAT_Off                       0
#define kTRSC_STAT_Standby                   1
#define kTRSC_STAT_Calibrating               2
#define kTRSC_STAT_PreActive                 3
#define kTRSC_STAT_Active                    4
#define kTRSC_STAT_SNA                       7


#define ITBM_TrlrStat_PRSNT                  1
#define TRLRCNCTSTS                          1
#define TRLR_CONN_INFO                       1

#define kTRG_INACTIVE                        0
#define kTRG_AUTO_PAN                        1
#define kTRG_MANU_PAN                        2
#define kTRG_STAT_SNA                        3 


#endif /* __HMI_DRV_PAR_H__ */
