from ErrorMgrCommon import ErrorManager_GeneratorVersion
from datetime import datetime
import os

now = datetime.now()
uniqueTime="0x"+now.strftime("%y%m%d%H%M%S")

def EmbedGenInfo(fHandle,InputVersion):
    long_ver,short_ver=InputVersion
    fHandle.write("\n\n/**********************************************************")
    fHandle.write("\nGenerated on : \t"+ uniqueTime)
    fHandle.write("\nGenerated using Generator Version :"+ErrorManager_GeneratorVersion)
    fHandle.write("\nGenerated using Excel file Version :" + long_ver)
    fHandle.write("\nGenerated by :" + os.getlogin())
    fHandle.write("\n**************************************************************/\n\n")

    fHandle.write("\n#ifndef ERRORMGR_VERSIONCHECKER_VERSION")
    fHandle.write("\n\t#define ERRORMGR_VERSIONCHECKER_VERSION "+uniqueTime)
    fHandle.write("\n#else")
    fHandle.write("\n\t#if ERRORMGR_VERSIONCHECKER_VERSION != "+uniqueTime)
    fHandle.write("\n\t\t#error \"mismatched files used for compiling\"")
    fHandle.write("\n\t#endif")
    fHandle.write("\n#endif")
    fHandle.write("\n\n\n")