/*
 * $QNXLicenseC:
 * Copyright 2018, QNX Software Systems. All Rights Reserved.
 *
 * You must obtain a written license from and pay applicable
 * license fees to QNX Software Systems before you may reproduce,
 * modify or distribute this software, or any work that includes
 * all or part of this software. Free development licenses are
 * available for evaluation and non-commercial purposes. For more
 * information visit http://licensing.qnx.com or email
 * licensing@qnx.com.
 *
 * This file may contain contributions from others. Please review
 * this entire file for other proprietary rights or license notices,
 * as well as the QNX Development Suite License Guide at
 * http://licensing.qnx.com/license-guide/ for other information.
 * $
 */

/**
 * @file camera_meta.h
 *
 * @brief This file defines functions that you can use to extract the metadata
 *        that is associated with a camera buffer.
 *
 *
 */

#ifndef __CAMERA_CAMERA_META_H__
#define __CAMERA_CAMERA_META_H__

#ifdef __cplusplus
extern "C" {
#endif

#include <camera/camera_api.h>
#include <stdint.h>
#include <stdbool.h>

/**
 * @brief This enumerated type specifies the possible camera metadata items
 *
 *        These IDs are used as keys for the @c
 *        camera_get_metadata_entry() function.
 *        Each key is associated with a value of the indicated type.
 */
typedef enum {
    // Embedded register values generated by the sensor while capturing the frame.
    METADATA_ID_EMBEDDED_REGS = 100,
    // Histograms and embedded statistics generated by the sensor for the current frame.
    METADATA_ID_EMBEDDED_STATS,
    // Exposure statistics calculated by the ISP for current frame.
    METADATA_ID_EXPOSURE_STATS,
    // Anti fog statistics calculated by the ISP for current frame.
    METADATA_ID_ANTI_FOG_STATS,
    // MAX9286 deserializer link status.
    METADATA_ID_MAX9286_LINK_STATUS,
    // The ID of current context for the given stream
    METADATA_ID_STREAM_CONTEXT
} camera_metadata_id_t;


/**
 * @brief Get pointer and size to a metadata item.
 * @details Use this function to get a metadata item associated with the
 * provided camera buffer.
 *
 * @param buffer A pointer to the buffer that has the required metadata item.
 * @param id The ID of the required metadata item.
 * @param metabuf A pointer to be set to the beginning of the required metadata item.
 * @param metasize A pointer to be set to the size of the required metadata item.
 * @return @c #CAMERA_EOK when the function successfully completes, otherwise
 *         another @c ::camera_error_t value that provides the reason that the
 *         call failed. @c #CAMERA_EINVAL is returned if one of the provided pointers
 *         is invalid. @c #CAMERA_ENODATA is returned if there is not enough space in
 *         the associated metadata buffer to search for items or if the item was not
 *         found.
 */
camera_error_t
camera_get_metadata_entry(const camera_buffer_t *buffer,
                          camera_metadata_id_t id,
                          void** metabuf,
                          uint64_t *metasize);


#ifdef __cplusplus
}
#endif
#endif /* __CAMERA_CAMERA_META_H__ */

#if defined(__QNXNTO__) && defined(__USESRCVERSION)
#include <sys/srcversion.h>
__SRCVERSION("$URL$ $Rev$")
#endif
