#ifndef SYSTEMSTATEDEFINITION_CFG_INCLUDEGUARD_H
#define SYSTEMSTATEDEFINITION_CFG_INCLUDEGUARD_H

#if defined(BUILD_MCU1_0) 
	#define SSM_APPLICATION_SLAVE
    #define SSM_APPLICATION_MASTER
#elif defined(BUILD_MCU2_0) 
    #define SSM_APPLICATION_SLAVE
#elif defined(BUILD_MCU2_1) 
	#define SSM_APPLICATION_SLAVE
#elif defined(BUILD_MCUQNX) 
	#define SSM_APPLICATION_SLAVE
#else
    #warning "Undefined SSM"
#endif

/* need to be commented out in Release and production software */
//#define SSM_DISABLE_STATIC_ALERTCHECKS
//#define SSM_UNITTESTSING_ENABLED

#define D_STATICARRAYMAX_SSM_MCU_1_0_Application_MAX	(20u)
#define D_STATICARRAYMAX_SSM_MCU_2_0_Application_MAX	(20u)
#define D_STATICARRAYMAX_SSM_MCU_2_1_Application_MAX	(20u)
#define D_STATICARRAYMAX_SSM_MCU_QNX_Application_MAX	(20u)

#define D_SSM_MASTER_PERIODICRUNNABLE_TIME_MS			(10u)

/* Timeout  represents the maximum amount of time you can stay in a state in msec*/
#define D_SSM_STATE_BOOTING_Timeout							(10000u/D_SSM_MASTER_PERIODICRUNNABLE_TIME_MS)
#define D_SSM_STATE_IPCREADY_Timeout						(10000u/D_SSM_MASTER_PERIODICRUNNABLE_TIME_MS)
#define D_SSM_STATE_RUNNING_Timeout							(0u)
#define D_SSM_STATE_DEGRADED_Timeout						(0u)
#define D_SSM_STATE_POWERINGDOWN_Timeout 					(5000u/D_SSM_MASTER_PERIODICRUNNABLE_TIME_MS)
#define D_SSM_STATE_SHUTTINGDOWN_REMOTECORES_Timeout		(5000u/D_SSM_MASTER_PERIODICRUNNABLE_TIME_MS)
#define D_SSM_STATE_MASTERCORE_SHUTDOWNJOBSEXECUTE_Timeout	(5000u/D_SSM_MASTER_PERIODICRUNNABLE_TIME_MS)
#define D_SSM_STATE_OFF_Timeout								(10000u/D_SSM_MASTER_PERIODICRUNNABLE_TIME_MS)
#define D_SSM_STATE_BOOT_ERROR_Timeout						(5000u/D_SSM_MASTER_PERIODICRUNNABLE_TIME_MS)
#define D_SSM_STATE_MAX_Timeout								(0u)

#define D_SHUTDOWN_REQUESTED_FLAG_UNIQUE	(0x12568965u)

#define SSM_BOOT_ISSUE				0x11u
#define SSM_APP_RUN_ISSUE			0x22u
#define SSM_SHUTDOWN_CLEANUP_ISSUE	0x33u


#ifdef SSM_UNITTESTSING_ENABLED
	#define SSM_STATIC_EXTERNAL_LINKAGE
	#define SSM_CONST_EXTERNAL_LINKAGE
#else
	#define SSM_STATIC_EXTERNAL_LINKAGE	static
	#define SSM_CONST_EXTERNAL_LINKAGE	const
#endif


#endif
