#ifndef ERRORMANAGER_CFG_INCGUARD
#define ERRORMANAGER_CFG_INCGUARD


#define ERRMANAGER_QM_LEVEL_ACTIVE	1u
#define ERRMANAGER_A_LEVEL_ACTIVE	0u
#define ERRMANAGER_B_LEVEL_ACTIVE	1u
#define ERRMANAGER_C_LEVEL_ACTIVE	0u
#define ERRMANAGER_D_LEVEL_ACTIVE	0u

//#define ERRORMGR_ENABLE_DEM_CALLBACK
//#define ERRORMGR_ENABLESERIALPRINTOUT
#include <stdio.h>
#ifdef ERRORMGR_ENABLESERIALPRINTOUT
	#ifdef _WIN32
		#define ERRORMGR_SERIALPRINTOUT_2P	printf
		#define ERRORMGR_SERIALPRINTOUT_3P	printf

	#else
		#define ERRORMGR_SERIALPRINTOUT_2P	UART_printf
		#define ERRORMGR_SERIALPRINTOUT_3P	UART_printf

#endif
#else
	//Warnings are treated as errors. Hence
	#define ERRORMGR_SERIALPRINTOUT_2P(a,b)
	#define ERRORMGR_SERIALPRINTOUT_3P(a,b,c)
#endif



//Type of ErrorMgr
#define ERRORMGR_TYPE_SATELLITE   (0x01u)
#define ERRORMFR_TYPE_AGGREGATOR  (0x02u)

//Different types of underlying communication layers
#define ERRORMGR_TYPE_UNDERLYINGCOMLAYER_UNDEFINED   (0x00u)
#define ERRORMGR_TYPE_UNDERLYINGCOMLAYER_SIGNALMGR   (0x01u)
#define ERRORMGR_TYPE_UNDERLYINGCOMLAYER_RTE  (0x02u)

//Differnt Types of Notifications in Aggregator
#define ERRORMGR_TYPE_PERIODIC_SATSAMPLING	0x01u
#define ERRORMGR_TYPE_ASYNC_NOTIFICATION 0x02u


//Defines for
#define ERRORMGRCORE_MCU1_0 (0x00u)
#define ERRORMGRCORE_MCU2_0 (0x01u)
#define ERRORMGRCORE_MCU2_1 (0x02u)
//#define ERRORMGRCORE_MCU3_0 (0x03)
//#define ERRORMGRCORE_MCU3_1 (0x04)
#define ERRORMGRCORE_MCUQNX (0x03u)
#define ERRORMGRCORE_CORE_MAX (0x04u)


//Selection of current core used for the build
//Need to be configured for every project
#if defined(BUILD_MCU2_0)
	#define ERRORMGR_CURRENTCORE ERRORMGRCORE_MCU2_0
#elif defined(BUILD_MCU2_1)
	#define ERRORMGR_CURRENTCORE ERRORMGRCORE_MCU2_1
//#elif defined(BUILD_MCU3_0)
//	#define ERRORMGR_CURRENTCORE ERRORMGRCORE_MCU3_0
//#elif defined(BUILD_MCU3_1)
//	#define ERRORMGR_CURRENTCORE ERRORMGRCORE_MCU3_1
#elif defined(BUILD_MCU1_0)
	#define ERRORMGR_CURRENTCORE ERRORMGRCORE_MCU1_0
#elif defined(BUILD_MCUQNX)
   #define ERRORMGR_CURRENTCORE ERRORMGRCORE_MCUQNX
   #define 	ErrorMgr_QNX_Enable_DebugPrints
#else
	//#warning "Need to define a BUILD version to ErrorManagerCore to use this file"
	#define ERRORMGR_CURRENTCORE ERRORMGRCORE_CORE_MAX
#endif

#define ERRORMGR_AGGREGATORCORE ERRORMGRCORE_MCU1_0



#define ERRORMGR_E2EPROTECTIONTYPE_LOCAL	(0x01u)
#define ERRORMGR_E2EPROTECTIONTYPE_VFB		(0x02u)
#define ERRORMGR_E2EPROTECTIONTYPE	ERRORMGR_E2EPROTECTIONTYPE_LOCAL



#if ERRORMGR_CURRENTCORE == ERRORMGR_AGGREGATORCORE

	#define ERRORMGR_TIMEOUT_CORE_1_0_ASIL_QM_VALUE_MS  (90u)
	#define ERRORMGR_TIMEOUT_CORE_2_0_ASIL_QM_VALUE_MS  (90u)
	#define ERRORMGR_TIMEOUT_CORE_2_1_ASIL_QM_VALUE_MS  (90u)
	#define ERRORMGR_TIMEOUT_CORE_3_0_ASIL_QM_VALUE_MS  (90u)
	#define ERRORMGR_TIMEOUT_CORE_3_1_ASIL_QM_VALUE_MS  (90u)
	#define ERRORMGR_TIMEOUT_CORE_QNX_ASIL_QM_VALUE_MS  (90u)
//	#define ERRORMGR_TIMEOUT_CORE_1_0_ASIL_A_VALUE_MS  (90)
//	#define ERRORMGR_TIMEOUT_CORE_2_0_ASIL_A_VALUE_MS  (90)
//	#define ERRORMGR_TIMEOUT_CORE_2_1_ASIL_A_VALUE_MS  (90)
//	#define ERRORMGR_TIMEOUT_CORE_3_0_ASIL_A_VALUE_MS  (90)
//	#define ERRORMGR_TIMEOUT_CORE_3_1_ASIL_A_VALUE_MS  (90)
//	#define ERRORMGR_TIMEOUT_CORE_QNX_ASIL_A_VALUE_MS  (90)
	#define ERRORMGR_TIMEOUT_CORE_1_0_ASIL_B_VALUE_MS  (90u)
	#define ERRORMGR_TIMEOUT_CORE_2_0_ASIL_B_VALUE_MS  (90u)
	#define ERRORMGR_TIMEOUT_CORE_2_1_ASIL_B_VALUE_MS  (90u)
//	#define ERRORMGR_TIMEOUT_CORE_3_0_ASIL_B_VALUE_MS  (90)
//	#define ERRORMGR_TIMEOUT_CORE_3_1_ASIL_B_VALUE_MS  (90)
	#define ERRORMGR_TIMEOUT_CORE_QNX_ASIL_B_VALUE_MS  (90u)
	#define ERRORMGR_TIMEOUT_CORE_1_0_ASIL_C_VALUE_MS  (90u)
	#define ERRORMGR_TIMEOUT_CORE_2_0_ASIL_C_VALUE_MS  (90u)
	#define ERRORMGR_TIMEOUT_CORE_2_1_ASIL_C_VALUE_MS  (90u)
	#define ERRORMGR_TIMEOUT_CORE_3_0_ASIL_C_VALUE_MS  (90u)
	#define ERRORMGR_TIMEOUT_CORE_3_1_ASIL_C_VALUE_MS  (90u)
	#define ERRORMGR_TIMEOUT_CORE_QNX_ASIL_C_VALUE_MS  (90u)
	#define ERRORMGR_TIMEOUT_CORE_1_0_ASIL_D_VALUE_MS  (90u)
	#define ERRORMGR_TIMEOUT_CORE_2_0_ASIL_D_VALUE_MS  (90u)
	#define ERRORMGR_TIMEOUT_CORE_2_1_ASIL_D_VALUE_MS  (90u)
	#define ERRORMGR_TIMEOUT_CORE_3_0_ASIL_D_VALUE_MS  (90u)
	#define ERRORMGR_TIMEOUT_CORE_3_1_ASIL_D_VALUE_MS  (90u)
	#define ERRORMGR_TIMEOUT_CORE_QNX_ASIL_D_VALUE_MS  (90u)



	#define ERRORMGR_AGGREGATORMONITOR_TASKPERIOD_ASIL_QM_MS	(30u)
//	#define ERRORMGR_AGGREGATORMONITOR_TASKPERIOD_ASIL_A_MS	(30)
	#define ERRORMGR_AGGREGATORMONITOR_TASKPERIOD_ASIL_B_MS	(30u)
//	#define ERRORMGR_AGGREGATORMONITOR_TASKPERIOD_ASIL_C_MS	(30)
//	#define ERRORMGR_AGGREGATORMONITOR_TASKPERIOD_ASIL_D_MS	(30)


   #define AUTOSAR_AGGREGATOR_TASKPERIOD_ASIL_QM_MS	(10u)
//	#define AUTOSAR_AGGREGATOR_TASKPERIOD_ASIL_A_MS		(10)
	#define AUTOSAR_AGGREGATOR_TASKPERIOD_ASIL_B_MS	   (10u)
//	#define AUTOSAR_AGGREGATOR_TASKPERIOD_ASIL_C_MS	   (10)
//	#define AUTOSAR_AGGREGATOR_TASKPERIOD_ASIL_D_MS	   (10)

	#define ERRORMGT_AGGREGATORCORE_UNDERLYINGCOMLAYER ERRORMGR_TYPE_UNDERLYINGCOMLAYER_RTE

	#define ERRORMGR_AGGREGATORCORE_SATMONITOR	ERRORMGR_TYPE_PERIODIC_SATSAMPLING

   //Todo::This needs to be turned on after the system becomes stable
	//#define ERRORMGR_AGGREGATOR_ASSERTINDIVIDUALERRORS_DURINGLOSSOFCOMM

	#define ErrorMgrAggregatorApp_Write_QM_ErrorStatus(x,y,z) 	Rte_Write_P_Errors_QM_Errors_QM_stub(x,y,z)
//	#define ErrorMgrAggregatorApp_Write_A_ErrorStatus(x,y,z)
	#define ErrorMgrAggregatorApp_Write_B_ErrorStatus(x,y,z) 	Rte_Write_P_Errors_B_Errors_B_stub(x,y,z)
//	#define ErrorMgrAggregatorApp_Write_C_ErrorStatus(x,y,z)
//	#define ErrorMgrAggregatorApp_Write_D_ErrorStatus(x,y,z)



	#define ErrorMgrAggregatorApp_Write_QM_SafeState(x,y,z) Rte_Write_P_SafeState_SafeStateOp_QM_stub(x,y,z)
//	#define ErrorMgrAggregatorApp_Write_A_SafeState(x,y,z)
	#define ErrorMgrAggregatorApp_Write_B_SafeState(x,y,z) 	Rte_Write_P_SafeState_SafeStateOp_B_stub(x,y,z)
//	#define ErrorMgrAggregatorApp_Write_C_SafeState(x,y,z)
//	#define ErrorMgrAggregatorApp_Write_D_SafeState(x,y,z)

#endif



#if ERRORMGR_CURRENTCORE ==  ERRORMGRCORE_MCU1_0
	#define ERRORMGRSATELLITE_UNDERLYINGCOMLAYER ERRORMGR_TYPE_UNDERLYINGCOMLAYER_RTE
	#define ERRORMGRSATELLITE_PERIODICFUNC_TIME_MS	(30u)
	#define ERRORMGRSATELLITE_OSPERIODIC_CALLBACK_TIME_MS	(10u)
	#define ERRORMGRSATELLITE_NOTIFICATION_RATE_PER_NTH_CYCLE	(1u)
	#define ERRORMGRSATELLITE_SATELLITE_SEND(x)
	#define ERRORMGRSATELLITE_SATELLITE_SEND_QM(x)	Rte_Write_P_SatError_Data_ErrorMgr_ErrorCommPack_1_0_QM_stub(x)
//	#define ERRORMGRSATELLITE_SATELLITE_SEND_A(x)
	#define ERRORMGRSATELLITE_SATELLITE_SEND_B(x)	Rte_Write_P_SatError_Data_ErrorMgr_ErrorCommPack_1_0_B_stub(x)
//	#define ERRORMGRSATELLITE_SATELLITE_SEND_C(x)
//	#define ERRORMGRSATELLITE_SATELLITE_SEND_D(x)
#elif ERRORMGR_CURRENTCORE ==  ERRORMGRCORE_MCU2_0
	#define ERRORMGRSATELLITE_UNDERLYINGCOMLAYER ERRORMGR_TYPE_UNDERLYINGCOMLAYER_SIGNALMGR
	#define ERRORMGRSATELLITE_PERIODICFUNC_TIME_MS	(30u)
	#define ERRORMGRSATELLITE_NOTIFICATION_RATE_PER_NTH_CYCLE	(1u)
	#define ERRORMGRSATELLITE_OSPERIODIC_CALLBACK_TIME_MS	(10u)
	#define ERRORMGRSATELLITE_SATELLITE_SEND_QM(x)	SigMgr_PpSatError_QM_Data_ErrorMgr_ErrorCommPack_2_0_QM_Put((ErrorMgr_ErrorCommPack_2_0_QM *)(x))
//	#define ERRORMGRSATELLITE_SATELLITE_SEND_A(x)
	#define ERRORMGRSATELLITE_SATELLITE_SEND_B(x)	SigMgr_PpSatError_B_Data_ErrorMgr_ErrorCommPack_2_0_B_Put((ErrorMgr_ErrorCommPack_2_0_B *)(x))
//	#define ERRORMGRSATELLITE_SATELLITE_SEND_C(x)
//	#define ERRORMGRSATELLITE_SATELLITE_SEND_D(x)
#elif ERRORMGR_CURRENTCORE ==  ERRORMGRCORE_MCU2_1
	#define ERRORMGRSATELLITE_UNDERLYINGCOMLAYER ERRORMGR_TYPE_UNDERLYINGCOMLAYER_SIGNALMGR
	#define ERRORMGRSATELLITE_PERIODICFUNC_TIME_MS	(30u)
	#define ERRORMGRSATELLITE_NOTIFICATION_RATE_PER_NTH_CYCLE	(1u)
   #define ERRORMGRSATELLITE_OSPERIODIC_CALLBACK_TIME_MS	(10u)
	#define ERRORMGRSATELLITE_SATELLITE_SEND_QM(x) SigMgr_PpSatError_QM_Data_ErrorMgr_ErrorCommPack_2_1_QM_Put((ErrorMgr_ErrorCommPack_2_1_QM *)(x))
//	#define ERRORMGRSATELLITE_SATELLITE_SEND_A(x)
	#define ERRORMGRSATELLITE_SATELLITE_SEND_B(x)  SigMgr_PpSatError_B_Data_ErrorMgr_ErrorCommPack_2_1_B_Put((ErrorMgr_ErrorCommPack_2_1_B *)(x))
//	#define ERRORMGRSATELLITE_SATELLITE_SEND_C(x)
//	#define ERRORMGRSATELLITE_SATELLITE_SEND_D(x)
#elif ERRORMGR_CURRENTCORE ==  ERRORMGRCORE_MCU3_0
	#define ERRORMGRSATELLITE_UNDERLYINGCOMLAYER ERRORMGR_TYPE_UNDERLYINGCOMLAYER_SIGNALMGR
	#define ERRORMGRSATELLITE_PERIODICFUNC_TIME_MS	(30u)
	#define ERRORMGRSATELLITE_NOTIFICATION_RATE_PER_NTH_CYCLE	(1u)
   #define ERRORMGRSATELLITE_OSPERIODIC_CALLBACK_TIME_MS	(10u)
	#define ERRORMGRSATELLITE_SATELLITE_SEND_QM(x) SigMgr_P_SatError_QM_Data_ErrorMgr_ErrorCommPack_3_0_QM_Put((ErrorMgr_ErrorCommPack_3_0_QM *)(x))
	#define ERRORMGRSATELLITE_SATELLITE_SEND_A(x)
	#define ERRORMGRSATELLITE_SATELLITE_SEND_B(x)  SigMgr_P_SatError_B_Data_ErrorMgr_ErrorCommPack_3_0_B_Put((ErrorMgr_ErrorCommPack_3_0_B *)(x))
	#define ERRORMGRSATELLITE_SATELLITE_SEND_C(x)
	#define ERRORMGRSATELLITE_SATELLITE_SEND_D(x)
#elif ERRORMGR_CURRENTCORE ==  ERRORMGRCORE_MCU3_1
	#define ERRORMGRSATELLITE_UNDERLYINGCOMLAYER ERRORMGR_TYPE_UNDERLYINGCOMLAYER_RTE
	#define ERRORMGRSATELLITE_PERIODICFUNC_TIME_MS	(30u)
	#define ERRORMGRSATELLITE_NOTIFICATION_RATE_PER_NTH_CYCLE	(1u)
   #define ERRORMGRSATELLITE_OSPERIODIC_CALLBACK_TIME_MS	(10u)
	#define ERRORMGRSATELLITE_SATELLITE_SEND_QM(x)	Rte_Write_P_SatError_Data_ErrorMgr_ErrorCommPack_3_1_QM_stub(x)
	#define ERRORMGRSATELLITE_SATELLITE_SEND_A(x)
	#define ERRORMGRSATELLITE_SATELLITE_SEND_B(x)	Rte_Write_P_SatError_Data_ErrorMgr_ErrorCommPack_3_1_B_stub(x)
	#define ERRORMGRSATELLITE_SATELLITE_SEND_C(x)
	#define ERRORMGRSATELLITE_SATELLITE_SEND_D(x)

#elif ERRORMGR_CURRENTCORE ==  ERRORMGRCORE_MCUQNX
	#define ERRORMGRSATELLITE_UNDERLYINGCOMLAYER ERRORMGR_TYPE_UNDERLYINGCOMLAYER_SIGNALMGR
	#define ERRORMGRSATELLITE_PERIODICFUNC_TIME_MS	(30u)
	#define ERRORMGRSATELLITE_NOTIFICATION_RATE_PER_NTH_CYCLE	(1u)
	#define ERRORMGRSATELLITE_OSPERIODIC_CALLBACK_TIME_MS	(10u)
	#define ERRORMGRSATELLITE_SATELLITE_SEND_QM(x)  SigMgr_P_SatError_QM_Data_ErrorMgr_ErrorCommPack_QNX_QM_Put((ErrorMgr_ErrorCommPack_QNX_QM *)x)
	#define ERRORMGRSATELLITE_SATELLITE_SEND_A(x)
	#define ERRORMGRSATELLITE_SATELLITE_SEND_B(x)  SigMgr_P_SatError_B_Data_ErrorMgr_ErrorCommPack_QNX_B_Put((ErrorMgr_ErrorCommPack_QNX_B *)x)
	#define ERRORMGRSATELLITE_SATELLITE_SEND_C(x)
	#define ERRORMGRSATELLITE_SATELLITE_SEND_D(x)


#else
	#error "ErrorMgr Undefined MCU Core"
#endif




#define ERRORMGR_SATELLITE_DISABLE_STATICARRAYCHECKS_BETWEENRTEANDLOCALDATATYPES
#define ERRORMGR_AGGREGARTOR_DISABLE_STATICARRAYCHECKS_BETWEENRTEANDLOCALDATATYPES



#define ERROR_MANAGER_DEBUG_ENABLEREADABLESTRUCT_REPRESENTATION    1u


#ifdef WIN32

	//VS Enviroment
	#define ERRMANAGER_ATTR_B_HIGHPERF_BSS
	#define ERRMANAGER_ATTR_B_BSS

	#define ERRMANAGER_ATTR_QM_HIGHPERF_BSS
	#define ERRMANAGER_ATTR_QM_BSS

	#define ERRMANAGER_ATTR_CONST_HIGHPERF

#else

	#if defined(BUILD_MCU1_0)

		#define ERRMANAGER_ATTR_B_HIGHPERF_BSS 		__attribute__((section("ERRManager_BSS_B_HighPerf")))
		#define ERRMANAGER_ATTR_B_BSS 					__attribute__((section("ERRManager_BSS_B")))

		#define ERRMANAGER_ATTR_QM_HIGHPERF_BSS 		__attribute__((section("ERRManager_BSS_QM_HighPerf")))
		#define ERRMANAGER_ATTR_QM_BSS 					__attribute__((section("ERRManager_BSS_QM")))

		#define ERRMANAGER_ATTR_CONST_HIGHPERF    	__attribute__((section("ERRManager_CONST_HighPerf")))

	#else

		#define ERRMANAGER_ATTR_B_HIGHPERF_BSS
		#define ERRMANAGER_ATTR_B_BSS

		#define ERRMANAGER_ATTR_QM_HIGHPERF_BSS
		#define ERRMANAGER_ATTR_QM_BSS

		#define ERRMANAGER_ATTR_CONST_HIGHPERF

	#endif


#endif





#endif
