#include "basesw_qnx_common.h"
#include "ErrorManagerDef.h"
#include "ErrorManagerQNX_Types.h"



/**************************************************************************************************
          This file is generated. Any changes will be overwritten. No handmodifications allowed   
          ErrorManager generator version used23.04.20                     
***************************************************************************************************/



/**********************************************************
Generated on : 	0x260127173337
Generated using Generator Version :23.04.20
Generated using Excel file Version :nan_NaT_nan
Generated by :sripkulk
**************************************************************/


#ifndef ERRORMGR_VERSIONCHECKER_VERSION
	#define ERRORMGR_VERSIONCHECKER_VERSION 0x260127173337
#else
	#if ERRORMGR_VERSIONCHECKER_VERSION != 0x260127173337
		#error "mismatched files used for compiling"
	#endif
#endif



#if ERRORMGR_CURRENTCORE == ERRORMGRCORE_MCUQNX


bool_t ErrorMgrSatelliteQnx_ReportErrorStatus(ldef_ErrorMgr_enErrorNo err, ldef_ErrorMgr_enErrorStatus enErrorStatus,const ldef_ErrorMgr_stAddData *AddData)
{
	bool_t bRet=FALSE;
	switch(err) {
		default: 
			break;   
	}
	return bRet;
}

#endif //if ERRORMGR_CURRENTCORE == ERRORMGRCORE_MCUQNX