/*
 * US_ErrMgrCfg.c
 *
 *  Created on: Mar 17, 2022
 *      Author: kkotkar
 */
#include "US_ErrMgrCfg.h"

#include "ErrorManagerDef.h"

US_DiagConfStrType DiagConfg[SNR_DIAG_FLG_SNR_FLAG_MAX_CODE] =
{
	{SNR_DIAG_FLG_SNR_TEMPERATURE_OUT_OF_RANGE,                                  SNR_OVER_TEMP_FLAG},
	{SNR_DIAG_FLG_SENSOR_DISCONNECT,                                             SNR_COMM_FAULT},                 
	{SNR_DIAG_FLG_RECEIVED_COMMAND_INVALID,                                      SNR_RECEIVED_COMMAND_INVALID},   /*used */
	{SNR_DIAG_FLG_PDCM_PULSE_INVALID,                                            SNR_COMM_FAULT},   /*not use */
	{SNR_DIAG_FLG_DISCOVERY_PULSE_INVALID,                                       SNR_COMM_FAULT},   /*not use */
	{SNR_DIAG_FLG_FCC_ERROR_STATE,                                               SNR_COMM_FAULT},   /*not use */
	{SNR_DIAG_FLG_INVALID_START_EDGE_DETECTED,                                   SNR_COMM_FAULT},   /*not use */
	{SNR_DIAG_FLG_SYNCHRONISATION_COUNTER_ERROR_DETECTED,                        SNR_SYNCHRONISATION_COUNTER_ERROR},
	{SNR_DIAG_FLG_CRM_TYPE_ERROR,                                                SNR_COMM_FAULT},  /*not use */
	{SNR_DIAG_FLG_SNR_COMM_UNKNOWN,                                              SNR_COMM_UNKNOWN},  /*not output */
	{SNR_DIAG_FLG_DRV1_FAILURE_DURING_BURST,                                     SNR_DRV1_FAILURE_DURING_BURST},        	               
	{SNR_DIAG_FLG_DRV2_FAILURE_DURING_BURST,                       	             SNR_DRV2_FAILURE_DURING_BURST},			
	{SNR_DIAG_FLG_DRVS_FAILURE_DURING_BURST,                       	             SNR_DRVS_FAILURE_DURING_BURST},			
	{SNR_DIAG_FLG_BURST_ABORT_DURING_BURST,                                      SNR_BURST_ABORT_DURING_BURST},			
	{SNR_DIAG_FLG_RING_COMPARATOR_ZERO,                                          SNR_RING_COMPARATOR_ZERO},				
	{SNR_DIAG_FLG_GET_RING_FREQUENCY_FAILURE,                                    SNR_GET_RING_FREQUENCY_FAILURE},		
	{SNR_DIAG_FLG_GET_DRV_FREQUENCY_FAILURE,                       	             SNR_GET_DRV_FREQUENCY_FAILURE},			
	{SNR_DIAG_FLG_SRAM_PARITY_ERROR,                                             SNR_SRAM_PARITY_ERROR},					
	{SNR_DIAG_FLG_CRC_MISTMATCH_IN_EEPROM_A1,                                    SNR_CRC_MISTMATCH_IN_EEPROM_A1},		
	{SNR_DIAG_FLG_CRC_MISTMATCH_IN_EEPROM_A2,                                    SNR_CRC_MISTMATCH_IN_EEPROM_A2},		
	{SNR_DIAG_FLG_ADA_MEASURE_TIMEOUT,                                           SNR_ADA_MEASURE_TIMEOUT},				
	{SNR_DIAG_FLG_PROGRAM_EEPROM,                                                SNR_PROGRAM_EEPROM},					
	{SNR_DIAG_FLG_VTANK_OVER_VOLTAGE_DURING_BURST,                               SNR_VTANK_OVER_VOLTAGE_DURING_BURST},	
	{SNR_DIAG_FLG_VTANK_OVERVOLTAGE,                                             SNR_VTANK_OVERVOLTAGE},					
	{SNR_DIAG_FLG_VTANK_UNDERVOLTAGE,                                            SNR_VTANK_UNDERVOLTAGE},				
	{SNR_DIAG_FLG_VSUP_OVER_VOLTAGE,                                             SNR_VSUP_OVER_VOLTAGE},					
	{SNR_DIAG_FLG_VSUP_UNDER_VOLTAGE,                                            SNR_VSUP_UNDER_VOLTAGE},				
	{SNR_DIAG_FLG_BAD_RING_TIME,                                                 SNR_NO_OUTPUT_FLAG},						
	{SNR_DIAG_FLG_TRANSDUCER_ERR,                                                SNR_NO_OUTPUT_FLAG},					
	{SNR_DIAG_FLG_SNR_BLOCKAGE,                                                  SNR_BLOCKAGE_FLAG},
	{SNR_DIAG_FLG_SNR_FW_MISMATCH,                                               SNR_FW_MISMATCH},
	{SNR_DIAG_FLG_SNR_OPMODE_ERROR,                                              SNR_OPMODE_ERROR},                               
	{SNR_DIAG_FLG_SNR_FAIL,                                                      SNR_LOSS_POWER_FAULT},
	{SNR_DIAG_FLG_SNR_SETUP_SENSOR_FAIL,                                         SNR_SNR_SETUP_SENSOR_FAIL},
#if(US_D_CUR_PLATFORM  == US_D_PLATFORM_CVADAS_HD)
    {SNR_DIAG_FLG_CRC_MISMATCH_IN_OTP,                                           SNR_NO_OUTPUT_FLAG},				                 	
    {SNR_DIAG_FLG_DSP_CONFIG_REGISTER_MISMATCH,                                  SNR_NO_OUTPUT_FLAG},		
    {SNR_DIAG_FLG_CPU_CONFIG_REGISTER_MISMATCH,                                  SNR_NO_OUTPUT_FLAG},		
    {SNR_DIAG_FLG_NOISE_DURING_BURST,                                            SNR_NO_OUTPUT_FLAG},				
    {SNR_DIAG_FLG_VREF_OUT_OF_RANGE,                                             SNR_NO_OUTPUT_FLAG},					
    {SNR_DIAG_FLG_VREF_OTP_OUT_OF_RANGE,                                         SNR_NO_OUTPUT_FLAG},				
    {SNR_DIAG_FLG_VDDD_OUT_OF_RANGE,                                             SNR_NO_OUTPUT_FLAG},					
    {SNR_DIAG_FLG_WD_COUNTER_DESYNC,                                             SNR_NO_OUTPUT_FLAG},					
    {SNR_DIAG_FLG_WD_CLOCK_FAIL,                                   				 SNR_NO_OUTPUT_FLAG},									
    {SNR_DIAG_FLG_CRC_BLOCK_CFG1,                                                SNR_NO_OUTPUT_FLAG},					
    {SNR_DIAG_FLG_CRC_BLOCK_CFG2,                                                SNR_NO_OUTPUT_FLAG},					
    {SNR_DIAG_FLG_CRC_BLOCK_MFG1,                                                SNR_NO_OUTPUT_FLAG},					
    {SNR_DIAG_FLG_CRC_BLOCK_MFG2,                                                SNR_NO_OUTPUT_FLAG},					
    {SNR_DIAG_FLG_CRC_OP_MODE1,                                                  SNR_NO_OUTPUT_FLAG},						
    {SNR_DIAG_FLG_CRC_OP_MODE2,                                                  SNR_NO_OUTPUT_FLAG},						
    {SNR_DIAG_FLG_SIGNAL_PATH_FAILURE,                                           SNR_NO_OUTPUT_FLAG}
#else
    {SNR_DIAG_FLG_CRC_MISMATCH_IN_OTP,                                           SNR_CRC_MISMATCH_IN_OTP},				                 	
    {SNR_DIAG_FLG_DSP_CONFIG_REGISTER_MISMATCH,                                  SNR_DSP_CONFIG_REGISTER_MISMATCH},		
    {SNR_DIAG_FLG_CPU_CONFIG_REGISTER_MISMATCH,                                  SNR_CPU_CONFIG_REGISTER_MISMATCH},		
    {SNR_DIAG_FLG_NOISE_DURING_BURST,                                            SNR_NOISE_DURING_BURST},				
    {SNR_DIAG_FLG_VREF_OUT_OF_RANGE,                                             SNR_VREF_OUT_OF_RANGE},					
    {SNR_DIAG_FLG_VREF_OTP_OUT_OF_RANGE,                                         SNR_VREF_OTP_OUT_OF_RANGE},				
    {SNR_DIAG_FLG_VDDD_OUT_OF_RANGE,                                             SNR_VDDD_OUT_OF_RANGE},					
    {SNR_DIAG_FLG_WD_COUNTER_DESYNC,                                             SNR_WD_COUNTER_DESYNC},					
    {SNR_DIAG_FLG_WD_CLOCK_FAIL,                                   				 SNR_WD_CLOCK_FAIL},									
    {SNR_DIAG_FLG_CRC_BLOCK_CFG1,                                                SNR_CRC_BLOCK_CFG1},					
    {SNR_DIAG_FLG_CRC_BLOCK_CFG2,                                                SNR_CRC_BLOCK_CFG2},					
    {SNR_DIAG_FLG_CRC_BLOCK_MFG1,                                                SNR_CRC_BLOCK_MFG1},					
    {SNR_DIAG_FLG_CRC_BLOCK_MFG2,                                                SNR_CRC_BLOCK_MFG2},					
    {SNR_DIAG_FLG_CRC_OP_MODE1,                                                  SNR_CRC_OP_MODE1},						
    {SNR_DIAG_FLG_CRC_OP_MODE2,                                                  SNR_CRC_OP_MODE2},						
    {SNR_DIAG_FLG_SIGNAL_PATH_FAILURE,                                           SNR_SIGNAL_PATH_FAILURE}				
#endif				
};


US_ECUDiagConfStrType ECUDiagConfg[DIAG_FLAG_ECU_MAX_CODE] =
{
    {DIAG_FLAG_REAR_BUMPER_SHRT_TO_GND, 		ECU_REAR_BUMPER_SHORT_TO_GND_FLAG},            /*DIAG_FLAG_REAR_BUMPER_SHRT_TO_GND = 0, */
	{DIAG_FLAG_REAR_BUMPER_OOR_LOW,				ECU_REAR_BUMPER_VOLTAGE_OOR_LOW_FLAG},         /*DIAG_FLAG_REAR_BUMPER_OOR_LOW, */
	{DIAG_FLAG_REAR_BUMPER_OOR_HIGH,			ECU_REAR_BUMPER_VOLTAGE_OOR_HIGH_FLAG},        /*DIAG_FLAG_REAR_BUMPER_OOR_HIGH, */
	{DIAG_FLAG_REAR_BUMPER_SHRT_TO_BAT,			ECU_REAR_BUMPER_SHORT_TO_BAT_FLAG},            /*DIAG_FLAG_REAR_BUMPER_SHRT_TO_BAT, */
	{DIAG_FLAG_REAR_BUMPER_OPEN, 				ECU_NO_OUTPUT_FLAG},                           /*DIAG_FLAG_REAR_BUMPER_OPEN, */
	{DIAG_FLAG_FRONT_BUMPER_OOR_LOW,    		ECU_FRONT_BUMPER_VOLTAGE_OOR_LOW_FLAG},        /*DIAG_FLAG_FRONT_BUMPER_OOR_LOW, */
	{DIAG_FLAG_FRONT_BUMPER_OOR_HIGH,   		ECU_FRONT_BUMPER_VOLTAGE_OOR_HIGH_FLAG },      /*DIAG_FLAG_FRONT_BUMPER_OOR_HIGH, */
	{DIAG_FLAG_FRONT_BUMPER_SHRT_TO_GND, 		ECU_FRONT_BUMPER_SHORT_TO_GND_FLAG},           /*DIAG_FLAG_FRONT_BUMPER_SHRT_TO_GND, */
	{DIAG_FLAG_FRONT_BUMPER_SHRT_TO_BAT,		ECU_FRONT_BUMPER_SHORT_TO_BAT_FLAG},           /*DIAG_FLAG_FRONT_BUMPER_SHRT_TO_BAT, */
	{DIAG_FLAG_FRONT_BUMPER_OPEN,   			ECU_NO_OUTPUT_FLAG},   	                       /*DIAG_FLAG_FRONT_BUMPER_OPEN, */
	{DIAG_FLAG_ECU_NO_CALI_DATA,                ECU_NO_CALI_DATA},  
#if(US_D_CUR_PLATFORM  == US_D_PLATFORM_CVADAS_HD)
	{DIAG_FLAG_ECU_SPI_DMA_ERR,                 ECU_NO_OUTPUT_FLAG},
#else
	{DIAG_FLAG_ECU_SPI_DMA_ERR,                 ECU_SPI_DMA_ERR},
#endif
	{DIAG_FLAG_ECU_CFG_SENSOR_ERR,              ECU_CFG_SENSOR_ERR},
	{DIAG_FLAG_ECU_GPIO_INT_INITIAL_ERR,        ECU_GPIO_INT_INITIAL_ERR},
	{DIAG_FLAG_ECU_PIN_INITIAL_ERR,             ECU_PIN_INITIAL_ERR},
	{DIAG_FLAG_ECU_DSI_CLOCK_INITIAL_ERR,       ECU_DSI_CLOCK_INITIAL_ERR},
	{DIAG_FLAG_ECU_DSI_REF_INITIAL_ERR,         ECU_NO_OUTPUT_FLAG},
	{DIAG_FLAG_ECU_SPI_INITIAL_ERR,             ECU_SPI_INITIAL_ERR},
	{DIAG_FLAG_ECU_MCAN_INITIAL_ERR,            ECU_NO_OUTPUT_FLAG},
	{DIAG_FLAG_ECU_USS_POWER_ON_ERR,            ECU_USS_POWER_ON_ERR},
    {DIAG_FLAG_ECU_DSI_OT_ERR,                  ECU_DSI_OT_ERR},
    {DIAG_FLAG_ECU_DSI_CRC_ERR,                 ECU_DSI_CRC_ERR},
    {DIAG_FLAG_ECU_DSI_RFC_ERR,                 ECU_DSI_RFC_ERR},
    {DIAG_FLAG_ECU_DSI_DSIUV_ERR,               ECU_NO_OUTPUT_FLAG},
    {DIAG_FLAG_ECU_DSI_VCCUV_ERR,               ECU_DSI_VCCUV_ERR},
    {DIAG_FLAG_ECU_DSI_RAM_BIST_FAIL,           ECU_DSI_RAM_BIST_FAIL},
    {DIAG_FLAG_ECU_DSI_FSM_RESET,               ECU_DSI_FSM_RESET},
    {DIAG_FLAG_ECU_DSI_CLKREF_ERR,              ECU_DSI_CLKREF_ERR},
    {DIAG_FLAG_ECU_DSI0_OC_ERR,                 ECU_DSI0_OC_ERR},
    {DIAG_FLAG_ECU_DSI1_OC_ERR,                 ECU_DSI1_OC_ERR},
    {DIAG_FLAG_ECU_DSI0_UV_ERR,                 ECU_DSI0_UV_ERR},
    {DIAG_FLAG_ECU_DSI1_UV_ERR,                 ECU_DSI1_UV_ERR},
    {DIAG_FLAG_ECU_COMM_ERR,                    ECU_COMM_ERR},
	{DIAG_FLAG_ECU_DSI3_registers_mismatch,     ECU_DSI3_registers_mismatch} 
};

/*CVADAS specific error map arrage with respect to sensorn ID & Flag position ,
 * IMP******if any new flags or sensors are added then need to update this array accordingly*/
ldef_ErrorMgr_enErrorNo SensorErrMap[US_D_MAX_NUM_SENSORS][MAX_DTC_SNR_FLAGS]=
{
	{   /* Sensor 1  error number */
	   ldef_ErrorMgr_Error_SENSOR1_OpenCkt_Fault,
       ldef_ErrorMgr_Error_SENSOR1_USS_Power_Lost_Fault,
	   ldef_ErrorMgr_Error_SENSOR1_USS_SWFirmWr_MisMatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_Temparature_out_of_range_error,   			
       ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_SNR_OPMODE_ERROR,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_DRV1_FAILURE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_DRV2_FAILURE_DURING_BURST, 
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_DRVS_FAILURE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_BURST_ABORT_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_RING_COMPARATOR_ZERO,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_GET_RING_FREQUENCY_FAILURE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_GET_DRV_FREQUENCY_FAILURE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_SRAM_Parity_error,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_CRC_MISTMATCH_IN_EEPROM_A1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_CRC_MISTMATCH_IN_EEPROM_A2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_ADA_MEASURE_TIMEOUT,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_PROGRAM_EEPROM,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_VTANK_overvoltage_burst_status_failure,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_VTANK_OVERVOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_VTANK_UNDERVOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_VSUP_OVER_VOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_VSUP_UNDER_VOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_BAD_RING_TIME,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_SNR_SETUP_SENSOR_FAIL,
#if(US_D_CUR_PLATFORM  != US_D_PLATFORM_CVADAS_HD)
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_CRC_MISMATCH_IN_OTP,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_DSP_Config_register_mismatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_CPU_Config_register_mismatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_NOISE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_Vref_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_VREF_OTP_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_VDDD_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_WD_COUNTER_DESYNC,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_WD_CLOCK_FAIL,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_CRC_BLOCK_CFG1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_CRC_BLOCK_CFG2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_CRC_BLOCK_MFG1,  
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_CRC_BLOCK_MFG2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_CRC_OP_MODE1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_CRC_OP_MODE2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_FLG_SIGNAL_PATH_FAILURE,
#endif
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_SYNCHRONISATION_COUNTER_ERROR_DETECTED,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR1_RECEIVED_COMMAND_INVALID,
	   ldef_ErrorMgr_Error_SENSOR1_USS_Sensor_Blockage
	},
	{   /* Sensor 2  error number */
	   ldef_ErrorMgr_Error_SENSOR2_OpenCkt_Fault,
       ldef_ErrorMgr_Error_SENSOR2_USS_Power_Lost_Fault,
	   ldef_ErrorMgr_Error_SENSOR2_USS_SWFirmWr_MisMatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_Temparature_out_of_range_error,   			
       ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_SNR_OPMODE_ERROR,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_DRV1_FAILURE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_DRV2_FAILURE_DURING_BURST, 
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_DRVS_FAILURE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_BURST_ABORT_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_RING_COMPARATOR_ZERO,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_GET_RING_FREQUENCY_FAILURE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_GET_DRV_FREQUENCY_FAILURE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_SRAM_Parity_error,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_CRC_MISTMATCH_IN_EEPROM_A1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_CRC_MISTMATCH_IN_EEPROM_A2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_ADA_MEASURE_TIMEOUT,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_PROGRAM_EEPROM,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_VTANK_overvoltage_burst_status_failure,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_VTANK_OVERVOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_VTANK_UNDERVOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_VSUP_OVER_VOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_VSUP_UNDER_VOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_BAD_RING_TIME,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_SNR_SETUP_SENSOR_FAIL,
#if(US_D_CUR_PLATFORM  != US_D_PLATFORM_CVADAS_HD)
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_CRC_MISMATCH_IN_OTP,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_DSP_Config_register_mismatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_CPU_Config_register_mismatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_NOISE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_Vref_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_VREF_OTP_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_VDDD_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_WD_COUNTER_DESYNC,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_WD_CLOCK_FAIL,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_CRC_BLOCK_CFG1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_CRC_BLOCK_CFG2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_CRC_BLOCK_MFG1,  
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_CRC_BLOCK_MFG2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_CRC_OP_MODE1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_CRC_OP_MODE2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_FLG_SIGNAL_PATH_FAILURE,
#endif
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_SYNCHRONISATION_COUNTER_ERROR_DETECTED,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR2_RECEIVED_COMMAND_INVALID,
	   ldef_ErrorMgr_Error_SENSOR2_USS_Sensor_Blockage
	},
	{   /* Sensor 3  error number */
	   ldef_ErrorMgr_Error_SENSOR3_OpenCkt_Fault,
       ldef_ErrorMgr_Error_SENSOR3_USS_Power_Lost_Fault,
	   ldef_ErrorMgr_Error_SENSOR3_USS_SWFirmWr_MisMatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_Temparature_out_of_range_error,   			
       ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_SNR_OPMODE_ERROR,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_DRV1_FAILURE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_DRV2_FAILURE_DURING_BURST, 
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_DRVS_FAILURE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_BURST_ABORT_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_RING_COMPARATOR_ZERO,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_GET_RING_FREQUENCY_FAILURE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_GET_DRV_FREQUENCY_FAILURE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_SRAM_Parity_error,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_CRC_MISTMATCH_IN_EEPROM_A1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_CRC_MISTMATCH_IN_EEPROM_A2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_ADA_MEASURE_TIMEOUT,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_PROGRAM_EEPROM,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_VTANK_overvoltage_burst_status_failure,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_VTANK_OVERVOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_VTANK_UNDERVOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_VSUP_OVER_VOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_VSUP_UNDER_VOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_BAD_RING_TIME,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_SNR_SETUP_SENSOR_FAIL,
#if(US_D_CUR_PLATFORM  != US_D_PLATFORM_CVADAS_HD)
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_CRC_MISMATCH_IN_OTP,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_DSP_Config_register_mismatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_CPU_Config_register_mismatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_NOISE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_Vref_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_VREF_OTP_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_VDDD_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_WD_COUNTER_DESYNC,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_WD_CLOCK_FAIL,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_CRC_BLOCK_CFG1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_CRC_BLOCK_CFG2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_CRC_BLOCK_MFG1,  
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_CRC_BLOCK_MFG2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_CRC_OP_MODE1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_CRC_OP_MODE2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_FLG_SIGNAL_PATH_FAILURE,
#endif
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_SYNCHRONISATION_COUNTER_ERROR_DETECTED,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR3_RECEIVED_COMMAND_INVALID,
	   ldef_ErrorMgr_Error_SENSOR3_USS_Sensor_Blockage
	},
	{   /* Sensor 4  error number */
	   ldef_ErrorMgr_Error_SENSOR4_OpenCkt_Fault,
       ldef_ErrorMgr_Error_SENSOR4_USS_Power_Lost_Fault,
	   ldef_ErrorMgr_Error_SENSOR4_USS_SWFirmWr_MisMatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_Temparature_out_of_range_error,   			
       ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_SNR_OPMODE_ERROR,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_DRV1_FAILURE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_DRV2_FAILURE_DURING_BURST, 
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_DRVS_FAILURE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_BURST_ABORT_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_RING_COMPARATOR_ZERO,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_GET_RING_FREQUENCY_FAILURE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_GET_DRV_FREQUENCY_FAILURE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_SRAM_Parity_error,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_CRC_MISTMATCH_IN_EEPROM_A1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_CRC_MISTMATCH_IN_EEPROM_A2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_ADA_MEASURE_TIMEOUT,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_PROGRAM_EEPROM,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_VTANK_overvoltage_burst_status_failure,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_VTANK_OVERVOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_VTANK_UNDERVOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_VSUP_OVER_VOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_VSUP_UNDER_VOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_BAD_RING_TIME,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_SNR_SETUP_SENSOR_FAIL,
#if(US_D_CUR_PLATFORM  != US_D_PLATFORM_CVADAS_HD)
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_CRC_MISMATCH_IN_OTP,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_DSP_Config_register_mismatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_CPU_Config_register_mismatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_NOISE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_Vref_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_VREF_OTP_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_VDDD_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_WD_COUNTER_DESYNC,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_WD_CLOCK_FAIL,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_CRC_BLOCK_CFG1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_CRC_BLOCK_CFG2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_CRC_BLOCK_MFG1,  
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_CRC_BLOCK_MFG2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_CRC_OP_MODE1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_CRC_OP_MODE2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_FLG_SIGNAL_PATH_FAILURE,
#endif
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_SYNCHRONISATION_COUNTER_ERROR_DETECTED,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR4_RECEIVED_COMMAND_INVALID,
	   ldef_ErrorMgr_Error_SENSOR4_USS_Sensor_Blockage
	},
	{   /* Sensor 5  error number */
	   ldef_ErrorMgr_Error_SENSOR5_OpenCkt_Fault,
       ldef_ErrorMgr_Error_SENSOR5_USS_Power_Lost_Fault,
	   ldef_ErrorMgr_Error_SENSOR5_USS_SWFirmWr_MisMatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_Temparature_out_of_range_error,   			
       ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_SNR_OPMODE_ERROR,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_DRV1_FAILURE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_DRV2_FAILURE_DURING_BURST, 
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_DRVS_FAILURE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_BURST_ABORT_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_RING_COMPARATOR_ZERO,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_GET_RING_FREQUENCY_FAILURE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_GET_DRV_FREQUENCY_FAILURE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_SRAM_Parity_error,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_CRC_MISTMATCH_IN_EEPROM_A1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_CRC_MISTMATCH_IN_EEPROM_A2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_ADA_MEASURE_TIMEOUT,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_PROGRAM_EEPROM,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_VTANK_overvoltage_burst_status_failure,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_VTANK_OVERVOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_VTANK_UNDERVOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_VSUP_OVER_VOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_VSUP_UNDER_VOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_BAD_RING_TIME,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_SNR_SETUP_SENSOR_FAIL,
#if(US_D_CUR_PLATFORM  != US_D_PLATFORM_CVADAS_HD)
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_CRC_MISMATCH_IN_OTP,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_DSP_Config_register_mismatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_CPU_Config_register_mismatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_NOISE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_Vref_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_VREF_OTP_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_VDDD_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_WD_COUNTER_DESYNC,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_WD_CLOCK_FAIL,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_CRC_BLOCK_CFG1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_CRC_BLOCK_CFG2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_CRC_BLOCK_MFG1,  
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_CRC_BLOCK_MFG2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_CRC_OP_MODE1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_CRC_OP_MODE2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_FLG_SIGNAL_PATH_FAILURE,
#endif
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_SYNCHRONISATION_COUNTER_ERROR_DETECTED,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR5_RECEIVED_COMMAND_INVALID,
	   ldef_ErrorMgr_Error_SENSOR5_USS_Sensor_Blockage
	},
	{   /* Sensor 6  error number */
	   ldef_ErrorMgr_Error_SENSOR6_OpenCkt_Fault,
       ldef_ErrorMgr_Error_SENSOR6_USS_Power_Lost_Fault,
	   ldef_ErrorMgr_Error_SENSOR6_USS_SWFirmWr_MisMatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_Temparature_out_of_range_error,   			
       ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_SNR_OPMODE_ERROR,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_DRV1_FAILURE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_DRV2_FAILURE_DURING_BURST, 
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_DRVS_FAILURE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_BURST_ABORT_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_RING_COMPARATOR_ZERO,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_GET_RING_FREQUENCY_FAILURE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_GET_DRV_FREQUENCY_FAILURE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_SRAM_Parity_error,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_CRC_MISTMATCH_IN_EEPROM_A1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_CRC_MISTMATCH_IN_EEPROM_A2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_ADA_MEASURE_TIMEOUT,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_PROGRAM_EEPROM,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_VTANK_overvoltage_burst_status_failure,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_VTANK_OVERVOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_VTANK_UNDERVOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_VSUP_OVER_VOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_VSUP_UNDER_VOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_BAD_RING_TIME,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_SNR_SETUP_SENSOR_FAIL,
#if(US_D_CUR_PLATFORM  != US_D_PLATFORM_CVADAS_HD)
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_CRC_MISMATCH_IN_OTP,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_DSP_Config_register_mismatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_CPU_Config_register_mismatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_NOISE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_Vref_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_VREF_OTP_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_VDDD_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_WD_COUNTER_DESYNC,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_WD_CLOCK_FAIL,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_CRC_BLOCK_CFG1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_CRC_BLOCK_CFG2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_CRC_BLOCK_MFG1,  
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_CRC_BLOCK_MFG2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_CRC_OP_MODE1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_CRC_OP_MODE2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_FLG_SIGNAL_PATH_FAILURE,
#endif
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_SYNCHRONISATION_COUNTER_ERROR_DETECTED,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR6_RECEIVED_COMMAND_INVALID,
	   ldef_ErrorMgr_Error_SENSOR6_USS_Sensor_Blockage
	},
	{   /* Sensor 7  error number */
	   ldef_ErrorMgr_Error_SENSOR7_OpenCkt_Fault,
       ldef_ErrorMgr_Error_SENSOR7_USS_Power_Lost_Fault,
	   ldef_ErrorMgr_Error_SENSOR7_USS_SWFirmWr_MisMatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_Temparature_out_of_range_error,   			
       ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_SNR_OPMODE_ERROR,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_DRV1_FAILURE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_DRV2_FAILURE_DURING_BURST, 
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_DRVS_FAILURE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_BURST_ABORT_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_RING_COMPARATOR_ZERO,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_GET_RING_FREQUENCY_FAILURE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_GET_DRV_FREQUENCY_FAILURE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_SRAM_Parity_error,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_CRC_MISTMATCH_IN_EEPROM_A1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_CRC_MISTMATCH_IN_EEPROM_A2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_ADA_MEASURE_TIMEOUT,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_PROGRAM_EEPROM,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_VTANK_overvoltage_burst_status_failure,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_VTANK_OVERVOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_VTANK_UNDERVOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_VSUP_OVER_VOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_VSUP_UNDER_VOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_BAD_RING_TIME,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_SNR_SETUP_SENSOR_FAIL,
#if(US_D_CUR_PLATFORM  != US_D_PLATFORM_CVADAS_HD)
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_CRC_MISMATCH_IN_OTP,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_DSP_Config_register_mismatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_CPU_Config_register_mismatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_NOISE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_Vref_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_VREF_OTP_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_VDDD_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_WD_COUNTER_DESYNC,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_WD_CLOCK_FAIL,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_CRC_BLOCK_CFG1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_CRC_BLOCK_CFG2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_CRC_BLOCK_MFG1,  
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_CRC_BLOCK_MFG2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_CRC_OP_MODE1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_CRC_OP_MODE2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_FLG_SIGNAL_PATH_FAILURE,
#endif
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_SYNCHRONISATION_COUNTER_ERROR_DETECTED,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR7_RECEIVED_COMMAND_INVALID,
	   ldef_ErrorMgr_Error_SENSOR7_USS_Sensor_Blockage
	},
	{   /* Sensor 8  error number */
	   ldef_ErrorMgr_Error_SENSOR8_OpenCkt_Fault,
       ldef_ErrorMgr_Error_SENSOR8_USS_Power_Lost_Fault,
	   ldef_ErrorMgr_Error_SENSOR8_USS_SWFirmWr_MisMatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_Temparature_out_of_range_error,   			
       ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_SNR_OPMODE_ERROR,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_DRV1_FAILURE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_DRV2_FAILURE_DURING_BURST, 
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_DRVS_FAILURE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_BURST_ABORT_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_RING_COMPARATOR_ZERO,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_GET_RING_FREQUENCY_FAILURE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_GET_DRV_FREQUENCY_FAILURE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_SRAM_Parity_error,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_CRC_MISTMATCH_IN_EEPROM_A1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_CRC_MISTMATCH_IN_EEPROM_A2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_ADA_MEASURE_TIMEOUT,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_PROGRAM_EEPROM,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_VTANK_overvoltage_burst_status_failure,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_VTANK_OVERVOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_VTANK_UNDERVOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_VSUP_OVER_VOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_VSUP_UNDER_VOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_BAD_RING_TIME,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_SNR_SETUP_SENSOR_FAIL,
#if(US_D_CUR_PLATFORM  != US_D_PLATFORM_CVADAS_HD)
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_CRC_MISMATCH_IN_OTP,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_DSP_Config_register_mismatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_CPU_Config_register_mismatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_NOISE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_Vref_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_VREF_OTP_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_VDDD_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_WD_COUNTER_DESYNC,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_WD_CLOCK_FAIL,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_CRC_BLOCK_CFG1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_CRC_BLOCK_CFG2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_CRC_BLOCK_MFG1,  
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_CRC_BLOCK_MFG2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_CRC_OP_MODE1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_CRC_OP_MODE2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_FLG_SIGNAL_PATH_FAILURE,
#endif
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_SYNCHRONISATION_COUNTER_ERROR_DETECTED,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR8_RECEIVED_COMMAND_INVALID,
	   ldef_ErrorMgr_Error_SENSOR8_USS_Sensor_Blockage
	},
	{   /* Sensor 9  error number */
	   ldef_ErrorMgr_Error_SENSOR9_OpenCkt_Fault,
       ldef_ErrorMgr_Error_SENSOR9_USS_Power_Lost_Fault,
	   ldef_ErrorMgr_Error_SENSOR9_USS_SWFirmWr_MisMatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_Temparature_out_of_range_error,   			
       ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_SNR_OPMODE_ERROR,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_DRV1_FAILURE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_DRV2_FAILURE_DURING_BURST, 
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_DRVS_FAILURE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_BURST_ABORT_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_RING_COMPARATOR_ZERO,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_GET_RING_FREQUENCY_FAILURE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_GET_DRV_FREQUENCY_FAILURE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_SRAM_Parity_error,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_CRC_MISTMATCH_IN_EEPROM_A1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_CRC_MISTMATCH_IN_EEPROM_A2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_ADA_MEASURE_TIMEOUT,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_PROGRAM_EEPROM,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_VTANK_overvoltage_burst_status_failure,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_VTANK_OVERVOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_VTANK_UNDERVOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_VSUP_OVER_VOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_VSUP_UNDER_VOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_BAD_RING_TIME,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_SNR_SETUP_SENSOR_FAIL,
#if(US_D_CUR_PLATFORM  != US_D_PLATFORM_CVADAS_HD)
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_CRC_MISMATCH_IN_OTP,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_DSP_Config_register_mismatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_CPU_Config_register_mismatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_NOISE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_Vref_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_VREF_OTP_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_VDDD_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_WD_COUNTER_DESYNC,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_WD_CLOCK_FAIL,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_CRC_BLOCK_CFG1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_CRC_BLOCK_CFG2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_CRC_BLOCK_MFG1,  
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_CRC_BLOCK_MFG2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_CRC_OP_MODE1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_CRC_OP_MODE2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_FLG_SIGNAL_PATH_FAILURE,
#endif
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_SYNCHRONISATION_COUNTER_ERROR_DETECTED,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR9_RECEIVED_COMMAND_INVALID,
	   ldef_ErrorMgr_Error_SENSOR9_USS_Sensor_Blockage
	},
	{   /* Sensor 10  error number */
	   ldef_ErrorMgr_Error_SENSOR10_OpenCkt_Fault,
       ldef_ErrorMgr_Error_SENSOR10_USS_Power_Lost_Fault,
	   ldef_ErrorMgr_Error_SENSOR10_USS_SWFirmWr_MisMatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_Temparature_out_of_range_error,   			
       ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_SNR_OPMODE_ERROR,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_DRV1_FAILURE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_DRV2_FAILURE_DURING_BURST, 
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_DRVS_FAILURE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_BURST_ABORT_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_RING_COMPARATOR_ZERO,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_GET_RING_FREQUENCY_FAILURE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_GET_DRV_FREQUENCY_FAILURE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_SRAM_Parity_error,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_CRC_MISTMATCH_IN_EEPROM_A1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_CRC_MISTMATCH_IN_EEPROM_A2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_ADA_MEASURE_TIMEOUT,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_PROGRAM_EEPROM,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_VTANK_overvoltage_burst_status_failure,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_VTANK_OVERVOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_VTANK_UNDERVOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_VSUP_OVER_VOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_VSUP_UNDER_VOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_BAD_RING_TIME,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_SNR_SETUP_SENSOR_FAIL,
#if(US_D_CUR_PLATFORM  != US_D_PLATFORM_CVADAS_HD)
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_CRC_MISMATCH_IN_OTP,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_DSP_Config_register_mismatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_CPU_Config_register_mismatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_NOISE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_Vref_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_VREF_OTP_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_VDDD_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_WD_COUNTER_DESYNC,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_WD_CLOCK_FAIL,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_CRC_BLOCK_CFG1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_CRC_BLOCK_CFG2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_CRC_BLOCK_MFG1,  
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_CRC_BLOCK_MFG2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_CRC_OP_MODE1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_CRC_OP_MODE2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_FLG_SIGNAL_PATH_FAILURE,
#endif
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_SYNCHRONISATION_COUNTER_ERROR_DETECTED,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR10_RECEIVED_COMMAND_INVALID,
	   ldef_ErrorMgr_Error_SENSOR10_USS_Sensor_Blockage
	},
	{   /* Sensor 11  error number */
	   ldef_ErrorMgr_Error_SENSOR11_OpenCkt_Fault,
       ldef_ErrorMgr_Error_SENSOR11_USS_Power_Lost_Fault,
	   ldef_ErrorMgr_Error_SENSOR11_USS_SWFirmWr_MisMatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_Temparature_out_of_range_error,   			
       ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_SNR_OPMODE_ERROR,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_DRV1_FAILURE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_DRV2_FAILURE_DURING_BURST, 
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_DRVS_FAILURE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_BURST_ABORT_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_RING_COMPARATOR_ZERO,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_GET_RING_FREQUENCY_FAILURE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_GET_DRV_FREQUENCY_FAILURE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_SRAM_Parity_error,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_CRC_MISTMATCH_IN_EEPROM_A1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_CRC_MISTMATCH_IN_EEPROM_A2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_ADA_MEASURE_TIMEOUT,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_PROGRAM_EEPROM,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_VTANK_overvoltage_burst_status_failure,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_VTANK_OVERVOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_VTANK_UNDERVOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_VSUP_OVER_VOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_VSUP_UNDER_VOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_BAD_RING_TIME,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_SNR_SETUP_SENSOR_FAIL,
#if(US_D_CUR_PLATFORM  != US_D_PLATFORM_CVADAS_HD)
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_CRC_MISMATCH_IN_OTP,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_DSP_Config_register_mismatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_CPU_Config_register_mismatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_NOISE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_Vref_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_VREF_OTP_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_VDDD_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_WD_COUNTER_DESYNC,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_WD_CLOCK_FAIL,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_CRC_BLOCK_CFG1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_CRC_BLOCK_CFG2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_CRC_BLOCK_MFG1,  
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_CRC_BLOCK_MFG2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_CRC_OP_MODE1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_CRC_OP_MODE2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_FLG_SIGNAL_PATH_FAILURE,
#endif
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_SYNCHRONISATION_COUNTER_ERROR_DETECTED,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR11_RECEIVED_COMMAND_INVALID,
	   ldef_ErrorMgr_Error_SENSOR11_USS_Sensor_Blockage
	},
	{   /* Sensor 12  error number */
	   ldef_ErrorMgr_Error_SENSOR12_OpenCkt_Fault,
       ldef_ErrorMgr_Error_SENSOR12_USS_Power_Lost_Fault,
	   ldef_ErrorMgr_Error_SENSOR12_USS_SWFirmWr_MisMatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_Temparature_out_of_range_error,   			
       ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_SNR_OPMODE_ERROR,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_DRV1_FAILURE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_DRV2_FAILURE_DURING_BURST, 
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_DRVS_FAILURE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_BURST_ABORT_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_RING_COMPARATOR_ZERO,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_GET_RING_FREQUENCY_FAILURE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_GET_DRV_FREQUENCY_FAILURE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_SRAM_Parity_error,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_CRC_MISTMATCH_IN_EEPROM_A1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_CRC_MISTMATCH_IN_EEPROM_A2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_ADA_MEASURE_TIMEOUT,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_PROGRAM_EEPROM,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_VTANK_overvoltage_burst_status_failure,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_VTANK_OVERVOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_VTANK_UNDERVOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_VSUP_OVER_VOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_VSUP_UNDER_VOLTAGE,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_BAD_RING_TIME,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_SNR_SETUP_SENSOR_FAIL,
#if(US_D_CUR_PLATFORM  != US_D_PLATFORM_CVADAS_HD)
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_CRC_MISMATCH_IN_OTP,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_DSP_Config_register_mismatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_CPU_Config_register_mismatch,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_NOISE_DURING_BURST,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_Vref_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_VREF_OTP_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_VDDD_out_of_range,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_WD_COUNTER_DESYNC,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_WD_CLOCK_FAIL,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_CRC_BLOCK_CFG1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_CRC_BLOCK_CFG2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_CRC_BLOCK_MFG1,  
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_CRC_BLOCK_MFG2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_CRC_OP_MODE1,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_CRC_OP_MODE2,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_FLG_SIGNAL_PATH_FAILURE,
#endif
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_SYNCHRONISATION_COUNTER_ERROR_DETECTED,
	   ldef_ErrorMgr_Error_SysIntFault_USS_SENSOR12_RECEIVED_COMMAND_INVALID,
	   ldef_ErrorMgr_Error_SENSOR12_USS_Sensor_Blockage
	},


};														
														
														
														
ldef_ErrorMgr_enErrorNo ECUErrMap[MAX_ECU_FLAGS]=
{
	ldef_ErrorMgr_Error_USS_M_F_short_to_GND,
	ldef_ErrorMgr_Error_USS_M_F_voltage_OOR_Low ,
	ldef_ErrorMgr_Error_USS_M_F_voltage_OOR_High,
	ldef_ErrorMgr_Error_USS_M_F_Short_to_Bat,
	ldef_ErrorMgr_Error_USS_M_R_short_to_GND,
	ldef_ErrorMgr_Error_USS_M_R_voltage_OOR_Low,
	ldef_ErrorMgr_Error_USS_M_R_voltage_OOR_High,
	ldef_ErrorMgr_Error_USS_M_R_Short_to_Bat,
	ldef_ErrorMgr_Error_USS_Cal_Data_Fault,
	ldef_ErrorMgr_Error_SysIntFault_MCU_USS_MASTER_internal_failure_VCCUV,
	ldef_ErrorMgr_Error_SysIntFault_MCU_USS_MASTER_INTB_pin_low_CLKREF_failure,
	ldef_ErrorMgr_Error_SysIntFault_MCU_USS_MASTER_DSI_Overtemperature_error,
	ldef_ErrorMgr_Error_SysIntFault_MCU_USS_MASTER_DSI_IRQ_STAT_CRC_ERR,
#if(US_D_CUR_PLATFORM  != US_D_PLATFORM_CVADAS_HD)
	ldef_ErrorMgr_Error_SysIntFault_MCU_USS_MASTER_ECU_SPI_DMA_ERR,
#endif
	ldef_ErrorMgr_Error_SysIntFault_MCU_USS_MASTER_ECU_CFG_SENSOR_ERR,
	ldef_ErrorMgr_Error_SysIntFault_MCU_USS_MASTER_ECU_GPIO_INT_INITIAL_ERR,
	ldef_ErrorMgr_Error_SysIntFault_MCU_USS_MASTER_ECU_PIN_INITIAL_ERR,
	ldef_ErrorMgr_Error_SysIntFault_MCU_USS_MASTER_ECU_DSI_CLOCK_INITIAL_ERR,
	/*ldef_ErrorMgr_Error_SysIntFault_MCU_USS_MASTER_ECU_DSI_REF_INITIAL_ERR,*/
	ldef_ErrorMgr_Error_SysIntFault_MCU_USS_MASTER_ECU_SPI_INITIAL_ERR,
	ldef_ErrorMgr_Error_SysIntFault_MCU_USS_MASTER_ECU_USS_POWER_ON_ERR,
	ldef_ErrorMgr_Error_SysIntFault_MCU_USS_MASTER_ECU_DSI_RFC_ERR,
	ldef_ErrorMgr_Error_SysIntFault_MCU_USS_MASTER_Front_OC_ERR,
	ldef_ErrorMgr_Error_SysIntFault_MCU_USS_MASTER_Front_DSI_Undervoltage_error,
	ldef_ErrorMgr_Error_SysIntFault_MCU_USS_MASTER_Rear_OC_ERR,
	ldef_ErrorMgr_Error_SysIntFault_MCU_USS_MASTER_Rear_DSI_Undervoltage_error,
	ldef_ErrorMgr_Error_SysIntFault_MCU_USS_MASTER_ECU_COMM_ERR,
	ldef_ErrorMgr_Error_SysIntFault_MCU_USS_MASTER_internal_failure_FSM_RESET,
	ldef_ErrorMgr_Error_SysIntFault_MCU_USS_MASTER_internal_failure_VDSIUV,
	ldef_ErrorMgr_Error_SysIntFault_MCU_USS_MASTER_DSI3_Safety_critical_registers_mismatch,
	ldef_ErrorMgr_Error_SysIntFault_MCU_USS_MASTER_internal_failure_RAM_BIST_failure 
};



