/*
*
* Copyright (c) 2019 Texas Instruments Incorporated
*
* All rights reserved not granted herein.
*
* Limited License.
*
* Texas Instruments Incorporated grants a world-wide, royalty-free, non-exclusive
* license under copyrights and patents it now or hereafter owns or controls to make,
* have made, use, import, offer to sell and sell ("Utilize") this software subject to the
* terms herein.  With respect to the foregoing patent license, such license is granted
* solely to the extent that any such patent is necessary to Utilize the software alone.
* The patent license shall not apply to any combinations which include this software,
* other than combinations with devices manufactured by or for TI ("TI Devices").
* No hardware patent is licensed hereunder.
*
* Redistributions must preserve existing copyright notices and reproduce this license
* (including the above copyright notice and the disclaimer and (if applicable) source
* code license limitations below) in the documentation and/or other materials provided
* with the distribution
*
* Redistribution and use in binary form, without modification, are permitted provided
* that the following conditions are met:
*
* *       No reverse engineering, decompilation, or disassembly of this software is
* permitted with respect to any software provided in binary form.
*
* *       any redistribution and use are licensed by TI for use only with TI Devices.
*
* *       Nothing shall obligate TI to provide you with source code for the software
* licensed and provided to you in object code.
*
* If software source code is provided to you, modification and redistribution of the
* source code are permitted provided that the following conditions are met:
*
* *       any redistribution and use of the source code, including any resulting derivative
* works, are licensed by TI for use only with TI Devices.
*
* *       any redistribution and use of any object code compiled from the source code
* and any resulting derivative works, are licensed by TI for use only with TI Devices.
*
* Neither the name of Texas Instruments Incorporated nor the names of its suppliers
*
* may be used to endorse or promote products derived from this software without
* specific prior written permission.
*
* DISCLAIMER.
*
* THIS SOFTWARE IS PROVIDED BY TI AND TI'S LICENSORS "AS IS" AND ANY EXPRESS
* OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
* OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
* IN NO EVENT SHALL TI AND TI'S LICENSORS BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
* BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
* DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
* OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
* OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
* OF THE POSSIBILITY OF SUCH DAMAGE.
*
*/
/***********************************************************************
    Project: 
    Date   : 2024-02-13 13:05:37

    This file is generated by EB Tresos
    Do not modify this file, otherwise the software may behave in
    unexpected way.

 ***********************************************************************/
/**
 *  \file     Dio_Cfg.h
 *
 *  \brief    This file contains generated pre compile configuration file
 *            for DIO MCAL driver
 *
 */

/**
 *  \defgroup MCAL_DIO_CFG DIO Configuration
 *
 *  This files defines DIO MCAL configuration structures
 *  @{
 */

#ifndef DIO_CFG_H_
#define DIO_CFG_H_

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */

#include "Dem.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ========================================================================== */
/*                           Macros & Typedefs                                */
/* ========================================================================== */
/** \brief DIO Driver Instance ID */
#define DIO_INSTANCE_ID                 ((uint8) 0U)

/**
 *  \name DIO service enable/diable defines
 *
 *  Pre-compile switches for enabling/disabling DIO MCAL APIs
 *  @{
 */
/** \brief Enable/Disable DEV error detection */
#define DIO_DEV_ERROR_DETECT            (STD_ON)

/** \brief Enable/Disable Dio_GetVersionInfo() */
#define DIO_VERSION_INFO_API            (STD_ON)

/** \brief Enable/Disable Dio_FlipChannel() */
#define DIO_FLIP_CHANNEL_API            (STD_ON)

/** \brief Enable/disable Dio register read back API */
#define DIO_REGISTER_READBACK_API       (STD_ON)
/* @} */

 /** \brief Max number of DIO ports */
#define DIO_ENABLED_PORT_MASK          (0U    | (1U << 0)\
 | (1U << 1)\
 | (1U << 7)\
)

/* Design : MCAL-5455, MCAL-5533 */
/**
 *  \name Symbolic name of DIO PORTs
 *
 *  This is symbolic name of DIO ports generated from configurator
 *  These defines map to physical GPIO register numbers.
 *  @{
 */
/** \brief Symbolic name for GPIO REG #0 */
#define DioConf_DioPort_DioPort_WKUP_GPIO0_BANK0 ((Dio_PortType) 0U)
/** \brief Symbolic name for GPIO REG #1 */
#define DioConf_DioPort_DioPort_WKUP_GPIO0_BANK23 ((Dio_PortType) 1U)
/** \brief Symbolic name for GPIO REG #7 */
#define DioConf_DioPort_DioPort_GPIO0_BANK23 ((Dio_PortType) 7U)
/* @} */


/* Design :  MCAL-5457, MCAL-5490, MCAL-5487, MCAL-5436*/
/**
 *  \name Symbolic name of DIO Channels
 *
 *  This is symbolic name of DIO channels generated from configurator
 *  These defines map to GPIO register channels
 *  The channel numbers are mapped as
 *  WKUP_GPIO0_B01: Channel 0  - Channel 31
 *  WKUP_GPIO0_B23: Channel 32 - Channel 63
 *  WKUP_GPIO0_B45: Channel 64 - Channel 83
 *  WKUP_GPIO1_B01: Channel 144 - Channel 175
 *  WKUP_GPIO1_B23: Channel 176 - Channel 207
 *  WKUP_GPIO1_B45: Channel 208 - Channel 227
 *  GPIO0_B01: Channel 288 - Channel 319
 *  GPIO0_B23: Channel 320 - Channel 351
 *  GPIO0_B45: Channel 352  - Channel 383
 *  GPIO0_B67: Channel 384 - Channel 415
 *  GPIO1_B01: Channel 432 - Channel 463
 *  GPIO1_B23: Channel 464 - Channel 467
 *  GPIO2_B01: Channel 576 - Channel 607
 *  GPIO2_B23: Channel 608 - Channel 639
 *  GPIO2_B45: Channel 640 - Channel 671
 *  GPIO2_B67: Channel 672 - Channel 703
 *  GPIO3_B01: Channel 720 - Channel 751
 *  GPIO3_B23: Channel 752 - Channel 755
 *  GPIO4_B01: Channel 864 - Channel 895
 *  GPIO4_B23: Channel 896 - Channel 927
 *  GPIO4_B45: Channel 928 - Channel 959
 *  GPIO4_B67: Channel 960 - Channel 991
 *  GPIO5_B01: Channel 1008 - Channel 1039
 *  GPIO5_B23: Channel 1040 - Channel 1043
 *  GPIO6_B01: Channel 1152 - Channel 1183
 *  GPIO6_B23: Channel 1184 - Channel 1215
 *  GPIO6_B45: Channel 1216 - Channel 1247
 *  GPIO6_B67: Channel 1248 - Channel 1279
 *  GPIO7_B01: Channel 1296 - Channel 1327
 *  GPIO7_B23: Channel 1328 - Channel 1331
 *  @{
 */








/** \brief Symbolic name for GPIO channel #15 DioChannel_pinEN */

#define DioConf_DioChannel_DioChannel_pinEN ((Dio_ChannelType) 15U)
/** \brief Shorter Symbolic name for GPIO channel #15 DioChannel_pinEN */
#define DioChannel_pinEN DioConf_DioChannel_DioChannel_pinEN

/** \brief Symbolic name for GPIO channel #1 DioChannel_PinSTB */

#define DioConf_DioChannel_DioChannel_PinSTB ((Dio_ChannelType) 1U)
/** \brief Shorter Symbolic name for GPIO channel #1 DioChannel_PinSTB */
#define DioChannel_PinSTB DioConf_DioChannel_DioChannel_PinSTB

/** \brief Symbolic name for GPIO channel #6 DioChannel_PinERR */

#define DioConf_DioChannel_DioChannel_PinERR ((Dio_ChannelType) 6U)
/** \brief Shorter Symbolic name for GPIO channel #6 DioChannel_PinERR */
#define DioChannel_PinERR DioConf_DioChannel_DioChannel_PinERR

/** \brief Symbolic name for GPIO channel #31 DioChannel_MCU_LED */

#define DioConf_DioChannel_DioChannel_MCU_LED ((Dio_ChannelType) 31U)
/** \brief Shorter Symbolic name for GPIO channel #31 DioChannel_MCU_LED */
#define DioChannel_MCU_LED DioConf_DioChannel_DioChannel_MCU_LED

/** \brief Symbolic name for GPIO channel #43 WKUP_GPIO0_B23_Ch0 */

#define DioConf_DioChannel_WKUP_GPIO0_B23_Ch0 ((Dio_ChannelType) 43U)
/** \brief Shorter Symbolic name for GPIO channel #43 WKUP_GPIO0_B23_Ch0 */
#define WKUP_GPIO0_B23_Ch0 DioConf_DioChannel_WKUP_GPIO0_B23_Ch0

/** \brief Symbolic name for GPIO channel #44 WKUP_GPIO0_B23_Ch1 */

#define DioConf_DioChannel_WKUP_GPIO0_B23_Ch1 ((Dio_ChannelType) 44U)
/** \brief Shorter Symbolic name for GPIO channel #44 WKUP_GPIO0_B23_Ch1 */
#define WKUP_GPIO0_B23_Ch1 DioConf_DioChannel_WKUP_GPIO0_B23_Ch1

/** \brief Symbolic name for GPIO channel #53 WKUP_GPIO0_B23_Ch10 */

#define DioConf_DioChannel_WKUP_GPIO0_B23_Ch10 ((Dio_ChannelType) 53U)
/** \brief Shorter Symbolic name for GPIO channel #53 WKUP_GPIO0_B23_Ch10 */
#define WKUP_GPIO0_B23_Ch10 DioConf_DioChannel_WKUP_GPIO0_B23_Ch10

/** \brief Symbolic name for GPIO channel #54 WKUP_GPIO0_B23_Ch11 */

#define DioConf_DioChannel_WKUP_GPIO0_B23_Ch11 ((Dio_ChannelType) 54U)
/** \brief Shorter Symbolic name for GPIO channel #54 WKUP_GPIO0_B23_Ch11 */
#define WKUP_GPIO0_B23_Ch11 DioConf_DioChannel_WKUP_GPIO0_B23_Ch11

/** \brief Symbolic name for GPIO channel #55 WKUP_GPIO0_B23_Ch12 */

#define DioConf_DioChannel_WKUP_GPIO0_B23_Ch12 ((Dio_ChannelType) 55U)
/** \brief Shorter Symbolic name for GPIO channel #55 WKUP_GPIO0_B23_Ch12 */
#define WKUP_GPIO0_B23_Ch12 DioConf_DioChannel_WKUP_GPIO0_B23_Ch12

/** \brief Symbolic name for GPIO channel #56 pinFDCAN14_Enable */

#define DioConf_DioChannel_pinFDCAN14_Enable ((Dio_ChannelType) 56U)
/** \brief Shorter Symbolic name for GPIO channel #56 pinFDCAN14_Enable */
#define pinFDCAN14_Enable DioConf_DioChannel_pinFDCAN14_Enable

/** \brief Symbolic name for GPIO channel #57 WKUP_GPIO0_B23_Ch14 */

#define DioConf_DioChannel_WKUP_GPIO0_B23_Ch14 ((Dio_ChannelType) 57U)
/** \brief Shorter Symbolic name for GPIO channel #57 WKUP_GPIO0_B23_Ch14 */
#define WKUP_GPIO0_B23_Ch14 DioConf_DioChannel_WKUP_GPIO0_B23_Ch14

/** \brief Symbolic name for GPIO channel #58
  *		   Can Transceiver Enable MCU MCAN0 */

#define DioConf_DioChannel_WKUP_GPIO0_B23_Ch15 ((Dio_ChannelType) 58U)
/** \brief Shorter Symbolic name for GPIO channel #58 WKUP_GPIO0_B23_Ch15 */
#define WKUP_GPIO0_B23_Ch15 DioConf_DioChannel_WKUP_GPIO0_B23_Ch15

/** \brief Symbolic name for GPIO channel #59 WKUP_GPIO0_B23_Ch16 */

#define DioConf_DioChannel_WKUP_GPIO0_B23_Ch16 ((Dio_ChannelType) 59U)
/** \brief Shorter Symbolic name for GPIO channel #59 WKUP_GPIO0_B23_Ch16 */
#define WKUP_GPIO0_B23_Ch16 DioConf_DioChannel_WKUP_GPIO0_B23_Ch16

/** \brief Symbolic name for GPIO channel #61 DioChannel_PINRXD */

#define DioConf_DioChannel_DioChannel_PINRXD ((Dio_ChannelType) 61U)
/** \brief Shorter Symbolic name for GPIO channel #61 DioChannel_PINRXD */
#define DioChannel_PINRXD DioConf_DioChannel_DioChannel_PINRXD

/** \brief Symbolic name for GPIO channel #45 WKUP_GPIO0_B23_Ch2 */

#define DioConf_DioChannel_WKUP_GPIO0_B23_Ch2 ((Dio_ChannelType) 45U)
/** \brief Shorter Symbolic name for GPIO channel #45 WKUP_GPIO0_B23_Ch2 */
#define WKUP_GPIO0_B23_Ch2 DioConf_DioChannel_WKUP_GPIO0_B23_Ch2

/** \brief Symbolic name for GPIO channel #46 WKUP_GPIO0_B23_Ch3 */

#define DioConf_DioChannel_WKUP_GPIO0_B23_Ch3 ((Dio_ChannelType) 46U)
/** \brief Shorter Symbolic name for GPIO channel #46 WKUP_GPIO0_B23_Ch3 */
#define WKUP_GPIO0_B23_Ch3 DioConf_DioChannel_WKUP_GPIO0_B23_Ch3

/** \brief Symbolic name for GPIO channel #47 WKUP_GPIO0_B23_Ch4 */

#define DioConf_DioChannel_WKUP_GPIO0_B23_Ch4 ((Dio_ChannelType) 47U)
/** \brief Shorter Symbolic name for GPIO channel #47 WKUP_GPIO0_B23_Ch4 */
#define WKUP_GPIO0_B23_Ch4 DioConf_DioChannel_WKUP_GPIO0_B23_Ch4

/** \brief Symbolic name for GPIO channel #48 WKUP_GPIO0_B23_Ch5 */

#define DioConf_DioChannel_WKUP_GPIO0_B23_Ch5 ((Dio_ChannelType) 48U)
/** \brief Shorter Symbolic name for GPIO channel #48 WKUP_GPIO0_B23_Ch5 */
#define WKUP_GPIO0_B23_Ch5 DioConf_DioChannel_WKUP_GPIO0_B23_Ch5

/** \brief Symbolic name for GPIO channel #49 WKUP_GPIO0_B23_Ch6 */

#define DioConf_DioChannel_WKUP_GPIO0_B23_Ch6 ((Dio_ChannelType) 49U)
/** \brief Shorter Symbolic name for GPIO channel #49 WKUP_GPIO0_B23_Ch6 */
#define WKUP_GPIO0_B23_Ch6 DioConf_DioChannel_WKUP_GPIO0_B23_Ch6

/** \brief Symbolic name for GPIO channel #50 WKUP_GPIO0_B23_Ch7 */

#define DioConf_DioChannel_WKUP_GPIO0_B23_Ch7 ((Dio_ChannelType) 50U)
/** \brief Shorter Symbolic name for GPIO channel #50 WKUP_GPIO0_B23_Ch7 */
#define WKUP_GPIO0_B23_Ch7 DioConf_DioChannel_WKUP_GPIO0_B23_Ch7

/** \brief Symbolic name for GPIO channel #51 WKUP_GPIO0_B23_Ch8 */

#define DioConf_DioChannel_WKUP_GPIO0_B23_Ch8 ((Dio_ChannelType) 51U)
/** \brief Shorter Symbolic name for GPIO channel #51 WKUP_GPIO0_B23_Ch8 */
#define WKUP_GPIO0_B23_Ch8 DioConf_DioChannel_WKUP_GPIO0_B23_Ch8

/** \brief Symbolic name for GPIO channel #52 WKUP_GPIO0_B23_Ch9 */

#define DioConf_DioChannel_WKUP_GPIO0_B23_Ch9 ((Dio_ChannelType) 52U)
/** \brief Shorter Symbolic name for GPIO channel #52 WKUP_GPIO0_B23_Ch9 */
#define WKUP_GPIO0_B23_Ch9 DioConf_DioChannel_WKUP_GPIO0_B23_Ch9

/** \brief Symbolic name for GPIO channel #346 DioChannel_USSDselPIN */

#define DioConf_DioChannel_DioChannel_USSDselPIN ((Dio_ChannelType) 346U)
/** \brief Shorter Symbolic name for GPIO channel #346 DioChannel_USSDselPIN */
#define DioChannel_USSDselPIN DioConf_DioChannel_DioChannel_USSDselPIN
/* @} */


/* Design : MCAL-5457, MCAL-5455*/
/**
 *  \name Symbolic name of DIO Channel Groups
 *
 *  This is the symbolic name of DIO channel groups generated from configurator
 *  The definition of the channel groups is present in the generated
 *  Dio_Lcfg.c file. The other modules will invoke the Dio_channelGroup APIs
 *  using the symbolic name defines
 *
 *  @{
 */
#define DioConf_DioChannelGroup_WKUP_GPIO0_B0_PTR ((const Dio_ChannelGroupType *)(DioConfig_DioPort_WKUP_GPIO0_BANK0_ChannelGroupRef[0]))
#define WKUP_GPIO0_B0_PTR DioConf_DioChannelGroup_WKUP_GPIO0_B0_PTR
#define DioConf_DioChannelGroup_WKUP_GPIO0_B23_PTR ((const Dio_ChannelGroupType *)(DioConfig_DioPort_WKUP_GPIO0_BANK23_ChannelGroupRef[0]))
#define WKUP_GPIO0_B23_PTR DioConf_DioChannelGroup_WKUP_GPIO0_B23_PTR
#define DioConf_DioChannelGroup_GPIO0_B23_PTR ((const Dio_ChannelGroupType *)(DioConfig_DioPort_GPIO0_BANK23_ChannelGroupRef[0]))
#define GPIO0_B23_PTR DioConf_DioChannelGroup_GPIO0_B23_PTR
/* @} */

/**
 *  \name DIO DEM Error codes to report
 *
 *  Pre-compile switches for enabling/disabling DEM events
 *  @{
 */
#define DemConf_DemEventParameter_DIO_DEM_NO_EVENT (0xFFFFU)
#define DIO_DEM_NO_EVENT DemConf_DemEventParameter_DIO_DEM_NO_EVENT

/* DIO IO check Dem IDs */
#ifndef DIO_WRITE_CHANNEL_EVENT_ID
    #define DIO_WRITE_CHANNEL_EVENT_ID  (DIO_DEM_NO_EVENT)
#endif
#ifndef DIO_WRITE_PORT_EVENT_ID
    #define DIO_WRITE_PORT_EVENT_ID     (DIO_DEM_NO_EVENT)
#endif

/* @} */

/**
 *  \brief Total HW units or Instances
 *    - used for array allocation. This should be +1 of the max unit number
 *   This is dependent on the SoC and not recommended to be modified
 */
#define DIO_HW_UNIT_CNT                 (6U)

/* GPIO Instance Ids */

/* GPIO Instance Id: WAKEUP Domain 0*/
#define DIO_INSTANCE_0                            (0U)
/* GPIO Instance Id: WAKEUP Domain 1*/
#define DIO_INSTANCE_1                            (1U)
/* GPIO Instance Id: Main Domain 0*/
#define DIO_INSTANCE_2                            (2U)
/* GPIO Instance Id: Main Domain 1*/
#define DIO_INSTANCE_3                            (3U)
/* GPIO Instance Id: Main Domain 2*/
#define DIO_INSTANCE_4                            (4U)
/* GPIO Instance Id: Main Domain 3*/
#define DIO_INSTANCE_5                            (5U)
/* GPIO Instance Id: Main Domain 4*/

/* GPIO Instance Id: Max */
#define DIO_MAX_INSTANCE_ID                       (DIO_INSTANCE_5)

/* GPIO Instance Limits */
/* GPIO Instance Limits: WAKEUP Domain 0*/
#define DIO_MAX_PORT_ID_INSTANCE_0                (3U)
/* GPIO Instance Limits: WAKEUP Domain 1*/
#define DIO_MAX_PORT_ID_INSTANCE_1                (6U)
/* GPIO Instance Limits: Main Domain 0*/
#define DIO_MAX_PORT_ID_INSTANCE_2                (9U)
/* GPIO Instance Limits: Main Domain 1*/
#define DIO_MAX_PORT_ID_INSTANCE_3                (12U)
/* GPIO Instance Limits: Main Domain 2*/
#define DIO_MAX_PORT_ID_INSTANCE_4                (15U)
/* GPIO Instance Limits: Main Domain 3*/
#define DIO_MAX_PORT_ID_INSTANCE_5                (18U)

/* GPIO Instance Pin Limits */
/* GPIO Instance Pin Limits: WAKEUP Domain 0*/
#define DIO_MAX_PIN_ID_INSTANCE_0                 (144U)
/* GPIO Instance Pin Limits: WAKEUP Domain 1*/
#define DIO_MAX_PIN_ID_INSTANCE_1                 (288U)
/* GPIO Instance Pin Limits: Main Domain 0*/
#define DIO_MAX_PIN_ID_INSTANCE_2                 (432U)
/* GPIO Instance Pin Limits: Main Domain 1*/
#define DIO_MAX_PIN_ID_INSTANCE_3                 (576U)
/* GPIO Instance Pin Limits: Main Domain 2*/
#define DIO_MAX_PIN_ID_INSTANCE_4                 (720U)
/* GPIO Instance Pin Limits: Main Domain 3*/
#define DIO_MAX_PIN_ID_INSTANCE_5                 (864U)

#define DIO_UTILS_ARRAYSIZE(array)             ((sizeof (array) / \
                                                 sizeof ((array)[0])))

/* ========================================================================== */
/*                         Structures and Enums                               */
/* ========================================================================== */
typedef struct {
    uint8 regNum;
    uint8 numPins;
    uint32 reservedPinStart;
} DioReservedPinListType;

/* ========================================================================== */
/*                          Global Declarations                               */
/* ========================================================================== */

/** \brief Reference to channel group structure for DioPort_WKUP_GPIO0_BANK0
  *  created at config time */
extern P2CONST(void, AUTOMATIC, DIO_CONST) DioConfig_DioPort_WKUP_GPIO0_BANK0_ChannelGroupRef[1];

/** \brief Reference to channel group structure for DioPort_WKUP_GPIO0_BANK23
  *  created at config time */
extern P2CONST(void, AUTOMATIC, DIO_CONST) DioConfig_DioPort_WKUP_GPIO0_BANK23_ChannelGroupRef[1];

/** \brief Reference to channel group structure for DioPort_GPIO0_BANK23
  *  created at config time */
extern P2CONST(void, AUTOMATIC, DIO_CONST) DioConfig_DioPort_GPIO0_BANK23_ChannelGroupRef[1];


#if (STD_ON == DIO_DEV_ERROR_DETECT)









    
    


/** \brief Channel mask for enabled pins in the available ports */
extern CONST (uint32,DIO_CONST) Dio_ConfigValidChannelMask[18U];

#endif /* (STD_ON == DIO_DEV_ERROR_DETECT) */

/** \brief DIO Max Port ID Instance */
extern const uint32 Dio_PortIdInstance[DIO_HW_UNIT_CNT + 1U];
/** \brief DIO Instance IDs */
extern const uint32 Dio_Instance[DIO_HW_UNIT_CNT];
/** \brief Base Address of Dio Instances */
extern const uint32 Dio_GPIOBaseAddr[DIO_HW_UNIT_CNT];

/* ========================================================================== */
/*                          Function Declarations                             */
/* ========================================================================== */
/** \brief This function checks whether pin is reserved  */
boolean Dio_isReservedPin(uint8 regNum, uint32 pinNum);

#ifdef __cplusplus
}
#endif

#endif  /* #ifndef DIO_CFG_H_ */

/* @} */
