/** @file mmr_safety.c 
 *  @brief  MMR Safety Application
 * 
 *  MMR Safety Application
 * 
 *  --------------------------------------------------------------------------
 *  @copyright MAGNA Electronics - C O N F I D E N T I A L <br>
 *  This document in its entirety is CONFIDENTIAL and may not be disclosed,
 *  disseminated or distributed to parties outside MAGNA Electronics
 *  without written permission from MAGNA Electronics.
 * 
 *  @author Anonymous Author (Anonymous.Author@magna.com)
 */

/**
 * This file contains functions that monitors safety
 * for the MMR module.
 *
 *  \details  MMR Safety module
 */
 
/* ===========================================================================
*
*   Include Files
*
* ========================================================================= */

#include "sdlr_soc.h"
#include <string.h>
#include "app_log.h"
#include "app_log_Boot.h"
#include "fusa_application.h"

#include "mmr_safety.h"

/* ===========================================================================
*
*   Defines
*
* ========================================================================= */


/* ===========================================================================
*
* Typedefs
*
* ========================================================================= */

typedef struct MMRSafety_MCU_ctrl_mmr0_critical_regs {
    uint32_t MCU_CTRL_MMR_CFG0_PID;
    uint32_t MCU_CTRL_MMR_CFG0_MMR_CFG0;
    uint32_t MCU_CTRL_MMR_CFG0_MMR_CFG1;
    uint32_t MCU_CTRL_MMR_CFG0_PID_PROXY;
    uint32_t MCU_CTRL_MMR_CFG0_MMR_CFG0_PROXY;
    uint32_t MCU_CTRL_MMR_CFG0_MMR_CFG1_PROXY;
} MMRSafety_MCU_ctrl_mmr0_critical_regs_t;

typedef struct MMRSafety_WKUP_ctrl_mmr0_critical_regs {
    uint32_t WKUP_CTRL_MMR_CFG0_PID;
    uint32_t WKUP_CTRL_MMR_CFG0_MMR_CFG0;
    uint32_t WKUP_CTRL_MMR_CFG0_MMR_CFG1;
    uint32_t WKUP_CTRL_MMR_CFG0_JTAGID;
    uint32_t WKUP_CTRL_MMR_CFG0_JTAG_USER_ID;
    uint32_t WKUP_CTRL_MMR_CFG0_DIE_ID0;
    uint32_t WKUP_CTRL_MMR_CFG0_DIE_ID1;
    uint32_t WKUP_CTRL_MMR_CFG0_DIE_ID2;
    uint32_t WKUP_CTRL_MMR_CFG0_DIE_ID3;
    uint32_t WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE0;
    uint32_t WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE1;
    uint32_t WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE2;
    uint32_t WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE3;
    uint32_t WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE4;
    uint32_t WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE5;
    uint32_t WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE6;
    uint32_t WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE7;
    uint32_t WKUP_CTRL_MMR_CFG0_SPARE_PLL0_CAL;
    uint32_t WKUP_CTRL_MMR_CFG0_SPARE_PLL1_CAL;
    uint32_t WKUP_CTRL_MMR_CFG0_MCU_PLL0_CAL;
    uint32_t WKUP_CTRL_MMR_CFG0_MCU_PLL1_CAL;
    uint32_t WKUP_CTRL_MMR_CFG0_MCU_PLL2_CAL;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL0_CAL;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL1_CAL;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL2_CAL;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL3_CAL;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL4_CAL;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL5_CAL;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL6_CAL;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL7_CAL;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL8_CAL;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL9_CAL;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL12_CAL;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL14_CAL;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL16_CAL;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL17_CAL;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL19_CAL;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL25_CAL;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL26_CAL;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL27_CAL;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL28_CAL;
    uint32_t WKUP_CTRL_MMR_CFG0_PID_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_MMR_CFG0_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_MMR_CFG1_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_JTAGID_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_JTAG_USER_ID_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_DIE_ID0_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_DIE_ID1_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_DIE_ID2_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_DIE_ID3_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE0_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE1_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE2_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE3_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE4_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE5_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE6_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE7_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_SPARE_PLL0_CAL_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_SPARE_PLL1_CAL_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_MCU_PLL0_CAL_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_MCU_PLL1_CAL_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_MCU_PLL2_CAL_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL0_CAL_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL1_CAL_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL2_CAL_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL3_CAL_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL4_CAL_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL5_CAL_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL6_CAL_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL7_CAL_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL8_CAL_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL9_CAL_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL12_CAL_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL14_CAL_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL16_CAL_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL17_CAL_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL19_CAL_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL25_CAL_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL26_CAL_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_MAIN_PLL27_CAL_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_WKUP_POST_CFG0;
    uint32_t WKUP_CTRL_MMR_CFG0_WKUP_POST_CFG1;
    uint32_t WKUP_CTRL_MMR_CFG0_WKUP_POST_CFG0_PROXY;
    uint32_t WKUP_CTRL_MMR_CFG0_WKUP_POST_CFG1_PROXY;
} MMRSafety_WKUP_ctrl_mmr0_critical_regs_t;

typedef struct MMRSafety_MAIN_ctrl_mmr0_critical_regs {
    uint32_t MAIN_CTRL_MMR_CFG0_PID;
    uint32_t MAIN_CTRL_MMR_CFG0_MMR_CFG1;
    uint32_t MAIN_CTRL_MMR_CFG0_MAIN_FEATURE_STAT0;
    uint32_t MAIN_CTRL_MMR_CFG0_MAIN_FEATURE_STAT1;
    uint32_t MAIN_CTRL_MMR_CFG0_PID_PROXY;
    uint32_t MAIN_CTRL_MMR_CFG0_MMR_CFG1_PROXY;
    uint32_t MAIN_CTRL_MMR_CFG0_MAIN_FEATURE_STAT0_PROXY;
    uint32_t MAIN_CTRL_MMR_CFG0_MAIN_FEATURE_STAT1_PROXY;
} MMRSafety_MAIN_ctrl_mmr0_critical_regs_t;

typedef struct MMRSafety_MCUCtrl_WKUPCtrl_mmr0_critical_regs {
    MMRSafety_MCU_ctrl_mmr0_critical_regs_t MMR_MCUCtrl_Reg;
    MMRSafety_WKUP_ctrl_mmr0_critical_regs_t MMR_WKUPCtrl_Reg;
} MMRSafety_MCUCtrl_WKUPCtrl_mmr0_critical_regs_t;

typedef struct MMRSafety_ctrl_mmr0_critical_regs {
    MMRSafety_MCUCtrl_WKUPCtrl_mmr0_critical_regs_t MMR_MCUWKUPCtrl_Reg;
    MMRSafety_MAIN_ctrl_mmr0_critical_regs_t MMR_MAINCtrl_Reg;
} MMRSafety_ctrl_mmr0_critical_regs_t;


/* ===========================================================================
*
* Private functions
*
* ========================================================================= */

static void mmr_safety_readStaticRegs(MMRSafety_ctrl_mmr0_critical_regs_t* pdata);

#define CDD_Safety_START_SEC_VAR_INIT_UNSPECIFIED
#include "CDD_Safety_MemMap.h"
/* ===========================================================================
*
*   Private variables
*
* ========================================================================= */

static MMRSafety_ctrl_mmr0_critical_regs_t gMMR_regs_content;

/* ===========================================================================
*
*   Global variables
*
* ========================================================================= */


#define CDD_Safety_STOP_SEC_VAR_INIT_UNSPECIFIED
#include "CDD_Safety_MemMap.h"

#define CDD_Safety_START_SEC_CODE
#include "CDD_Safety_MemMap.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */
/* ========================================================================== */
/*                          Function Implementation                           */
/* ========================================================================== */

/*!
 * \brief   Read MMR Register config function
 *
 * \param   pdata [IN]    pointer to HW reg storage 
 *
 * \retval  None 
 */
static void mmr_safety_readStaticRegs(MMRSafety_ctrl_mmr0_critical_regs_t* pdata)
{
  /* DD-ID: {BC79D64A-ED3A-42e0-8C49-198159DE66DD}*/
    /* base address CTRL_MMR0 + offset */
    /* Read MCU_CTRL_MMR_CFG0 Safety critical registers */
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_MCUCtrl_Reg.MCU_CTRL_MMR_CFG0_PID = *((uint32_t *)(SDL_MCU_CTRL_MMR0_CFG0_BASE + SDL_MCU_CTRL_MMR_CFG0_PID));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_MCUCtrl_Reg.MCU_CTRL_MMR_CFG0_MMR_CFG0 = *((uint32_t *)(SDL_MCU_CTRL_MMR0_CFG0_BASE + SDL_MCU_CTRL_MMR_CFG0_MMR_CFG0));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_MCUCtrl_Reg.MCU_CTRL_MMR_CFG0_MMR_CFG1 = *((uint32_t *)(SDL_MCU_CTRL_MMR0_CFG0_BASE + SDL_MCU_CTRL_MMR_CFG0_MMR_CFG1));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_MCUCtrl_Reg.MCU_CTRL_MMR_CFG0_PID_PROXY = *((uint32_t *)(SDL_MCU_CTRL_MMR0_CFG0_BASE + SDL_MCU_CTRL_MMR_CFG0_PID_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_MCUCtrl_Reg.MCU_CTRL_MMR_CFG0_MMR_CFG0_PROXY = *((uint32_t *)(SDL_MCU_CTRL_MMR0_CFG0_BASE + SDL_MCU_CTRL_MMR_CFG0_MMR_CFG0_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_MCUCtrl_Reg.MCU_CTRL_MMR_CFG0_MMR_CFG1_PROXY = *((uint32_t *)(SDL_MCU_CTRL_MMR0_CFG0_BASE + SDL_MCU_CTRL_MMR_CFG0_MMR_CFG1_PROXY));
    
    /* Read WKUP_CTRL_MMR_CFG0 Safety critical registers */
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_PID = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_PID));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MMR_CFG0 = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MMR_CFG0));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MMR_CFG1 = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MMR_CFG1));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_JTAGID = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_JTAGID));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_JTAG_USER_ID = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_JTAG_USER_ID));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_DIE_ID0 = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_DIE_ID0));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_DIE_ID1 = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_DIE_ID1));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_DIE_ID2 = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_DIE_ID2));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_DIE_ID3 = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_DIE_ID3));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE0 = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE0));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE1 = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE1));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE2 = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE2));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE3 = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE3));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE4 = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE4));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE5 = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE5));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE6 = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE6));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE7 = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE7));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_SPARE_PLL0_CAL = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_SPARE_PLL0_CAL));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_SPARE_PLL1_CAL = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_SPARE_PLL1_CAL));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MCU_PLL0_CAL = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MCU_PLL0_CAL));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MCU_PLL1_CAL = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MCU_PLL1_CAL));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MCU_PLL2_CAL = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MCU_PLL2_CAL));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL0_CAL = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL0_CAL));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL1_CAL = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL1_CAL));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL2_CAL = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL2_CAL));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL3_CAL = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL3_CAL));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL4_CAL = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL4_CAL));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL5_CAL = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL5_CAL));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL6_CAL = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL6_CAL));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL7_CAL = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL7_CAL));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL8_CAL = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL8_CAL));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL9_CAL = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL9_CAL));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL12_CAL = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL12_CAL));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL14_CAL = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL14_CAL));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL16_CAL = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL16_CAL));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL17_CAL = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL17_CAL));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL19_CAL = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL19_CAL));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL25_CAL = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL25_CAL));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL26_CAL = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL26_CAL));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL27_CAL = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL27_CAL));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL28_CAL = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL28_CAL));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_PID_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_PID_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MMR_CFG0_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MMR_CFG0_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MMR_CFG1_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MMR_CFG1_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_JTAGID_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_JTAGID_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_JTAG_USER_ID_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_JTAG_USER_ID_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_DIE_ID0_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_DIE_ID0_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_DIE_ID1_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_DIE_ID1_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_DIE_ID2_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_DIE_ID2_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_DIE_ID3_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_DIE_ID3_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE0_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE0_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE1_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE1_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE2_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE2_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE3_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE3_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE4_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE4_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE5_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE5_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE6_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE6_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE7_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_DEVICE_FEATURE7_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_SPARE_PLL0_CAL_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_SPARE_PLL0_CAL_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_SPARE_PLL1_CAL_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_SPARE_PLL1_CAL_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MCU_PLL0_CAL_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MCU_PLL0_CAL_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MCU_PLL1_CAL_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MCU_PLL1_CAL_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MCU_PLL2_CAL_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MCU_PLL2_CAL_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL0_CAL_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL0_CAL_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL1_CAL_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL1_CAL_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL2_CAL_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL2_CAL_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL3_CAL_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL3_CAL_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL4_CAL_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL4_CAL_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL5_CAL_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL5_CAL_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL6_CAL_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL6_CAL_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL7_CAL_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL7_CAL_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL8_CAL_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL8_CAL_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL9_CAL_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL9_CAL_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL12_CAL_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL12_CAL_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL14_CAL_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL14_CAL_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL16_CAL_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL16_CAL_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL17_CAL_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL17_CAL_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL19_CAL_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL19_CAL_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL25_CAL_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL25_CAL_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL26_CAL_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL26_CAL_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_MAIN_PLL27_CAL_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_MAIN_PLL27_CAL_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_WKUP_POST_CFG0 = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_WKUP_POST_CFG0));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_WKUP_POST_CFG1 = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_WKUP_POST_CFG1));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_WKUP_POST_CFG0_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_WKUP_POST_CFG0_PROXY));
    pdata->MMR_MCUWKUPCtrl_Reg.MMR_WKUPCtrl_Reg.WKUP_CTRL_MMR_CFG0_WKUP_POST_CFG1_PROXY = *((uint32_t *)(SDL_WKUP_CTRL_MMR0_CFG0_BASE + SDL_WKUP_CTRL_MMR_CFG0_WKUP_POST_CFG1_PROXY));

    /* Read MAIN_CTRL_MMR0 Safety critical registers */
    pdata->MMR_MAINCtrl_Reg.MAIN_CTRL_MMR_CFG0_PID = *((uint32_t *)(SDL_CTRL_MMR0_CFG0_BASE + SDL_MAIN_CTRL_MMR_CFG0_PID));
    pdata->MMR_MAINCtrl_Reg.MAIN_CTRL_MMR_CFG0_MMR_CFG1 = *((uint32_t *)(SDL_CTRL_MMR0_CFG0_BASE + SDL_MAIN_CTRL_MMR_CFG0_MMR_CFG1));
    pdata->MMR_MAINCtrl_Reg.MAIN_CTRL_MMR_CFG0_MAIN_FEATURE_STAT0 = *((uint32_t *)(SDL_CTRL_MMR0_CFG0_BASE + SDL_MAIN_CTRL_MMR_CFG0_MAIN_FEATURE_STAT0));
    pdata->MMR_MAINCtrl_Reg.MAIN_CTRL_MMR_CFG0_MAIN_FEATURE_STAT1 = *((uint32_t *)(SDL_CTRL_MMR0_CFG0_BASE + SDL_MAIN_CTRL_MMR_CFG0_MAIN_FEATURE_STAT1));
    pdata->MMR_MAINCtrl_Reg.MAIN_CTRL_MMR_CFG0_PID_PROXY = *((uint32_t *)(SDL_CTRL_MMR0_CFG0_BASE + SDL_MAIN_CTRL_MMR_CFG0_PID_PROXY));
    pdata->MMR_MAINCtrl_Reg.MAIN_CTRL_MMR_CFG0_MMR_CFG1_PROXY = *((uint32_t *)(SDL_CTRL_MMR0_CFG0_BASE + SDL_MAIN_CTRL_MMR_CFG0_MMR_CFG1_PROXY));
    pdata->MMR_MAINCtrl_Reg.MAIN_CTRL_MMR_CFG0_MAIN_FEATURE_STAT0_PROXY = *((uint32_t *)(SDL_CTRL_MMR0_CFG0_BASE + SDL_MAIN_CTRL_MMR_CFG0_MAIN_FEATURE_STAT0_PROXY));
    pdata->MMR_MAINCtrl_Reg.MAIN_CTRL_MMR_CFG0_MAIN_FEATURE_STAT1_PROXY = *((uint32_t *)(SDL_CTRL_MMR0_CFG0_BASE + SDL_MAIN_CTRL_MMR_CFG0_MAIN_FEATURE_STAT1_PROXY));
}

/* ===========================================================================
*
*   Global functions
*
* ========================================================================= */
/*
 * Purpose: Initialize MMR safety and Read the first pass MMR registers 
 * Description: Readback MMR registers after initialization 
 * Return Type : void 
 */

void TASK_mmr_safety_init(void)
{
  /* DD-ID: {AA49A43B-23CD-4079-9F03-CA0AA5914AFC}*/
    #if ( SDL_APP_MMR_ENABLED == SDL_APP_ON )
    /* Read MMR Static Registers for future compare */
    mmr_safety_readStaticRegs(&gMMR_regs_content);
    #endif
}

/*
 * Purpose: MMR safety mainfunction to check registers against first pass values 
 * Description: Will set fault if mismatch 
 * Return Type : void 
 */
void TASK_mmr_safety_MainFunction(void)
{
  /* DD-ID: {BEC7A53D-486D-4332-8A0E-7C60BB66B8E4}*/
    static MMRSafety_ctrl_mmr0_critical_regs_t tempMMR_regs_content;
    const uint8_t *tempRegPtr  = (uint8_t *)&tempMMR_regs_content.MMR_MCUWKUPCtrl_Reg;
    const uint8_t *regPtr = (uint8_t *)&gMMR_regs_content.MMR_MCUWKUPCtrl_Reg;
    const uint8_t *tempRegMainPtr = (uint8_t *)&tempMMR_regs_content.MMR_MAINCtrl_Reg;
    const uint8_t *regMainPtr = (uint8_t *)&gMMR_regs_content.MMR_MAINCtrl_Reg;
    #if ( SDL_APP_MMR_ENABLED == SDL_APP_ON )
    /* Read MMR Static Registers */
    mmr_safety_readStaticRegs(&tempMMR_regs_content);

    /* Check current read of tempMMR_regs_content.MMR_MCUWKUPCtrl_Reg matches the intial gMMR_regs_content.MMR_MCUWKUPCtrl_Reg */
    if (0x00 != memcmp((const uint8_t*)regPtr, (const uint8_t*)tempRegPtr, sizeof(MMRSafety_MCUCtrl_WKUPCtrl_mmr0_critical_regs_t)))
    {
        #if defined (SDL_APP_MMR_UART_PRINTS_ENABLED)
        UART_printf("mmr_safety_readStaticRegs: Compare failure for MCU_WKUP CTRL_MMR on line no. %d \n", __LINE__);
        #endif
        Fusa_Application_SetMcuWkupMMRSafetyCriticalConfigFailFlag();
    } 
    else
    {
        #if defined (SDL_APP_MMR_UART_PRINTS_ENABLED)
        UART_printf("mmr_safety_readStaticRegs: PASS for MCU_WKUP MMR\n");
        #endif
    }

    /* Check current read of tempMMR_regs_content.MMR_MAINCtrl_Reg matches the intial gMMR_regs_content.MMR_MAINCtrl_Reg */
    if (0x00 != memcmp((const uint8_t*)regMainPtr, (const uint8_t*)tempRegMainPtr, sizeof(MMRSafety_MAIN_ctrl_mmr0_critical_regs_t)))
    {
        #if defined (SDL_APP_MMR_UART_PRINTS_ENABLED)
        UART_printf("mmr_safety_readStaticRegs: Compare failure for MAIN CTRL_MMR on line no. %d \n", __LINE__);
        #endif
        Fusa_Application_SetMainMMRSafetyCriticalConfigFailFlag();
    } 
    else
    {
        #if defined (SDL_APP_MMR_UART_PRINTS_ENABLED)
        UART_printf("mmr_safety_readStaticRegs: PASS for MAIN CTRL_MMR \n");
        #endif
    }    
    #endif
}

/* Nothing past this point */

#define CDD_Safety_STOP_SEC_CODE
#include "CDD_Safety_MemMap.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */
