/* =========================================================================
 * MAGNA Electronics - C O N F I D E N T I A L
 *  This document in its entirety is CONFIDENTIAL and may not be disclosed
 *  disseminated or distributed to parties outside MAGNA Electronics
 *  without written permission from MAGNA Electronics.
 * ========================================================================= */
/* ================= (c) MAGNA Electronics Solutions ======================= */
/** @ingroup
 *  @file           profiler.h
 *  @brief          profiler API declaration
 *
 *
 *  @version        3.31
 *  @author         Mikhail Vakhrushev
 *  @date           10.04.2020
 *
 * =========================================================================
 *
 *  @par          Change History:
 *
 * ========================================================================= */
#pragma once

#include<stdint.h>

/*
*   grep -rn PROF_START --include=*.c | sed -E "s/.*PROF_START\((\w+)\).+/PROFILER_ACTION(\1)\\\\/g"
*   The body of the following define is generated by the upper command.
*/
#define PROFILER_ITEMS(PROFILER_ACTION)\
    PROFILER_ACTION(algorithm_pipeline)\
    PROFILER_ACTION(AWB_run)\
    PROFILER_ACTION(processFrame)\
    PROFILER_ACTION(processFrame_iter)\



#define PROFILER_LIST_ACTION(X) PROF_##X,
typedef enum
{
    PROF_START = 0,
    PROFILER_ITEMS(PROFILER_LIST_ACTION)
    PROF_NUM
} PROFILER_TYPE;

typedef struct
{
    uint8_t* dump;
    uint32_t pos;
    uint32_t tab;
    PROFILER_TYPE cur_method[32];
    uint64_t timings[32];
}profiler_t;

extern profiler_t g_profiler;

void prof_start(PROFILER_TYPE t);
void prof_end(void);
void prof_dump(void);
void print_prof(void);


#define PROF_START(NAME) prof_start(PROF_##NAME);
#define PROF_END(...) prof_end();
