#ifndef ERRORMGR_QNXBASE_DEFS_H_INCGUARD 
#define ERRORMGR_QNXBASE_DEFS_H_INCGUARD 



#include "unix.h"
#include "errno.h"
#include "unistd.h"
#include "sys/iofunc.h"
#include "sys/dispatch.h"



/**************************************************************************************************
          This file is generated. Any changes will be overwritten. No handmodifications allowed   
          ErrorManager generator version used23.04.20                     
***************************************************************************************************/



/**********************************************************
Generated on : 	0x260127173337
Generated using Generator Version :23.04.20
Generated using Excel file Version :nan_NaT_nan
Generated by :sripkulk
**************************************************************/


#ifndef ERRORMGR_VERSIONCHECKER_VERSION
	#define ERRORMGR_VERSIONCHECKER_VERSION 0x260127173337
#else
	#if ERRORMGR_VERSIONCHECKER_VERSION != 0x260127173337
		#error "mismatched files used for compiling"
	#endif
#endif



#if ERRORMGR_CURRENTCORE == ERRORMGRCORE_MCUQNX

const BaseSWCommon_VirtualDeviceDef * ErrorMgr_GetqnxVirtualDeviceList();
#define ErrorMgr_VirtualDevDefs_Count 0
#endif //if ERRORMGR_CURRENTCORE == ERRORMGRCORE_MCUQNX

#endif /* End Include Guard */
