/**
* Note: This file was auto-generated by TI PinMux on 12/16/2022 at 2:38:35 PM.
*
* \file  J721S2_pinmux_data.c
*
* \brief  This file contains the pin mux configurations for the boards.
*         These are prepared based on how the peripherals are extended on
*         the boards.
*
* \copyright Copyright (CU) 2022 Texas Instruments Incorporated -
*             http://www.ti.com/
*/

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */

#include "J721S2_pinmux.h"

/** Peripheral Pin Configurations */


static pinmuxPerCfg_t gCpsw2g0PinCfg[] =
{
    /* CPSW2G0 -> MDIO0_MDC -> T28 */
    {
        PIN_MCASP1_AXR0, PIN_MODE(6) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* CPSW2G0 -> MDIO0_MDIO -> V28 */
    {
        PIN_MCASP1_AFSX, PIN_MODE(6) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* CPSW2G0 -> RGMII1_RD0 -> AA24 */
    {
        PIN_MCASP1_ACLKX, PIN_MODE(6) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE  | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* CPSW2G0 -> RGMII1_RD1 -> AB25 */
    {
        PIN_MCASP0_AXR12, PIN_MODE(6) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE  | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* CPSW2G0 -> RGMII1_RD2 -> T23 */
    {
        PIN_MCASP0_AXR13, PIN_MODE(6) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE  | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* CPSW2G0 -> RGMII1_RD3 -> U24 */
    {
        PIN_MCASP0_AXR14, PIN_MODE(6) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE  | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* CPSW2G0 -> RGMII1_RXC -> AD26 */
    {
        PIN_MCASP1_AXR3, PIN_MODE(6) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE  | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* CPSW2G0 -> RGMII1_RX_CTL -> AC25 */
    {
        PIN_MCASP0_AXR15, PIN_MODE(6) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE  | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* CPSW2G0 -> RGMII1_TD0 -> T25 */
    {
        PIN_MCASP0_AXR7, PIN_MODE(6) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* CPSW2G0 -> RGMII1_TD1 -> W24 */
    {
        PIN_MCASP0_AXR8, PIN_MODE(6) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* CPSW2G0 -> RGMII1_TD2 -> AA25 */
    {
        PIN_MCASP0_AXR9, PIN_MODE(6) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* CPSW2G0 -> RGMII1_TD3 -> V25 */
    {
        PIN_MCASP0_AXR10, PIN_MODE(6) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* CPSW2G0 -> RGMII1_TXC -> U25 */
    {
        PIN_MCASP1_AXR4, PIN_MODE(6) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* CPSW2G0 -> RGMII1_TX_CTL -> T24 */
    {
        PIN_MCASP0_AXR11, PIN_MODE(6) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gCpsw2gPinCfg[] =
{
    {0, TRUE, gCpsw2g0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gDebugss0PinCfg[] =
{
    /* DEBUGSS -> TRC_CLK -> W25 */
    {
        PIN_MCAN12_TX, PIN_MODE(10) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* DEBUGSS -> TRC_CTL -> AC24 */
    {
        PIN_MCAN12_RX, PIN_MODE(10) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* DEBUGSS -> TRC_DATA0 -> AE28 */
    {
        PIN_MCAN13_TX, PIN_MODE(10) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* DEBUGSS -> TRC_DATA1 -> AF28 */
    {
        PIN_MCAN13_RX, PIN_MODE(10) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* DEBUGSS -> TRC_DATA2 -> AD25 */
    {
        PIN_MCAN14_TX, PIN_MODE(10) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* DEBUGSS -> TRC_DATA3 -> W23 */
    {
        PIN_MCAN14_RX, PIN_MODE(10) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* DEBUGSS -> TRC_DATA4 -> Y27 */
    {
        PIN_MCASP2_ACLKX, PIN_MODE(10) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* DEBUGSS -> TRC_DATA5 -> R27 */
    {
        PIN_MCAN1_RX, PIN_MODE(10) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* DEBUGSS -> TDI -> AG28 */
    {
        PIN_TDI, PIN_MODE(0) | \
        ((PIN_PULL_DIRECTION | PIN_INPUT_ENABLE | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DISABLE))
    },
    /* DEBUGSS -> TDO -> AE26 */
    {
        PIN_TDO, PIN_MODE(0) | \
        ((PIN_PULL_DIRECTION) & (~PIN_PULL_DISABLE & ~PIN_INPUT_ENABLE))
    },
    /* DEBUGSS -> TMS -> AG27 */
    {
        PIN_TMS, PIN_MODE(0) | \
        ((PIN_PULL_DIRECTION | PIN_INPUT_ENABLE | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DISABLE))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gDebugssPinCfg[] =
{
    {0, TRUE, gDebugss0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gTimer1PinCfg[] =
{
    /* TIMER -> TIMER_IO1 -> AG25 */
    {
        PIN_TIMER_IO1, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gTimerPinCfg[] =
{
    {1, TRUE, gTimer1PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gEhrpwm1PinCfg[] =
{
    /* EHRPWM1 -> EHRPWM1_A -> AC27 */
    {
        PIN_MCASP2_AXR1, PIN_MODE(9) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    {PINMUX_END}
};

static pinmuxPerCfg_t gEhrpwm2PinCfg[] =
{
    /* EHRPWM2 -> EHRPWM2_A -> AC28 */
    {
        PIN_MCASP0_AXR0, PIN_MODE(9) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gEhrpwmPinCfg[] =
{
    {1, TRUE, gEhrpwm1PinCfg},
    {2, TRUE, gEhrpwm2PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gGpio0PinCfg[] =
{
    /* GPIO0 -> GPIO0_0 -> AG24 */
    {
        PIN_EXTINTN, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* GPIO0 -> GPIO0_11 -> V23 */
    {
        PIN_GPIO0_11, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE  | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* GPIO0 -> GPIO0_12 -> T26 */
    {
        PIN_GPIO0_12, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* GPIO0 -> GPIO0_13 -> AD24 */
    {
        PIN_PMIC_WAKE0N, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* GPIO0 -> GPIO0_17 -> Y26 */
    {
        PIN_MCASP0_AXR1, PIN_MODE(7) | \
        ((PIN_PULL_DIRECTION | PIN_INPUT_ENABLE | PIN_OUTPUT_DISABLE ) & (~PIN_PULL_DISABLE))
    },
    /* GPIO0 -> GPIO0_18 -> AB27 */
    {
        PIN_MCASP0_AXR2, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE  | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* GPIO0 -> GPIO0_19 -> V27 */
    {
        PIN_MCASP1_AXR1, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE  | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* GPIO0 -> GPIO0_20 -> W27 */
    {
        PIN_MCASP1_AXR2, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* GPIO0 -> GPIO0_22 -> AA27 */
    {
        PIN_MCASP2_AFSX, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE  | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* GPIO0 -> GPIO0_23 -> AA26 */
    {
        PIN_MCASP2_AXR0, PIN_MODE(7) | \
        ((PIN_PULL_DIRECTION | PIN_INPUT_ENABLE| PIN_OUTPUT_DISABLE) & (~PIN_PULL_DISABLE))
    },
    /* GPIO0 -> GPIO0_27 -> V26 */
    {
        PIN_MCAN1_TX, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* GPIO0 -> GPIO0_31 -> T27 */
    {
        PIN_MCASP0_AXR3, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* GPIO0 -> GPIO0_34 -> AD27 */
    {
        PIN_MCASP0_AXR6, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* GPIO0 -> GPIO0_58 -> AE25 */
    {
       PIN_TIMER_IO0, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gGpioPinCfg[] =
{
    {0, TRUE, gGpio0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gI2c0PinCfg[] =
{
    /* I2C0 -> I2C0_SCL -> AH25 */
    {
        PIN_I2C0_SCL, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* I2C0 -> I2C0_SDA -> AE24 */
    {
        PIN_I2C0_SDA, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxPerCfg_t gI2c1PinCfg[] =
{
    /* I2C1 -> I2C1_SCL -> AB26 */
    {
        PIN_ECAP0_IN_APWM_OUT, PIN_MODE(13) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* I2C1 -> I2C1_SDA -> AD28 */
    {
        PIN_EXT_REFCLK1, PIN_MODE(13) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxPerCfg_t gI2c4PinCfg[] =
{
    /* I2C4 -> I2C4_SCL -> AA28 */
    {
        PIN_MCASP0_AXR5, PIN_MODE(13) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* I2C4 -> I2C4_SDA -> U26 */
    {
        PIN_MCASP0_AXR4, PIN_MODE(13) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxPerCfg_t gI2c5PinCfg[] =
{
    /* I2C5 -> I2C5_SCL -> R28 */
    {
        PIN_MCAN2_TX, PIN_MODE(13) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* I2C5 -> I2C5_SDA -> Y25 */
    {
        PIN_MCAN2_RX, PIN_MODE(13) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gI2cPinCfg[] =
{
    {0, TRUE, gI2c0PinCfg},
    {1, TRUE, gI2c1PinCfg},
    {4, TRUE, gI2c4PinCfg},
    {5, TRUE, gI2c5PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gMcan5PinCfg[] =
{
    /* MCAN15 -> MCAN15_RX -> AA23 */
    {
        PIN_MCAN15_RX, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE  | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCAN15 -> MCAN15_TX -> Y24 */
    {
        PIN_MCAN15_TX, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    {PINMUX_END}
};

static pinmuxPerCfg_t gMcan6PinCfg[] =
{
    /* MCAN16 -> MCAN16_RX -> AB24 */
    {
        PIN_MCAN16_RX, PIN_MODE(0) | \
        ((PIN_INPUT_ENABLE | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DISABLE & ~PIN_PULL_DIRECTION))
    },
    /* MCAN16 -> MCAN16_TX -> Y28 */
    {
        PIN_MCAN16_TX, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gMcanPinCfg[] =
{
    {5, TRUE, gMcan5PinCfg},
    {6, TRUE, gMcan6PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gMcu_adc0PinCfg[] =
{
    /* MCU_ADC0 -> MCU_ADC0_AIN0 -> L25 */
    {
        PIN_MCU_ADC0_AIN0, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_ADC0 -> MCU_ADC0_AIN1 -> K25 */
    {
        PIN_MCU_ADC0_AIN1, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_ADC0 -> MCU_ADC0_AIN2 -> M24 */
    {
        PIN_MCU_ADC0_AIN2, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_ADC0 -> MCU_ADC0_AIN3 -> L24 */
    {
        PIN_MCU_ADC0_AIN3, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_ADC0 -> MCU_ADC0_AIN4 -> L27 */
    {
        PIN_MCU_ADC0_AIN4, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_ADC0 -> MCU_ADC0_AIN5 -> K24 */
    {
        PIN_MCU_ADC0_AIN5, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_ADC0 -> MCU_ADC0_AIN6 -> M27 */
    {
        PIN_MCU_ADC0_AIN6, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_ADC0 -> MCU_ADC0_AIN7 -> M26 */
    {
        PIN_MCU_ADC0_AIN7, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxPerCfg_t gMcu_adc1PinCfg[] =
{
    /* MCU_ADC1 -> MCU_ADC1_AIN0 -> P25 */
    {
        PIN_MCU_ADC1_AIN0, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_ADC1 -> MCU_ADC1_AIN1 -> R25 */
    {
        PIN_MCU_ADC1_AIN1, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_ADC1 -> MCU_ADC1_AIN2 -> P28 */
    {
        PIN_MCU_ADC1_AIN2, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_ADC1 -> MCU_ADC1_AIN3 -> P27 */
    {
        PIN_MCU_ADC1_AIN3, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_ADC1 -> MCU_ADC1_AIN4 -> N25 */
    {
        PIN_MCU_ADC1_AIN4, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_ADC1 -> MCU_ADC1_AIN5 -> P26 */
    {
        PIN_MCU_ADC1_AIN5, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_ADC1 -> MCU_ADC1_AIN6 -> N26 */
    {
        PIN_MCU_ADC1_AIN6, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_ADC1 -> MCU_ADC1_AIN7 -> N27 */
    {
        PIN_MCU_ADC1_AIN7, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gMcu_adcPinCfg[] =
{
    {0, TRUE, gMcu_adc0PinCfg},
    {1, TRUE, gMcu_adc1PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gMcu_cpsw2g0PinCfg[] =
{
    /* MCU_CPSW2G0 -> MCU_RGMII1_RD0 -> B22 */
    {
        PIN_MCU_RGMII1_RD0, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE  | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_CPSW2G0 -> MCU_RGMII1_RD1 -> B21 */
    {
        PIN_MCU_RGMII1_RD1, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE  | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_CPSW2G0 -> MCU_RGMII1_RD2 -> C22 */
    {
        PIN_MCU_RGMII1_RD2, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE  | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_CPSW2G0 -> MCU_RGMII1_RD3 -> D23 */
    {
        PIN_MCU_RGMII1_RD3, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE  | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_CPSW2G0 -> MCU_RGMII1_RXC -> D22 */
    {
        PIN_MCU_RGMII1_RXC, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE  | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_CPSW2G0 -> MCU_RGMII1_RX_CTL -> E23 */
    {
        PIN_MCU_RGMII1_RX_CTL, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE  | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_CPSW2G0 -> MCU_RGMII1_TD0 -> F23 */
    {
        PIN_MCU_RGMII1_TD0, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MCU_CPSW2G0 -> MCU_RGMII1_TD1 -> G22 */
    {
        PIN_MCU_RGMII1_TD1, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MCU_CPSW2G0 -> MCU_RGMII1_TD2 -> E21 */
    {
        PIN_MCU_RGMII1_TD2, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MCU_CPSW2G0 -> MCU_RGMII1_TD3 -> E22 */
    {
        PIN_MCU_RGMII1_TD3, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MCU_CPSW2G0 -> MCU_RGMII1_TXC -> F21 */
    {
        PIN_MCU_RGMII1_TXC, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MCU_CPSW2G0 -> MCU_RGMII1_TX_CTL -> F22 */
    {
        PIN_MCU_RGMII1_TX_CTL, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gMcu_cpsw2gPinCfg[] =
{
    {0, TRUE, gMcu_cpsw2g0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gMcu_i2c1PinCfg[] =
{
    /* MCU_I2C1 -> MCU_I2C1_SCL -> F24 */
    {
        PIN_WKUP_GPIO0_8, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_I2C1 -> MCU_I2C1_SDA -> H26 */
    {
        PIN_WKUP_GPIO0_9, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gMcu_i2cPinCfg[] =
{
    {1, TRUE, gMcu_i2c1PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gMcu_mcan0PinCfg[] =
{
    /* MCU_MCAN0 -> MCU_MCAN0_RX -> E28 */
    {
        PIN_MCU_MCAN0_RX, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE  | PIN_OUTPUT_DISABLE ) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_MCAN0 -> MCU_MCAN0_TX -> E27 */
    {
        PIN_MCU_MCAN0_TX, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gMcu_mcanPinCfg[] =
{
    {0, TRUE, gMcu_mcan0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gMcu_mdio0PinCfg[] =
{
    /* MCU_MDIO0 -> MCU_MDIO0_MDC -> A21 */
    {
        PIN_MCU_MDIO0_MDC, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MCU_MDIO0 -> MCU_MDIO0_MDIO -> A22 */
    {
        PIN_MCU_MDIO0_MDIO, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gMcu_mdioPinCfg[] =
{
    {0, TRUE, gMcu_mdio0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gMcu_ospi0PinCfg[] =
{
    /* MCU_OSPI0 -> MCU_OSPI0_CLK -> D19 */
    {
        PIN_MCU_OSPI0_CLK, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MCU_OSPI0 -> MCU_OSPI0_CSn0 -> F15 */
    {
        PIN_MCU_OSPI0_CSN0, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MCU_OSPI0 -> MCU_OSPI0_D0 -> C19 */
    {
        PIN_MCU_OSPI0_D0, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_OSPI0 -> MCU_OSPI0_D1 -> F16 */
    {
        PIN_MCU_OSPI0_D1, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_OSPI0 -> MCU_OSPI0_D2 -> G15 */
    {
        PIN_MCU_OSPI0_D2, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_OSPI0 -> MCU_OSPI0_D3 -> F18 */
    {
        PIN_MCU_OSPI0_D3, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_23 -> E19 */
    {
        PIN_MCU_OSPI0_D4, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_24 -> G19 */
    {
        PIN_MCU_OSPI0_D5, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_25 -> F19 */
    {
        PIN_MCU_OSPI0_D6, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_26 -> F20 */
    {
        PIN_MCU_OSPI0_D7, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_OSPI0 -> MCU_OSPI0_DQS -> E18 */
    {
        PIN_MCU_OSPI0_DQS, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE  | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_OSPI0 -> MCU_OSPI0_LBCLKO -> E20 */
    {
        PIN_MCU_OSPI0_LBCLKO, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gMcu_ospiPinCfg[] =
{
    {0, TRUE, gMcu_ospi0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gMcu_uart0PinCfg[] =
{
    /* MCU_UART0 -> MCU_UART0_RXD -> C24 */
    {
        PIN_WKUP_GPIO0_13, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MCU_UART0 -> MCU_UART0_TXD -> C25 */
    {
        PIN_WKUP_GPIO0_12, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gMcu_uartPinCfg[] =
{
    {0, TRUE, gMcu_uart0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gMmcsd1PinCfg[] =
{
    /* MMCSD1 -> MMC1_CLK -> P23 */
    {
        PIN_MMC1_CLK, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* MMCSD1 -> MMC1_CMD -> N24 */
    {
        PIN_MMC1_CMD, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MMCSD1 -> MMC1_DAT0 -> M23 */
    {
        PIN_MMC1_DAT0, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MMCSD1 -> MMC1_DAT1 -> P24 */
    {
        PIN_MMC1_DAT1, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MMCSD1 -> MMC1_DAT2 -> R24 */
    {
        PIN_MMC1_DAT2, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* MMCSD1 -> MMC1_DAT3 -> R22 */
    {
        PIN_MMC1_DAT3, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* Without the two below, SD card does not work under QNX if booted from NAND */
    /* MMCSD1 -> MMC1_SDCD -> AE25 */
    /* Shruthi R : GPIO0_58 is to be used as DSEL per HSIS Req. 17285883 - not for SD */
    /*
    {
        PIN_TIMER_IO0, PIN_MODE(8) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    */
    /* MMC1 -> MMC1_CLKLB */
    {
        PIN_MMC1_CLKLB, PIN_MODE(0) | \
        ((PIN_PULL_DIRECTION | PIN_INPUT_ENABLE) & (~PIN_PULL_DISABLE))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gMmcsdPinCfg[] =
{
    {1, TRUE, gMmcsd1PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gSpi0PinCfg[] =
{
    /* SPI0 -> SPI0_CLK -> AH27 */
    {
        PIN_SPI0_CLK, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_DRV_STR_SLOW ) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* SPI0 -> SPI0_CS0 -> AE27 */
    {
        PIN_SPI0_CS0, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_DRV_STR_SLOW ) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* SPI0 -> SPI0_CS1 -> AF26 */
    {
        PIN_SPI0_CS1, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_DRV_STR_SLOW ) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* SPI0 -> SPI0_D0 -> AG26 */
    {
        PIN_SPI0_D0, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_DRV_STR_SLOW ) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* SPI0 -> SPI0_D1 -> AH26 */
    {
        PIN_SPI0_D1, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE  | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gSpiPinCfg[] =
{
    {0, TRUE, gSpi0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gSystem0PinCfg[] =
{
    /* SYSTEM -> RESETSTATz -> AF27 */
    {
        PIN_RESETSTATZ, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* SYSTEM -> SOC_SAFETY_ERRORn -> AF25 */
    {
        PIN_SOC_SAFETY_ERRORN, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gSystemPinCfg[] =
{
    {0, TRUE, gSystem0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gUart2PinCfg[] =
{
    /* UART2 -> UART2_RXD -> W28 */
    {
        PIN_MCAN0_TX, PIN_MODE(11) | \
        ((PIN_INPUT_ENABLE | PIN_OUTPUT_DISABLE ) & (~PIN_PULL_DISABLE & ~PIN_PULL_DIRECTION))
    },
    /* UART2 -> UART2_TXD -> U28 */
    {
        PIN_MCAN0_RX, PIN_MODE(11) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    {PINMUX_END}
};

static pinmuxPerCfg_t gUart8PinCfg[] =
{
    /* UART8 -> UART8_RXD -> AB28 */
    {
        PIN_MCASP0_ACLKX, PIN_MODE(11) | \
        ((PIN_INPUT_ENABLE | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DISABLE & ~PIN_PULL_DIRECTION))
    },
    /* UART8 -> UART8_TXD -> U27 */
    {
        PIN_MCASP0_AFSX, PIN_MODE(11) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gUartPinCfg[] =
{
    {2, TRUE, gUart2PinCfg},
    {8, TRUE, gUart8PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gWkup_debugss0PinCfg[] =
{
    /* WKUP_DEBUGSS -> EMU0 -> A27 */
    {
        PIN_EMU0, PIN_MODE(0) | \
        ((PIN_PULL_DIRECTION | PIN_INPUT_ENABLE) & (~PIN_PULL_DISABLE))
    },
    /* WKUP_DEBUGSS -> EMU1 -> C26 */
    {
        PIN_EMU1, PIN_MODE(0) | \
        ((PIN_PULL_DIRECTION | PIN_INPUT_ENABLE) & (~PIN_PULL_DISABLE))
    },
    /* WKUP_DEBUGSS -> TCK -> A25 */
    {
        PIN_TCK, PIN_MODE(0) | \
        ((PIN_PULL_DIRECTION | PIN_INPUT_ENABLE) & (~PIN_PULL_DISABLE))
    },
    /* WKUP_DEBUGSS -> TRSTn -> B28 */
    {
        PIN_TRSTN, PIN_MODE(0) | \
        ((PIN_INPUT_ENABLE) & (~PIN_PULL_DISABLE & ~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gWkup_debugssPinCfg[] =
{
    {0, TRUE, gWkup_debugss0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gWkup_gpio0PinCfg[] =
{
    /* WKUP_GPIO0 -> WKUP_GPIO0_0 -> D26 */
    {
        PIN_WKUP_GPIO0_0, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_1 -> E24 */
    {
        PIN_WKUP_GPIO0_1, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_2 -> C28 */
    {
        PIN_WKUP_GPIO0_2, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_3 -> C27 */
    {
        PIN_WKUP_GPIO0_3, PIN_MODE(7) | \
        ((PIN_PULL_DIRECTION | PIN_INPUT_ENABLE | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DISABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_4 -> C23 */
    {
        PIN_WKUP_GPIO0_4, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_5 -> F26 */
    {
        PIN_WKUP_GPIO0_5, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_6 -> E25 */
    {
        PIN_WKUP_GPIO0_6, PIN_MODE(7) | \
        ((PIN_INPUT_ENABLE  | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DISABLE & ~PIN_PULL_DIRECTION))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_7 -> F28 */
    {
        PIN_WKUP_GPIO0_7, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE  | PIN_OUTPUT_DISABLE	) & (~PIN_PULL_DIRECTION))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_10 -> F27 */
    {
        PIN_WKUP_GPIO0_10, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_11 -> F25 */
    {
        PIN_WKUP_GPIO0_11, PIN_MODE(7) | \
        ((PIN_PULL_DIRECTION | PIN_INPUT_ENABLE  | PIN_OUTPUT_DISABLE ) & (~PIN_PULL_DISABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_14 -> B24 */
    {
        PIN_WKUP_GPIO0_14, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_15 -> D25 */
    {
        PIN_WKUP_GPIO0_15, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_28 -> G17 */
    {
        PIN_MCU_OSPI0_CSN1, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_29 -> F14 */
    {
        PIN_MCU_OSPI0_CSN2, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_30 -> F17 */
    {
        PIN_MCU_OSPI0_CSN3, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_31 -> A19 */
    {
        PIN_MCU_OSPI1_CLK, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_32 -> B20 */
    {
        PIN_MCU_OSPI1_LBCLKO, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_33 -> B19 */
    {
        PIN_MCU_OSPI1_DQS, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_34 -> D21 */
    {
        PIN_MCU_OSPI1_D0, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_35 -> G20 */
    {
        PIN_MCU_OSPI1_D1, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE  | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_36 -> C20 */
    {
        PIN_MCU_OSPI1_D2, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE  | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_37 -> A20 */
    {
        PIN_MCU_OSPI1_D3, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE  | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DIRECTION))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_38 -> D20 */
    {
        PIN_MCU_OSPI1_CSN0, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_39 -> C21 */
    {
        PIN_MCU_OSPI1_CSN1, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_49 -> K26 */
    {
        PIN_WKUP_GPIO0_49, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_54 -> B27 */
    {
        PIN_MCU_SPI0_CLK, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_55 -> D24 */
    {
        PIN_MCU_SPI0_D0, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_56 -> G27 */
    {
        PIN_WKUP_GPIO0_56, PIN_MODE(7) | \
        ((PIN_PULL_DIRECTION) & (~PIN_PULL_DISABLE & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_57 -> J26 */
    {
        PIN_WKUP_GPIO0_57, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_66 -> G25 */
    {
        PIN_WKUP_GPIO0_66, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_67 -> J27 */
    {
        PIN_WKUP_GPIO0_67, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_69 -> B25 */
    {
        PIN_MCU_SPI0_D1, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_70 -> B26 */
    {
        PIN_MCU_SPI0_CS0, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_GPIO0 -> WKUP_GPIO0_87 -> J25 */
    {
        PIN_MCU_I2C0_SDA, PIN_MODE(7) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gWkup_gpioPinCfg[] =
{
    {0, TRUE, gWkup_gpio0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gWkup_i2c0PinCfg[] =
{
    /* WKUP_I2C0 -> WKUP_I2C0_SCL -> H24 */
    {
        PIN_WKUP_I2C0_SCL, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* WKUP_I2C0 -> WKUP_I2C0_SDA -> H27 */
    {
        PIN_WKUP_I2C0_SDA, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gWkup_i2cPinCfg[] =
{
    {0, TRUE, gWkup_i2c0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gWkup_system0PinCfg[] =
{
    /* WKUP_SYSTEM0 -> MCU_RESETSTATz -> A23 */
    {
        PIN_MCU_RESETSTATZ, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_SYSTEM0 -> MCU_RESETz -> A26 */
    {
        PIN_MCU_RESETZ, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* WKUP_SYSTEM0 -> MCU_SAFETY_ERRORn -> J23 */
    {
        PIN_MCU_SAFETY_ERRORN, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE | PIN_INPUT_ENABLE) & (~PIN_PULL_DIRECTION))
    },
    /* WKUP_SYSTEM0 -> PMIC_POWER_EN1 -> G26 */
    {
        PIN_PMIC_POWER_EN1, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    /* WKUP_SYSTEM0 -> PORz -> K23 */
    {
        PIN_PORZ, PIN_MODE(0) | \
        ((PIN_PULL_DIRECTION | PIN_INPUT_ENABLE | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DISABLE))
    },
    /* WKUP_SYSTEM0 -> RESET_REQz -> A24 */
    {
        PIN_RESET_REQZ, PIN_MODE(0) | \
        ((PIN_PULL_DIRECTION | PIN_INPUT_ENABLE| PIN_OUTPUT_DISABLE) & (~PIN_PULL_DISABLE))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gWkup_systemPinCfg[] =
{
    {0, TRUE, gWkup_system0PinCfg},
    {PINMUX_END}
};


static pinmuxPerCfg_t gWkup_uart0PinCfg[] =
{
    /* WKUP_UART0 -> WKUP_UART0_RXD -> D28 */
    {
        PIN_WKUP_UART0_RXD, PIN_MODE(0) | \
        ((PIN_INPUT_ENABLE | PIN_OUTPUT_DISABLE) & (~PIN_PULL_DISABLE & ~PIN_PULL_DIRECTION))
    },
    /* WKUP_UART0 -> WKUP_UART0_TXD -> D27 */
    {
        PIN_WKUP_UART0_TXD, PIN_MODE(0) | \
        ((PIN_PULL_DISABLE) & (~PIN_PULL_DIRECTION & ~PIN_INPUT_ENABLE))
    },
    {PINMUX_END}
};

static pinmuxModuleCfg_t gWkup_uartPinCfg[] =
{
    {0, TRUE, gWkup_uart0PinCfg},
    {PINMUX_END}
};


pinmuxBoardCfg_t gJ721S2_MainPinmuxData[] =
{
    {0, gCpsw2gPinCfg},
    {1, gDebugssPinCfg},
    {2, gTimerPinCfg},
    {3, gEhrpwmPinCfg},
    {4, gGpioPinCfg},
    {5, gI2cPinCfg},
    {6, gMcanPinCfg},
    {7, gMmcsdPinCfg},
    {8, gSpiPinCfg},
    {9, gSystemPinCfg},
    {10, gUartPinCfg},
    {PINMUX_END}
};

pinmuxBoardCfg_t gJ721S2_WkupPinmuxData[] =
{
    {0, gMcu_adcPinCfg},
    {1, gMcu_cpsw2gPinCfg},
    {2, gMcu_i2cPinCfg},
    {3, gMcu_mcanPinCfg},
    {4, gMcu_mdioPinCfg},
    {5, gMcu_ospiPinCfg},
    {6, gMcu_uartPinCfg},
    {7, gWkup_debugssPinCfg},
    {8, gWkup_gpioPinCfg},
    {9, gWkup_i2cPinCfg},
    {10, gWkup_systemPinCfg},
    {11, gWkup_uartPinCfg},
    {PINMUX_END}
};
