/*
 *  Copyright (c) 2021 Texas Instruments Incorporated
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

 /**
 *  \file     sdl_dcc_funcTest.c
 *
 *  \brief    This Test application demonstrates comparison of 2 clock
 *              sources.
 *
 *  \details    Different clock sources are provided to Counter 1 (Test Clock)
 *              and Counter 0 (Reference Clock).
 *              This application configures the DCC module to generate
 *              interrupt, when Counter 1 reaches 0.
 *              1. When Counter 0 + Valid Counter & Counter 1 reaches 0 at same
 *                   time, Completion Interrupt is generated.
 *              2. Error Interrupt is generated when
 *                  2.1. Counter 1 reaches 0 before Counter 0 reaches 0
 *
 *              Other Conditions where an error interrupt can be generated by
 *              DCC but not demonstrated by this demo application.
 *                  2.2. Counter 1 reaches 0 after Counter 1 & VALID0 reaches 0
 *                  2.3. Source sources to Counter 0 & Counter 1 are not present
 **/

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */

#include<string.h>
#include "dcc.h"
#include "fusa_application.h"
/*===========================================================================*/
/*                         Declarations                                      */
/*===========================================================================*/

#define DCC_SEED_CONST_1	(1U)
#define DCC_SEED_CONST_2	(2U)
#define DCC_SEED_CONST_3	(3U)
#define DCC_SEED_CONST_10	(10U)

#if defined (DEBUG_DCC_MAGNA)
/**
 * \brief   Utility function to print on UART console/CCS console
 */
static void SDL_DCCAppPrint(const char * str);
/**
 * \brief   This function returns clock frequencies
 *
 * \param   dccInst     Instance of DCC
 * \param   clk0Src     Clock source for counter 0
 * \param   clk1Src     Clock source for counter 1
 * \param   clk0Freq    Clock frequency for counter 0 in KHz
 * \param   clk1Freq    Clock frequency for counter 1 in KHz
 *
 * \retval  status      Negative number in case of errors
 */
static int32_t SDL_DCCAppGetClkfreqKHz(uint32_t dccInst,
                                    uint32_t clk0Src, uint32_t clk1Src,
                                    uint32_t *clk0Freq, uint32_t *clk1Freq);
/**
 * \brief   This function returns least integral ratio for given clocks.
 *
 * \param   refClkFreq      Reference clock frequency in KHz.
 * \param   testClkFreq     Test clock frequency in KHz.
 * \param   refClkRatioNum  Reference clock ratio number.
 * \param   testClkRatioNum Test clock ratio number.
 *
 * \retval  None.
 */
static void SDL_DCCAppGetClkRatio(uint32_t  refClkFreq,
                              uint32_t  testClkFreq,
                              uint32_t *refClkRatioNum,
                              uint32_t *testClkRatioNum);

/**
 * \brief   This function returns seed value for COUNT1.
 *
 * \param   refClkFreq      Reference clock frequency in KHz.
 * \param   testClkFreq     Test clock frequency in KHz.
 * \param   refClkRatioNum  Reference clock ratio number.
 * \param   testClkRatioNum Test clock ratio number.
 * \param   drfitPer        Allowed drift in test clock in percentage.
 * \param   configParams    DCC configuration parameters.
 *                          Refer enum #SDL_DCC_config.
 *
 * \retval  None.
 */
static void SDL_DCCAppSetSeedVals(uint32_t           refClkFreq,
                              uint32_t           testClkFreq,
                              uint32_t           refClkRatioNum,
                              uint32_t           testClkRatioNum,
                              uint32_t           drfitPer,
                              SDL_DCC_config  *configParams);

/**
 * \brief   This function register ISR for a given instance of DCC
 *
 *
 * \param   dccInst     Instance of DCC
 *
 * \retval  SDL_PASS on successful interrupt handler registration.
 */
static int32_t SDL_DCCAppRegisterIsr(uint32_t dccInst);

/**
 * \brief   ISR for done interrupt, set a global flag
 *
 * \retval  None
 */
static void SDL_DCCAppDoneIntrISR(uintptr_t handle);
#endif /*(DEBUG_DCC_MAGNA)*/
static void SDL_DCCCalculateSeeds(SDL_DCC_clkFreq srcFreq, SDL_DCC_clkFreq testFreq,
                                  uint32_t* clk0Seed, uint32_t* clk1Seed, 
                                  uint32_t* validSeed);
/* ========================================================================== */
/*                            Global Variables                                */
/* ========================================================================== */
#define CDD_Safety_START_SEC_VAR_INIT_UNSPECIFIED
#include "CDD_Safety_MemMap.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */

#if defined (DEBUG_DCC_MAGNA)
static volatile uint32_t isrFlag = 0u;
#endif /*(DEBUG_DCC_MAGNA)*/

#define CDD_Safety_STOP_SEC_VAR_INIT_UNSPECIFIED
#include "CDD_Safety_MemMap.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */
/**< Flag used to indicate occurrence of the completion interrupt */
/* ========================================================================== */
/*                          Function Definitions                              */
/* ========================================================================== */

#define CDD_Safety_START_SEC_CODE
#include "CDD_Safety_MemMap.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */

#if defined (DEBUG_DCC_MAGNA)
int32_t SDL_DCC_funcTest(void)
{
  /* DD-ID: {6939AEDC-0DB2-42b0-BEC1-7BE2A1949FE5}*/
    int32_t retVal, i, srcClk, testClk;
    uint32_t clk0Freq, clk1Freq, refClkRatioNum, testClkRatioNum;
    SDL_DCC_config configParams;
	SDL_DCC_staticRegs staticRegs;
	
	/* Steps
    1. Determine the clock frequencies for the sources
    2. Figure out the seed values for successful completion
    3. Configure Interrupts for normal completion
    4. Configure DCC instance
    5. Enable DCC
    6. Wait for normal completion
    7. Change reference clock source to higher frequency source (to simulate
        clock change)
    8. Configure DCC and Enable
    9. Wait for error notification
    */
     (void)memset((void*)&configParams, 0, sizeof(configParams));
#if defined (SDL_APP_DCC_UART_PRINTS_ENABLED)
    SDL_DCCAppPrint("\r\n" APP_DCC_STR ": Start\r\n");
	
    UART_printf("\nINSTANCE: DCC0\n");
#endif
	
	/* This loop cycling for 2 clock sources to achieve qualification testing.
		case 0:  Test clock   = MAIN PLLCTRL (MAIN_SYSCLK0)
		         Source clock = HFOSC0
		case 1:  Test clock   = MAIN PLLCTRL (MAIN_SYSCLK0)
		         Source clock = HFOSC1
	*/
	for(i=0; i<2; i++)
	{
		switch(i)
		{
			case 0:
					srcClk = SDL_DCC_CLK0_SRC_CLOCK0_0;
					testClk = SDL_DCC_CLK1_SRC_CLOCKSRC3;
#if defined (SDL_APP_DCC_UART_PRINTS_ENABLED)
					UART_printf("\n Reference clock source: HFOSC0 \n");
					UART_printf(" Test clock source: MAIN_SYSCLK0 \n");
#endif
			break;
					
			case 1:
					srcClk = SDL_DCC_CLK0_SRC_CLOCK0_1;
					testClk = SDL_DCC_CLK1_SRC_CLOCKSRC7;
#if defined (SDL_APP_DCC_UART_PRINTS_ENABLED)
					UART_printf("\n Reference clock source: HFOSC1 \n");
					UART_printf(" Test clock source: SERDES\n");
#endif
			break;

			default:
				/* Do nothing */
				break;
		}
	
		/* Step 1 Determine the clock frequencies for the sources */
		retVal = SDL_DCCAppGetClkfreqKHz(APP_DCC_MODULE_INST,
                                   srcClk,
                                   testClk,
                                   &clk0Freq, &clk1Freq);
		
		if (SDL_PASS == retVal)
		{
			/* Step 2 Figure out the seed values for successful completion */
			/* Get clock ratio */
			SDL_DCCAppGetClkRatio(clk0Freq,
								clk1Freq,
								&refClkRatioNum,
								&testClkRatioNum);
		
			configParams.mode    = APP_DCC_MODE;
			configParams.clk0Src = srcClk;
			configParams.clk1Src = testClk;
			
			/* Get the seed values for given clock selections and allowed drift */
			SDL_DCCAppSetSeedVals(clk0Freq,
								clk1Freq,
								refClkRatioNum,
								testClkRatioNum,
								APP_DCC_TEST_CLOCK_SRC_1_DRIFT,
								&configParams);
		
			/* Step 3 Configure Interrupts for normal completion */
			SDL_DCCAppRegisterIsr(APP_DCC_MODULE_INST);
		
			/* Step 4 Configure DCC instance */
			retVal = SDL_DCC_configure(SDL_DCC_INST_DCC0, &configParams);
			
			if (SDL_PASS == retVal)
			{
				retVal = SDL_DCC_verifyConfig(SDL_DCC_INST_DCC0, &configParams);
			}
			else
			{
				retVal = SDL_EFAIL;
			}
			
			if (SDL_PASS == retVal)
			{
				/* Clear the interrupt flag */
				isrFlag = 0U;
		
				SDL_DCC_getStaticRegs(SDL_DCC_INST_MCU_DCC0, &staticRegs);
#if defined (SDL_APP_DCC_UART_PRINTS_ENABLED)
				SDL_DCCAppPrint(APP_DCC_STR ": DCC configured \n");
		
				SDL_DCCAppPrint(APP_DCC_STR ": Enabling DCC\n");
#endif
				
				/* Step 5 Enable DCC */
				SDL_DCC_enable(SDL_DCC_INST_DCC0);
		
#if defined (SDL_APP_DCC_UART_PRINTS_ENABLED)
				SDL_DCCAppPrint(APP_DCC_STR ": Waiting for some time to perform Continuous mode \n");
#endif
				
				volatile int32_t i = 0;
				/* Wait for the ESM interrupt to report the error */
				do {
					i++;
					if (i > 0x0FFFFFFF)
					{
						/* Timeout for the wait */
						break;
					}
				} while (isrFlag == DCC_NO_INTERRUPT);
				
				if (isrFlag == DCC_INTERRUPT)
				{
#if defined (SDL_APP_DCC_UART_PRINTS_ENABLED)
					SDL_DCCAppPrint(APP_DCC_STR ": DCC Generated Error interrupt when it is not expected \n");
#endif
					isrFlag = DCC_NO_INTERRUPT;
					retVal = SDL_EFAIL;
				}
				else
				{
#if defined (SDL_APP_DCC_UART_PRINTS_ENABLED)
					SDL_DCCAppPrint(APP_DCC_STR ": DCC module is disabled \n");
#endif
					/* Step 6 Disable DCC */
					SDL_DCC_disable(SDL_DCC_INST_DCC0);
					retVal = SDL_PASS;
				}
			}
		}
	}
#if defined (SDL_APP_DCC_UART_PRINTS_ENABLED)
	UART_printf("\n\n\n Reference clock source: HFOSC1 \n");
	UART_printf(" Test clock source: MCAN \n");
#endif
	
	
    retVal = SDL_DCCAppGetClkfreqKHz(APP_DCC_MODULE_INST,
                                     APP_DCC_REF_CLOCK_SRC_0,
                                     APP_DCC_TEST_CLOCK_SRC_1,
                                     &clk0Freq, &clk1Freq);
	
    /* Step 7. Change reference clock source to higher frequency source 
               OR change the clock ratios to introduce the error
     */
    if (retVal == SDL_PASS)
    {	
        /* Step 8. Configure DCC and Enable */
        /* Change reference clock source to higher frequency source */
#if defined (SDL_APP_DCC_UART_PRINTS_ENABLED)
        SDL_DCCAppPrint(APP_DCC_STR ": Changing the clock source \n");
#endif
        configParams.clk1Src = APP_DCC_TEST_CLOCK_SRC_1_HIGHER;

        retVal = SDL_DCC_configure(SDL_DCC_INST_DCC0, &configParams);
#if defined (SDL_APP_DCC_UART_PRINTS_ENABLED)
        SDL_DCCAppPrint(APP_DCC_STR ": Enabling DCC and waiting for "
                        "Error interrupt \n");
#endif
	    /* Enable ERROR interrupt */
	    SDL_DCC_enableIntr(SDL_DCC_INST_DCC0, SDL_DCC_INTERRUPT_ERR);
        SDL_DCC_enable(SDL_DCC_INST_DCC0);

        /* Step 9. Wait for error notification */
			
		volatile int32_t i = 0;
		/* Wait for the ESM interrupt to report the error */
		do {
			i++;
			if (i > 0x0FFFFFFF)
			{
				/* Timeout for the wait */
				break;
			}
		} while (isrFlag == DCC_NO_INTERRUPT);
			
		if (isrFlag == DCC_INTERRUPT)
		{
#if defined (SDL_APP_DCC_UART_PRINTS_ENABLED)
			SDL_DCCAppPrint(APP_DCC_STR ": DCC Generated Error interrupt \n");
			SDL_DCCAppPrint(APP_DCC_STR ": Indicating clock drift/change \n");
#endif
			isrFlag = DCC_NO_INTERRUPT;
			/* Disabling the DCC */
			SDL_DCC_disable(SDL_DCC_INST_DCC0);
		}	
		else
		{
#if defined (SDL_APP_DCC_UART_PRINTS_ENABLED)
			SDL_DCCAppPrint(APP_DCC_STR ": Could not generate Error interrupt \n");
#endif
			retVal = SDL_EFAIL;
		}
    }
    
    else
    {
#if defined (SDL_APP_DCC_UART_PRINTS_ENABLED)
        SDL_DCCAppPrint(APP_DCC_STR ": Error : Could not derive clock "
                        "frequency!!!\r\n");
#endif
    }

    return retVal;
}
#endif /*DEBUG_DCC_MAGNA*/

int32_t dcc_init_inst(uint32_t dccInst)
{
  /* DD-ID:{F9CA295C-BF65-4ba7-882F-C9D284D69327}*/
    SDL_DCC_config configParams;
	SDL_DCC_staticRegs staticRegs;
    int32_t retVal;

    configParams.clk0Src = SDL_APP_DCC_cfg[dccInst].srcClk;
    configParams.clk1Src = SDL_APP_DCC_cfg[dccInst].testClk;
    configParams.mode    = SDL_APP_DCC_cfg[dccInst].mode;

    /* Calculate valid, count0 and count1 */ 
    SDL_DCCCalculateSeeds(SDL_APP_DCC_cfg[dccInst].srcFreq, SDL_APP_DCC_cfg[dccInst].testFreq, 
        &configParams.clk0Seed, &configParams.clk1Seed, &configParams.clk0ValidSeed);


	retVal = SDL_DCC_configure(SDL_APP_DCC_cfg[dccInst].instance, &configParams);
	
	if (SDL_PASS == retVal)
	{
		retVal = SDL_DCC_verifyConfig(SDL_APP_DCC_cfg[dccInst].instance, &configParams);
	}
	else
	{
		retVal = SDL_EFAIL;
	}
	
	if (SDL_PASS == retVal)
	{
#if defined (SDL_APP_DCC_UART_PRINTS_ENABLED)
		SDL_DCCAppPrint(APP_DCC_STR ": DCC configured \n");
		SDL_DCCAppPrint(APP_DCC_STR ": Enabling DCC\n");
#endif
		(void)SDL_DCC_getStaticRegs(SDL_APP_DCC_cfg[dccInst].instance, &staticRegs);
		(void)SDL_DCC_enableIntr(SDL_APP_DCC_cfg[dccInst].instance, SDL_DCC_INTERRUPT_ERR);
		(void)SDL_DCC_enable(SDL_APP_DCC_cfg[dccInst].instance);
	    (void)memcpy((SDL_DCC_staticRegs *)&(DCC_staticRegs[SDL_APP_DCC_cfg[dccInst].instance]), (SDL_DCC_staticRegs *)&(staticRegs), sizeof(staticRegs));
    }


    return retVal;
}

/* ========================================================================== */
/*                 Internal Function Definitions                              */
/* ========================================================================== */

#if defined (SDL_APP_DCC_UART_PRINTS_ENABLED)
static void SDL_DCCAppPrint(const char * str)
{
  /* DD-ID: {F3F75249-9034-4ad8-AD0F-C201E0795E3C}*/
    UART_printf(str);
}
#endif

#if defined (DEBUG_DCC_MAGNA)
static int32_t SDL_DCCAppGetClkfreqKHz(uint32_t dccInst,
                                        uint32_t clk0Src, uint32_t clk1Src,
                                        uint32_t *clk0Freq, uint32_t *clk1Freq)
{
    /* DD-ID: {8609B7F6-DE56-4c47-8456-087F59A130B8}*/
    int32_t retVal;
    switch (dccInst)
    {
        case SDL_DCC0_BASE :
            
                /* 25 MHz */
                *clk0Freq = APP_DCC_REF_CLOCK_FREQ_IN_KHZ;
                retVal = SDL_PASS;
            
                /* 60 MHz */
                *clk1Freq = APP_DCC_TEST_CLOCK_FREQ_IN_KHZ;
				
				retVal = SDL_PASS;
            
        break;

        default :

#if defined (SDL_APP_DCC_UART_PRINTS_ENABLED)
            SDL_DCCAppPrint(APP_DCC_STR ": Error : DCC Instance not supported in"
                        " this example !!!\r\n");
#endif
			retVal = SDL_EFAIL;
        break;
    }
    return (retVal);
}

static void SDL_DCCAppGetClkRatio(uint32_t  refClkFreq,
                              uint32_t  testClkFreq,
                              uint32_t *refClkRatioNum,
                              uint32_t *testClkRatioNum)
{
     /* DD-ID: {E9AFB3A0-A5F9-4c6e-9FAC-B62B9F37B91A}*/
    uint32_t loopCnt, hcf = 1U;

    for (loopCnt = 1;
         (loopCnt <= refClkFreq) || (loopCnt <= testClkFreq);
         loopCnt++)
    {
        if ((refClkFreq % loopCnt == 0) && (testClkFreq % loopCnt == 0))
        {
            hcf = loopCnt;
        }
    }
    *refClkRatioNum  = (refClkFreq / hcf);
    *testClkRatioNum = (testClkFreq / hcf);
}
#endif	/*(DEBUG_DCC_MAGNA)*/

/* DCC operation summary:
    1. count0 and valid are decremented by clock0 and count1 is decremented by clock 1
    2. Both count0 and count1 start decrementing at the same time
    2. After count0 expires count0 starts decrementing
    3. count1 needs to expire before valid expires
   This is example code from TI <Continuous Monitor of the PLL Frequency With the DCC> 
    1. Minimum valid count is determined by synchronication and digitization errors 
        if f_clk0 < f_clk1, then valid_min = 10
        else, valid_min = 2(2*f_clk0/f_clk1 + 3)
    2. Given error allowance(1/APP_DCC_RESOLUTION) calculate count0 and count1 
        (0.5 * T_valid) / T_1 = 1 / Resolution = error allowance 
        T_0 + 0.5 * T_valid = T_1
        count0 = T_0 * f_clk0 
        count1 = T_1 * f_clk1 
        valid  = T_valid * f_clk0
*/
static void SDL_DCCCalculateSeeds(SDL_DCC_clkFreq srcFreq, SDL_DCC_clkFreq testFreq, uint32_t* clk0Seed, uint32_t* clk1Seed, uint32_t* validSeed)
{
  /* DD-ID: {19B26550-B194-4836-8867-2E847CFBB5B6}*/
    uint32_t duration;
    float64_t tempclk1Seed;

    if (testFreq > srcFreq)
    {
        *validSeed = DCC_SEED_CONST_10;
    }
    else
    {
        *validSeed = DCC_SEED_CONST_2 * ((DCC_SEED_CONST_2 *(srcFreq / testFreq) + DCC_SEED_CONST_1) + DCC_SEED_CONST_3);
    }

    duration = (*validSeed) * APP_DCC_RESOLUTION / DCC_SEED_CONST_2;
    *clk0Seed = duration - (*validSeed) / DCC_SEED_CONST_2;
    tempclk1Seed = (double)duration / (double)srcFreq * (double)testFreq;
    *clk1Seed = (uint32_t)tempclk1Seed;
}

#if defined (DEBUG_DCC_MAGNA)
static void SDL_DCCAppSetSeedVals(uint32_t           refClkFreq,
                              uint32_t           testClkFreq,
                              uint32_t           refClkRatioNum,
                              uint32_t           testClkRatioNum,
                              uint32_t           drfitPer,
                              SDL_DCC_config *configParams)
{
    /* DD-ID: {F32AF8DE-E23C-4453-9819-E493E0DF1259}*/
    uint32_t maxFreqKHz, maxCntLimit;
    uint32_t maxRefCnt, minRefCnt;
    uint64_t mulVar;

    /* Find maximum frequency between test and reference clock */
    if (refClkFreq > testClkFreq)
    {
        maxFreqKHz  = refClkFreq;
        maxCntLimit = APP_DCC_SRC0_MAX_VAL;
    }
    else
    {
        maxFreqKHz  = testClkFreq;
        maxCntLimit = APP_DCC_SRC1_MAX_VAL;
    }
    /* Calculate seed values for 0% drift */
    if (maxFreqKHz == refClkFreq)
    {
        configParams->clk0Seed = maxCntLimit / refClkRatioNum;
        configParams->clk0Seed = configParams->clk0Seed * refClkRatioNum;
        mulVar = ((uint64_t) (configParams->clk0Seed) *
                  (uint32_t) (testClkRatioNum));
        configParams->clk1Seed   = (uint32_t) (mulVar / refClkRatioNum);
        configParams->clk0ValidSeed = refClkRatioNum;
    }
    else
    {
        configParams->clk1Seed = maxCntLimit / testClkRatioNum;
        configParams->clk1Seed = configParams->clk1Seed * testClkRatioNum;
        mulVar = ((uint64_t) (configParams->clk1Seed) *
                  (uint32_t) (refClkRatioNum));
        configParams->clk0Seed   = (uint32_t) (mulVar / testClkRatioNum);
        configParams->clk0ValidSeed = 1U;
    }
    /* Applying allowed drift */
    if (((APP_DCC_SRC0_MAX_VAL + APP_DCC_SRC0_VALID_MAX_VAL) <
         (configParams->clk0Seed * (100U + drfitPer) / 100U)))
    {

#if defined (SDL_APP_DCC_UART_PRINTS_ENABLED)
        /* Seed values with drift exceeds maximum range */
        SDL_DCCAppPrint(APP_DCC_STR ": Seed values with drift exceeds"
                        " allowed range\n");
        SDL_DCCAppPrint(APP_DCC_STR ": Application will run with 0% "
                        " allowed drift\n");
#endif
    }
    else if (100U < drfitPer)
    {
#if defined (SDL_APP_DCC_UART_PRINTS_ENABLED)
        /* Error percentage is greater than 100 */
        SDL_DCCAppPrint(APP_DCC_STR ": Warning Wrong drift %,Not applying drift\n");
        SDL_DCCAppPrint(APP_DCC_STR ": Application will run with 0% drift\n");
#endif
    }
    else
    {
        maxRefCnt = (configParams->clk0Seed * (100U + drfitPer) / 100U);
        minRefCnt = (configParams->clk0Seed * (100U - drfitPer) / 100U);
        if (APP_DCC_SRC0_VALID_MAX_VAL < (maxRefCnt - minRefCnt))
        {
#if defined (SDL_APP_DCC_UART_PRINTS_ENABLED)
            SDL_DCCAppPrint(APP_DCC_STR ": Warning Seed value for valid count "
                        "exceeds allowed range.\n");
            SDL_DCCAppPrint(APP_DCC_STR "Application will run with 0% allowed"
                        " drift.\n");
#endif
        }
        else
        {
            if (maxRefCnt == minRefCnt)
            {
                configParams->clk0ValidSeed = 1U;
            }
            else
            {
                configParams->clk0Seed   = minRefCnt;
                configParams->clk0ValidSeed = (maxRefCnt - minRefCnt);
            }
        }
    }

#if defined (SDL_APP_DCC_UART_PRINTS_ENABLED)
    SDL_DCCAppPrint(APP_DCC_STR ": Seed values calculation done.\n");
#endif
}

static int32_t SDL_DCCAppRegisterIsr(uint32_t dccInst)
{
  /* DD-ID: {54B4433C-3272-4874-A390-08FCDFF4547E}*/
    int32_t retVal = SDL_EFAIL;
    uint32_t dccInt;
    OsalRegisterIntrParams_t intrPrms;
    OsalInterruptRetCode_e osalRetVal;
    HwiP_Handle hwiHandle;

    Osal_RegisterInterrupt_initParams(&intrPrms);
    intrPrms.corepacConfig.arg          = (uintptr_t)0;
    intrPrms.corepacConfig.priority     = 1U;
    intrPrms.corepacConfig.corepacEventNum = 0U; /* NOT USED ? */

    switch (dccInst)
    {
        case SDL_DCC0_BASE :
		
            dccInt = SDLR_ESM0_ESM_LVL_EVENT_DCC0_INTR_ERR_LEVEL_0;
			
            intrPrms.corepacConfig.isrRoutine   = &SDL_DCCAppDoneIntrISR;

            retVal = SDL_PASS;
        break;

        default :
			/* Do nothing */
#if defined (SDL_APP_DCC_UART_PRINTS_ENABLED)
            SDL_DCCAppPrint(APP_DCC_STR ": Error : DCC Instance not supported in"
                        " this test !!!\r\n");
#endif
        break;
    }
    if (SDL_PASS == retVal)
    {
        intrPrms.corepacConfig.intVecNum = dccInt;

        osalRetVal = Osal_RegisterInterrupt(&intrPrms, &hwiHandle);
        if(OSAL_INT_SUCCESS != osalRetVal)
        {
            retVal = SDL_EFAIL;

#if defined (SDL_APP_DCC_UART_PRINTS_ENABLED)
            SDL_DCCAppPrint(APP_DCC_STR ": Error Could not register ISR !!!\n");
#endif
        }
    }
    return (retVal);
}

static void SDL_DCCAppDoneIntrISR(uintptr_t handle)
{
  /* DD-ID: {DB37B332-C32B-42a0-AEAC-A325B20639EF}*/
    SDL_DCC_clearIntr(SDL_DCC_INST_DCC0, SDL_DCC_INTERRUPT_DONE);
    isrFlag  = 1U;
}

static void SDL_DCCIntrDisable(uint32_t intsrc)
{
  /* DD-ID: {2FAD8AA8-DA53-4d5c-8FC0-172D8C55EA8F}*/
    /* Clear ESM registers. */

    SDL_ESM_disableIntr(SDL_ESM0_CFG_BASE, intsrc);
    SDL_ESM_clrNError(SDL_ESM_INST_MAIN_ESM0);

}
#endif /*(DEBUG_DCC_MAGNA)*/

int32_t SDL_ESM_DCC_applicationCallbackFunction(SDL_ESM_Inst esmInst, SDL_ESM_IntType esmIntrType,
                                            uint32_t grpChannel,  uint32_t index, uint32_t intSrc, void *arg)
{
    /* DD-ID: {5CF4F492-3327-4453-AAA6-FADB407EBC18}*/
    Fusa_Application_ErrorLogForDID((uint8_t)e_errLog_DCC, (uint8_t)TRUE);
    int32_t retVal = SDL_PASS;
    (void)esmIntrType;
    (void)grpChannel;
    (void)arg;
    (void)index;

    switch (esmInst)
    {
    default:
    case SDL_ESM_INST_WKUP_ESM0:
        (void)SDL_ESM_disableIntr((uint32_t)SDL_WKUP_ESM0_CFG_BASE, intSrc);
        if (intSrc == SDLR_WKUP_ESM0_ESM_LVL_EVENT_GLUELOGIC_HFOSC0_CLKLOSS_GLUE_REF_CLK_LOSS_DETECT_OUT_0) 
        {
            Sdl_Application_SetClkDetErrorFlag();
        }
        break;
    case SDL_ESM_INST_MCU_ESM0:
        (void)SDL_ESM_disableIntr((uint32_t)SDL_MCU_ESM0_CFG_BASE, intSrc);
        if ((intSrc == SDLR_MCU_ESM0_ESM_LVL_EVENT_MCU_PLLFRACF2_SSMOD0_LOCKLOSS_IPCFG_0) || 
            (intSrc == SDLR_MCU_ESM0_ESM_LVL_EVENT_MCU_PLLFRACF2_SSMOD1_LOCKLOSS_IPCFG_0))
        {
            Sdl_Application_SetPllSlipMcuErrorFlag();
        }
        else if ((intSrc == SDLR_MCU_ESM0_ESM_LVL_EVENT_MCU_DCC0_INTR_ERR_LEVEL_0) ||
                 (intSrc == SDLR_MCU_ESM0_ESM_LVL_EVENT_MCU_DCC1_INTR_ERR_LEVEL_0))
        {
            Sdl_Application_SetMcuDCCErrorFlag();
        }
        else
        {
             /* Do nothing */
        }
        break;
    case SDL_ESM_INST_MAIN_ESM0:
        (void)SDL_ESM_disableIntr((uint32_t)SDL_ESM0_CFG_BASE, intSrc);
        if ((intSrc == SDLR_ESM0_ESM_LVL_EVENT_DCC4_INTR_ERR_LEVEL_0) ||
            (intSrc == SDLR_ESM0_ESM_LVL_EVENT_DCC6_INTR_ERR_LEVEL_0) ||
            (intSrc == SDLR_ESM0_ESM_LVL_EVENT_DCC8_INTR_ERR_LEVEL_0))
        {
            Sdl_Application_SetMainDCCErrorFlag();
        }
        else if (intSrc == SDLR_ESM0_ESM_LVL_EVENT_PLLFRACF2_SSMOD14_LOCKLOSS_IPCFG_0)
        {
            Sdl_Application_SetPllSlipMainErrorFlag();
        }
        else
        { 
            /* Do nothing */
        }
        break;
    }

#if defined (SDL_APP_DCC_UART_PRINTS_ENABLED)
    UART_printf("\nInterrupt is generated to ESM\n");
    UART_printf("    ESM Call back function called : instType 0x%x, intType 0x%x, " \
                "grpChannel 0x%x, index 0x%x, intSrc 0x%x \n",
                esmInst, esmIntrType, grpChannel, index, intSrc);
    UART_printf("    Take action \n\n");
#endif
    
    /* For clearing the interrupt */
    (void)SDL_ESM_clrNError(esmInst);
	
    return retVal;
}
#define CDD_Safety_STOP_SEC_CODE
#include "CDD_Safety_MemMap.h" /* PRQA S 5087 */ /* MD_MSR_MemMap */
/********************************* End of file ******************************/
