/*
 * US_ObjDet_Global.h
 *
 *  Created on: Aug 9, 2021
 *      Author: jonapais
 */

#ifndef US_OBJDET_GLOBAL_H_
#define US_OBJDET_GLOBAL_H_

#include "US_SnrData_Typedefs_Global.h"
#include "US_PlatformCfg_Global.h"
/*
 *	OBJECT DETECTION VERSION: V_OD_25_03_23_00
 * 
 *  Change Log:
 *  ----------
 *  jonapais   23Mar25   V_OD_25_03_23_00
 *  1. Confidence capping when flanked 2.0.
*
 *  jonapais   13Mar25   V_OD_25_03_13_00
 *  1. Ego direction change results in opposite direction group conf cap.
 *     With additional debug.
 *
 *  jonapais   10Mar25   V_OD_25_03_10_00
 *  1. Update logic for group clearing, now conf reduction,
 *     of a group that has confirmed change of direction
 *     of motion.  aka Group clearing fix.
 *
 *  jonapais   7Mar25   V_OD_25_03_07_00
 *  1.  Enable radial matches for lone direct sides when not in FAPA.
 *  2.  Also enable radial matches for lone directs from side sensors
 *      when _gDbg_EnableSideRadMatch != Zero (for testing).
 *
 *  jonapais   4Mar25   V_OD_25_03_04_00
 *  1. Rewrote clear map in AgeAndAdjust/UssOD_GetAndUpdateGrpAllowLevel
 *     to reduce confidence of map in the direction away
 *     from motion.  Used to clear map on prndl change,
 *     not only reduce confidence after motion confirmed.
 *
 *  jreynolds  6Mar25   V_OD_25_03_06_00
 *  1. Merging old QAC fixes from develop branch
 *
 *  jonapais   3Mar25   V_OD_25_03_03_00
 *  1. Fixed bug with point sweeper min X value is a distance,
 *     and not a min X value.  Points will never qualify.
 *
 *  jonapais   27Feb25   V_OD_25_02_27_00
 *  1. For DynTargetDeadPntSweeper implemented new logic
 *     to correct for out of tube points being swept up
 *     improperly, when no target pull away.
 *
 *  jonapais   22Feb25   V_OD_25_02_22_00
 *  1. Clean up of FAPA API flags.
 *
 *  jreynolds  21Feb25   V_OD_25_02_21_02
 *  1. Actually turned off square fov in triang.c
 * 
 *  jreynolds  21Feb25   V_OD_25_02_21_01
 *  1. Reset square fov back to 200cm for use with ReduxFOV sensor calibration
 *  2. Small interface change in US_ObjDetHeight.c for DNN
 * 
 *  jonapais   21Feb25   V_OD_25_02_21_00
 *  1. Fixed deprecated latched flag from UssOD_CapConfForPntsWhenFlanked
 *
 *  jonapais   20Feb25   V_OD_25_02_20_03
 *  1. Removed extra instance of UssOD_IsGrpGeomHigh
 *
 *  jonapais   20Feb25   V_OD_25_02_20_02
 *  1. Added temp flags to manage FAPA_API feature selection,
 *     US_D_USE_FAPA_API         (ME_TRUE)
 *     US_D_USE_FAPA_API_OD_TMP  (ME_FALSE)
 *     OD_D_USE_FAPA_FEATURE_WITH_NO_API   (ME_TRUE)
 *     Intent is to revert US_D_USE_FAPA_API_OD_TMP once other
 *     consumers begin using OD_D_USE_FAPA_FEATURE_WITH_NO_API
 *     in conjunction with US_D_USE_FAPA_API == ME_FALSE.
 * 
 *  jonapais   20Feb25   V_OD_25_02_20_01
 *  1. Change:  US_D_OD_CAP_PNT_CONF_WHEN_FLANKED       (ME_TRUE)
 *
 *  jonapais   20Feb25   V_OD_25_02_20_00
 *  1. Correct bug with radial matching of temporal triangulation
 *     improperly set bMergPnts flag which could call point
 *     'walk away' and/or teleporation of merge point.
 *
 *  jonapais   14Feb25   V_OD_25_02_14_00
 *  For DynTargetDeadPntSweeper implemented the following rule changes.
 *  1. Points generated by side sensors may be capped by algo.
 *  2. Points outside the vehicle driving tube that are old (ca >= 4)
 *     and outside the vehicle driving tube,
 *     and a closer X distance than the closest freshly measured point,
 *     will be capped.
 *  3. DynTargetDeadPntSweeper changed to only run on front of ego.
 * 
 *  jonapais   13Feb25   V_OD_25_02_13_01
 *  1. Extended range of point sweeper to 150cm
 *  2. Point split mitigation is on.
 *  3. Sweeper for pull away countermeasure is on.
 *  4. Change check for new points to be based on meas flag and not cruising age.
 *  5. Lowered confidence for new points to sweep around to 20%.
 *
 *  jonapais   12Feb25   V_OD_25_02_12_00
 *  1. Enable squared off FOV starting at 150cm from bumper..
 *
 *  jonapais   1Feb25   V_OD_25_02_11_00
 *  1. Confidence capping latch removal logic further refined.
 *
 *  jonapais   10eb25   V_OD_25_02_10_01
 *  1. Confidence capping latch removal logic refined.
 *
 *  jonapais   10Feb25   V_OD_25_02_10_00
 *  1. Fix bug with dyn object garbage collection. Y swapped with X.
 *
 *  jonapais   9Feb25   V_OD_25_02_09_01
 *  1. Fix bug with conf latch
 *
 *  jonapais   8Feb25   V_OD_25_02_08_00
 *
 *  1. Refactor dynamic target object pull-away garbage collection
 *     into function DynTargetDeadPntSweeper(uint8_t uGrpIdx)
 *     Calling function after point detection (instead of AgeAndAdjust on
 *     next cycle) in order to achieve faster (same cycle) dying point clean up.
 *
 *  jonapais   7Feb25   V_OD_25_02_07_01
 *
 *  1. Countermeasure enable macro to on.
 *
 *  jonapais   6Feb25   V_OD_25_02_07_00
 *
 *  1. Macros did not end up in repo.  Not sure how it even built. Added them.
 *
 *  Tuning adjustments:
 *  2. Qualifying new points now count as measured
 *  3. Conf of new point >= 30%
 *  4. dx of new and old points must be:  75cm >= dx >= 7.0 cm
 *  5. Radial match dist max = 75cm
 *  6. Crusing age of old points >= 4
 *
 *  jonapais   6Feb25   V_OD_25_02_06_00
 *
 *  1. Added dynamic target object pull-away garbage collection.
 *	   Caps confidence of dying point early under specific conditions.
 *     Cap is not persistent.
 *
 *  jonapais   3Feb25   V_OD_25_02_03_00
 *
 *  1. Disable 2-way D/I meas latching release condition.
 *
 *  jonapais   31Jan25   V_OD_25_01_31_00
 *
 *  1. Fixed latching bug with V_OD_25_01_29_00
 *
 *  BASED ON: V_OD_25_01_29_00
 *
 *  jonapais   29Jan25   V_OD_25_01_29_00 + ENG DEBUG
 *
 *  1. Temporary debug for debug point data.
 *  Note: To be reverted after issue is resolved
 *
 *  jonapais   29Jan25   V_OD_25_01_29_00
 *
 *  1. Fix bug with cache standstill timeout.
 *  Note: Bug introduced in last version (V_OD_25_01_24_00)
 *
 *  BASED ON: V_OD_25_01_11_00
 *  jonapais   11Jan25   V_OD_25_01_24_00
 *  1. Updated pntstat flags to contain persistent history of DI/DD/LD/TD
 *  2. Updated pntstat flags to contain persistent history of conf cap flag
 *  3. Updated PntDebug message to include base distance and new persistent flag
 *  4. Updated PntDebug message to msgID = 2 to reflect changes 1-3
 *  5. Included radial matching for Normal TD points.
 *  6. Fixed bug with point matching with existing group point list. (May have caused double points in past)
 *  7. Restructured confidence capping to utilize new persistent flags and conf capping mechanism.
 *  8. DI measurements are not conf capped, until (or previously) measured (confirmed) by DD/TD/D measurements
 *        or DI measurement made from different originating sensors.
 *  9. Confidence capping is also released any time a point is remeasured <= 150 cm.
 *  10. Turn on direct/direct for inners.
 *  11. Some code clean up.
 *  12. Allow caching of last measuremnt when stationary to support improved D/D triang.
 *
 *  --------------------------------------------------------------
 *  jonapais   11Jan25   V_OD_25_01_11_00 - *ENGINEERING TEST ONLY*
 *  BASED ON: V_OD_25_01_03_00
 *  1. Disable DI Triangulation
 *  2. Reenable DD for inner sensors
 *  3. Enable L0 direct cache to be updated on all sucessful measurement cycles.
 *  4. Set up uEchoCalcFlags and associated enumerations in US_SnrData_Typedefs_Global.h.
 *  5. Removed unnecessary flag for dynamic turn on/off of flanking conf cap.  DISABLED via macro.
 *  6. Removed DEAD code.
 *
 *  --------------------------------------------------------------
 *  jonapais   03Jan25   V_OD_25_01_03_00
 *  1. Radial matching now checked for temporal triangulation.
 *  2. Set up uEchoCalcFlags and associated enumerations in US_SnrData_Typedefs_Global.h.
 *
 *  --------------------------------------------------------------
 *  jonapais   16Dec24   V_OD_24_12_03_00
 *  1. Set US_D_OD_USE_LDPM_ONLY_REAR = FALSE so that lone point matching
 *     can occur on the front bumper.  Also made changes for QAC
 *     with regard to this macro being set to false.
 *
 *  2. Changed arbitration in UssOD_MatchMeasDistWithPntList()
 *     Arbitration priorities (Top is #1):
 *     #1 priority, triang point furthest towards outside of vehicle
 *     #2 priority, triang point towards inside of vehicle, closest to sensor Y coord
 *     #3 priority, un-triang point furthest towards outside of vehicle
 *     Untriangulated points inside the sensor Y location will not match.
 *
 *  --------------------------------------------------------------
 *  jonapais   13Dec24   V_OD_24_12_02_00
 *  1. Fixed bug where bFinishTriang flag was always set to false,
 *     such that temporal dir triang never ran in V24_12_01_00.
 *
 *  2. Fixed bug with long dir triang due to bias matching flag
 *     being on, which blocks lones from matching as bias matching on
 *     requires matched points to be latched triangulations.
 *     Also eliminate bias matching for DD triang, as not needed.
 *
 *  --------------------------------------------------------------
 *  jonapais   04Dec24   V_OD_24_12_01_00
 *  1. FOV checks for temporal triang were only performed in 1 of 3
 *     possible locations.  It was done for point creation, but not
 *     the two oppurtunities to point match.
 *     Moved FOV checks and confidence capping code to above decision 
 *     tree such that FOV will be respected by all 3 point updates.
 *
 *  2. Disabled temporal triangulation when the following conditions 
 *     are met:
 *        - FAPA Active
 *        - Direct distance to sensor is < 50 cm
 *        - Veh speed < 2.0f and > 0.0f
 *     The implication is the algo will drop out and 
 *     Lone Direct triang shall take over.
 *
 *  --------------------------------------------------------------
 *  jonapais    02Dec24   V_OD_24_12_00_00
 *  1. Added tube varification to bias matching point list search.
 *
 *  --------------------------------------------------------------
 *  jonapais    22Nov24   V_OD_24_11_01_00
 *  1. Limit FOV on Temporal Triang for Outers and Sides.
 *     (Inners were already limited.)
 *
 *  --------------------------------------------------------------
 *  jonapais    22Nov24   V_OD_24_11_00_02
 *  1. US_D_OD_USE_CR_DIST_KILL set to TRUE
 *
 *  --------------------------------------------------------------
 *  jonapais    22Nov24   V_OD_24_11_00_01
 *  1. Standstill cache timeout is enabled in V24_11_00_00. 
 *     Change log update only.
 *    
 *
 *  --------------------------------------------------------------
 *  jonapais    22Nov24   V_OD_24_11_00_00
 *  1.  Flanking improvement under noise conditions
 *  2.  Offset bias matching bug fix.
 *  3.  Bias Matching enabled for D-DI triangulation
 *  4.  Disable noise gain boost dist check.
 *  5.  US_D_OD_USE_CR_DIST_KILL set to FALSE
 *  6.  UDAT Adv Debug Pnts split between front and rear busses.  
 *  7.  Standstill cache timeout.
 *
 *
 */

#define US_D_POINTMAP_OUT_SIZE  (96u)

#define US_D_MAX_NUM_SECTORS_CHK        (8u)
#define US_D_MAX_SECTORS_TOTAL          (US_D_MAX_NUM_SECTORS_CHK << ONE)

#define US_D_OD_EPSILON  (1e-4)

/* Needs to be defined in cals */
#define SNR_TYPE_PDC (0u)
#define SNR_TYPE_PSM (1u)

/* Make these cals */
#define SNR_PDC_FOV_2_RAD (US_DEG2RAD(60.0)) // PDC MAX FOV / 2.0
#define SNR_PSM_FOV_2_RAD (US_DEG2RAD(30.0)) // PSM MAX FOV / 2.0
#define SNR_PDC_INNER_FOV_2_RAD (US_DEG2RAD(45.0)) // PDC INNER MAX FOV / 2.0

#define US_D_OD_SQARE_FOV_Y_DIST   (200.0f)

#define US_D_INSTANT_PT_SIGSTR      (800u)

/* Apply odometry to direct distance cache */
#define US_D_OD_USE_DIRECT_DIST_ODO (ME_TRUE)

/*Data Type for Zone Info*/
typedef enum ME_US_E_Zones_e {
    ZONE_OFF = ZERO,
    ZONE1 ,
    ZONE2 ,
    ZONE3 ,
    ZONE4 ,
    ZONE5 ,
    ZONE6 ,
    ZONE7 ,
    ZONE8 ,
    ZONE_NO_OBSTACLE,
    ZONE10,
    ZONE11,
    ZONE_RESERVED_12,    // Not used.
    ZONE_RESERVED_13,    // Not used.
    ZONE_SENSOR_BLOCKED, // Not used. Separate blocked sensor message
    ZONE_SNA             // Not used.
} ME_US_E_Zones_t;

typedef enum
{
    OD_GRP_ALL_ALLOW = ZERO,
    OD_GRP_SUPPRESS,
    OD_GRP_REDUCE_CONF,
    OD_GRP_CLR_N_SUPPRESS,
    OD_GRP_MAX
} US_E_Grp_Allow_Level_t;

typedef enum
{
    OD_DIR_EGO_MOT_UNKNOWN = ZERO,
    OD_DIR_EGO_MOT_D,
    OD_DIR_EGO_MOT_R,
    OD_DIR_EGO_MOT_MAX,
} US_E_Dir_Ego_Motion_t;

/*
 * ********* TEMPORARY CODE UNTIL CALIBRATION UPDATES ARE DONE *********
 */
#if 0
typedef struct UssObjDet_SnrLoc_s
{
    float32_t fX;
    float32_t fY;
    float32_t fZ;
    float32_t fAngAlpha;
    float32_t fAngBeta;
    uint8_t   uSnrType;  //0 = pdc, 1 = psm
} UssOD_SnrLoc_t;
#endif
/* Output Buffers */

typedef struct US_S_Point_s
{
    sint16_t x;
    sint16_t y;
    uint8_t  height;
    uint8_t  cruising_age;
    uint8_t  confidence;
    uint8_t  age;
} US_S_Point_t;


#ifdef DEBUG_VISUAL_TOOL_CAN_MSGS_ENABLE
typedef struct US_S_PntDebugInfo_s
{
    uint8_t   uCmdId;           /*  1  */
    uint8_t   uOutputId;        /*  2  */
    uint8_t   uGrpIdx;          /*  3  */
    uint8_t   uPntIdx;          /*  4  */
    uint8_t   uDirSnrIdx;       /*  5  */
    uint8_t   uIndirSnrIdx;     /*  6  */
    uint16_t  uLowDirDist;      /*  7  */
    uint16_t  uIndirDist;       /*  9  */
    uint16_t  uBaseDist;        /* 14 */
    uint16_t  uPntStat;         /* 12  - Bit encoded.  See US_D_PNTSTAT_ */
    uint8_t   uSectorIdx;       /* 11  */
    uint8_t   Reserved_16;
} US_S_PntDebugInfo_t;
#endif

typedef struct US_S_PointMap_s
{
    uint32_t uTimestamp;
    US_S_Point_t sPointMap[US_D_POINTMAP_OUT_SIZE];
} US_S_PointMap_t;

#define US_D_OD_NO_INDIR_SNR (0xFFu)

enum US_E_SnrDir_e
{
    US_INDIR_LEFT = ZERO,
    US_INDIR_RIGHT
};

typedef struct US_S_IndirSnrIdxList_s
{
    uint8_t uIndirSnrDataIdx;
    uint8_t uFovCalcIdx;
} US_S_IndirSnrIdxList_t;

typedef struct US_S_SnrAngleCalcs_s
{
    float32_t fSnrAngInVehCoords_rad[US_D_MAX_NUM_SENSORS];
} US_S_SnrAngleCalcs_t;

typedef struct US_S_DrivingTubeInfo_s
{
    float32_t fTubeEdgeY;
    float32_t fFrontBumperX;
    float32_t fFrontSnrClsX;
    float32_t fRearBumperX;
    float32_t fRearSnrClsX;
} US_S_DrivingTubeInfo_t;

void UssOD_Init(void);
void UssOD_InitCalData(void);
void UssOD_FovPreprocessing(void);
void UssOD_SectorPreprocessing(void);
uint8_t UssOD_uFindSectorIdx(float32_t fX, float32_t fY, uint8_t uCurSecIdx);
const US_S_IndirSnrIdxList_t * UssOD_psGetIndirSnrList(uint8_t uGrpIdx, uint8_t uGroupSnrIdx);
const US_S_SnrAngleCalcs_t * UssOD_psGetSnrAngleCalcs(void);
void UssOD_Main(void);

#ifdef US_D_OD_HEIGHT_GEOM_STATS
bool_t UssOD_IsGrpGeomHigh(uint8_t uGrpIdx);
float32_t UssOD_GetGeomDebugFloat(uint8_t uSelection);
uint32_t UssOD_GetGeomDebug(uint8_t uSelection);
#endif
/*#ifdef US_D_OD_HEIGHT_GEOM_STATS - always needed since PA externs this*/
uint8_t UssOD_bIsLowObjectRear(void);
bool_t UssOD_bIsHighObjectRear(void);
US_E_Grp_Allow_Level_t UssOD_eGetGrpAllowLevel(uint8_t uGrpIdx);

US_S_DrivingTubeInfo_t * UssOD_psGetDrivingTubeInfo(void);
#endif /* US_OBJDET_GLOBAL_H_ */
