/*
 * US_SnrDrvMgr.h
 *
 *  Created on: Feb 25, 2021
 *      Author: e39960
 */

#ifndef SOURCES_US_SNRDRV_US_SnrDrvMgr_F_GLOBAL_H_
#define SOURCES_US_SNRDRV_US_SnrDrvMgr_F_GLOBAL_H_
#include "US_Data_Typedefs_Global.h"

EXTERN uint32_t US_SnrDrvMgr_F_TuningSetProfileCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetProfileCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetProfilePlusCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_TuningSetProfilePlusCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetFTCCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetATGCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetAATG1Cmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetAATG2Cmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetNFDCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetGanaMeasBeginCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetSensorEEFlagVarCTRLCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetEDIChannelCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetSTCCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetSTGCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetFCCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetNormalBurstNumCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetSensorOPModeCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetSensorRegisterCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetSensorEEPROMCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetSensorAmbiTempCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetFixPathCfgCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetGainCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetDSIMasterRegCmd(uint32_t SnrMap,uint32_t UserData,uint16_t RegAddr,uint16_t len,uint8_t const *sndData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));

EXTERN uint32_t US_SnrDrvMgr_F_SetMaxEchoNumCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetEnvFiltCfgCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetEnvCfgCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetCalGainCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetBurstTypeCfgCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetChirpBWCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetCurrentCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetEEVALSENSMEASCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetADDRBYEEPROMCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SetDSIMasterRegByTableCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_SensorMarrage(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReleaseReset_DSI3TranceiverCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_Reset_DSI3TranceiverCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_Cfg_DSI3TranceiverCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));

EXTERN uint32_t US_SnrDrvMgr_F_AutoAddressingCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData)); 
EXTERN uint32_t US_SnrDrvMgr_F_ReqDSIMasterRegByTableCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqSnrFWVer(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqSensorIDCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqSensorAmbiTempCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqSensorRegisterCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqSensorDiagnosticResultCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqSensorOPModeCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqSensorTempCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqSensorFreqCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqGanaMeasBeginCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqSensorEEFlagCTRL(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqCPSMeasGainCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqEnvDataCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqEDIChannelCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqNFDCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqFixPathCfgCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqMaxEchoNumCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqEnvFiltCfgCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqEnvCfgCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqCalGainCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqGainCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqCurrentCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqBurstTypeCfgCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqRingingCompCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData)); 
EXTERN uint32_t US_SnrDrvMgr_F_ReqChirpBWCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqNormalBurstNumCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqFCCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqAATG2Cmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqAATG1Cmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqATGCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqFTCCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqSTCCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqSTGCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqSensorEEPROMCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqSendBurstCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqSendBurstWDelayCmd(uint32_t SnrMap,uint8_t delay,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqProfileCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqProfilePlusCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqEEVALSensMeasCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqRFMCtrlCmd(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqADVoltager(uint32_t SnrMap,uint32_t UserData,uint16_t sndlen,uint8_t const *sndData,uint16_t rcvlen, uint8_t* rcvData,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));
EXTERN uint32_t US_SnrDrvMgr_F_ReqDSIMasterRegCmd(uint32_t SnrMap,uint32_t UserData,uint16_t RegAddr,uint16_t len,uint8_t *data,void (*CallBack)(uint32_t ErrorCode,uint32_t Cmd,uint32_t UserData,uint16_t RcvSize,uint8_t *RcvData));

EXTERN void US_SnrDrvCom_F_Task(void);

#endif /* SOURCES_US_SNRDRV_US_SnrDrvMgr_F_H_ */
