#ifndef SIGNALMGRSIGTYPES_H_INCGUARD
#define SIGNALMGRSIGTYPES_H_INCGUARD

//Selection of current core used for the build
//Need to be configured for every project
#if defined(BUILD_MCU2_0) 
	#include "SSM_Defs.h"
	#include "ErrorManagerDef.h"
	#include "CalDataProvider_defs.h"
	#include "VehicleInputAdapterDataTypes.h"
	#include "ProxiMgrIpcDataTypes.h"
	#include "TRSC_Inputs_Outputs.h"
	#include "HMI_SVS.h"
	#include "AutoPark_Input_Output.h"
	#include "NFCD_Input_Output.h"
	#include "MOT_Input_Output.h"
	#include "APFusion_Interface.h"
	#include "THA_SM_VC_Inputs_Outputs.h"
	#include "DegManager_Inputs_Outputs.h"
	#include "LMD_Input_Output.h"
	#include "InterfaceSignalForTestPatternRoutine.h"
	#include "ME_CalibSVS.h"
	#include "VoltageCurrent_data.h"
	#include "FOD_Input_Output.h"
	#include "CPU_Load_Ipc_Signal.h"
	#include "WdgGlobal.h"
	#include "APDiagDataTypes.h"
	#include "TimeManagerProxyTypes.h"
	#include "ProxiParameters.h"
	#include "RunTimeStatsIpc.h"
	#include "CamTypes.h"
#elif defined(BUILD_MCU2_1) 
//	#include "CommonDataTypeRef.h"
	#include "TRSC_Inputs_Outputs.h"	
	#include "ME_CalibSVS.h"
	#include "HMI_SVS.h"
	#include "VehicleInputAdapterDataTypes.h"
	#include "ProxiMgrIpcDataTypes.h"
	#include "ErrorManagerDef.h"
	#include "SSM_Defs.h"
	#include "CalDataProvider_defs.h"
	#include "AutoPark_Input_Output.h"
	#include "NFCD_Input_Output.h"	
	#include "MOT_Input_Output.h"	
	#include "APFusion_Interface.h"
	#include "THA_SM_VC_Inputs_Outputs.h"
	#include "THA_Detection_Inputs_Outputs.h"
	#include "DegManager_Inputs_Outputs.h"
	#include "USS_Inputs_Outputs.h"
	#include "VoltageCurrent_data.h"
	#include "FOD_Input_Output.h"
	#include "APDiagDataTypes.h"
	#include "CPU_Load_Ipc_Signal.h"
	#include "FeatureArbiterOutputs.h"
	#include "WdgGlobal.h"
	#include "TimeManagerProxyTypes.h"
	#include "RunTimeStatsIpc.h"
#elif defined(BUILD_MCU3_0) 
	#include "CommonDataTypeRef.h"
#elif defined(BUILD_MCU3_1) 
	#include "CommonDataTypeRef.h"
#elif defined(BUILD_MCU1_0) 
	//#include "CommonDataTypeRef.h"
	//#include "APFusion_Interface.h"
	#include "../../magna_apps/KM/code/JobKM.h"
	#include "VehicleInputAdapterDataTypes.h"
	#include "ProxiMgrIpcDataTypes.h"
	#include "CalibIpcDataTypes.h"
	#include "Rte_CDD_IPCHandler.h"
	#include "CalDataProvider_defs.h"
	#include "DegManager_Inputs_Outputs.h"
	#include "VoltageCurrent_data.h"
	#include "InterfaceSignalForTestPatternRoutine.h"
	#include "APDiagDataTypes.h"
	#include "USS_Inputs_Outputs.h"
	#include "WdgGlobal.h"
	#include "TimeManagerProxyTypes.h"
	#include "RunTimeStatsIpc.h"
#elif defined(BUILD_MPU1_0) 
	//#include "CommonDataTypeRef.h"
	#include "ErrorManagerDef.h"
	#include "HMI_SVS.h"
	#include "ME_CalibSVS.h"
	#include "TRSC_Inputs_Outputs.h"	
	#include "VehicleInputAdapterDataTypes.h"
	#include "ProxiMgrIpcDataTypes.h"
	#include "CalDataProvider_defs.h"
	#include "SSM_Defs.h"
	#include "AutoPark_Input_Output.h"
	#include "NFCD_Input_Output.h"
	#include "MOT_Input_Output.h"
	#include "APFusion_Interface.h"
	#include "THA_SM_VC_Inputs_Outputs.h"
	#include "THA_Detection_Inputs_Outputs.h"
	#include "USS_Inputs_Outputs.h"
	#include "LMD_Input_Output.h"
	#include "CamTypes.h"
	#include "FOD_Input_Output.h"
	#include "WdgGlobal.h"
	#include "ProxiParameters.h"
	#include "DLD_Input_Output.h"
	#include "RunTimeStatsIpc.h"
#else
	//#warning "Need to define a BUILD version to ErrorManagerCore to use this file"
	#define ERRORMGR_CURRENTCORE ERRORMGRCORE_CORE_MAX
#endif


#endif
